function renderOverview() {
  const s = stats();
  $('overallScore').nextElementSibling.textContent = '/ 5.0'; $('overallMeter').closest('.score-panel').querySelector('.score-foot').innerHTML = '<span>1 Initial</span><span>5 Optimized</span>'; const maturityLegend = $('recommendations').closest('.view')?.querySelector('.legend-panel .legend-list'); if (maturityLegend) maturityLegend.innerHTML = '<div><b>1</b><span><strong>Initial</strong><small>Privacy and security practices are absent or ad hoc.</small></span></div><div><b>2</b><span><strong>Repeatable</strong><small>Basic practices exist but vary.</small></span></div><div><b>3</b><span><strong>Defined</strong><small>Documented and repeatable practices.</small></span></div><div><b>4</b><span><strong>Managed</strong><small>Measured and consistently governed.</small></span></div><div><b>5</b><span><strong>Optimized</strong><small>Continuously improving and adaptive.</small></span></div>';
  $('overallScore').textContent = s.average.toFixed(1); $('overallLabel').textContent = s.scored.length ? maturityLabels[Math.round(s.average)] : 'Not assessed'; $('overallMeter').style.width = `${s.average / 5 * 100}%`;
  $('completionValue').textContent = `${s.completion}%`; $('completionDetail').textContent = `${s.scored.length} of ${s.controls.length} controls scored`; $('completionRing').style.transform = `rotate(${s.completion * 3.6}deg)`; $('gapValue').textContent = s.gaps;
  $('functionCards').innerHTML = functions.map(fn => { const controls = controlsFor(fn); const policy = controls.map(item => policyScoreFor(item.id)).filter(value => value !== null); const practice = controls.map(item => scoreFor(item.id)).filter(value => value !== null); const policyAverage = policy.length ? policy.reduce((a, b) => a + b, 0) / policy.length : null; const practiceAverage = practice.length ? practice.reduce((a, b) => a + b, 0) / practice.length : null; const displayAverage = [policyAverage, practiceAverage].filter(value => value !== null).reduce((sum, value, _, values) => sum + value / values.length, 0); return `<article class="function-card" data-function="${fn.id}"><div class="card-top"><div><p class="eyebrow">${fn.id} / ${controls.length} controls</p><h4>${fn.name}</h4><p>${fn.description}</p></div></div><div class="coverage-scores"><div class="coverage-score"><small>Policy</small><strong>${policyAverage === null ? '-' : policyAverage.toFixed(1)}</strong></div><div class="coverage-score"><small>Practice</small><strong>${practiceAverage === null ? '-' : practiceAverage.toFixed(1)}</strong></div></div><div class="card-bar"><span style="width:${Math.min(displayAverage / 5 * 100, 100)}%"></span></div></article>`; }).join('');
  document.querySelectorAll('.function-card').forEach(card => card.addEventListener('click', () => showAssessment(card.dataset.function)));
  const low = allControls().map(item => ({ name: item.name, fn: item.fn, score: scoreFor(item.id) })).sort((a, b) => (a.score ?? -1) - (b.score ?? -1)).slice(0, 3);
  $('recommendations').innerHTML = low.map(item => `<div class="recommendation"><b>${item.score === null ? '!' : item.score}</b><div><strong>${item.name}</strong><small>${item.fn.name} · ${item.score === null ? 'Needs assessment' : 'Below target maturity'}</small></div></div>`).join('');
  renderSummary();
}
function setCsfTab(tab) {
  const view = $('csfView');
  const buttons = view.querySelectorAll('[data-csf-tab]');
  const children = [...view.children];
  const coreStart = children.findIndex(child => child.classList.contains('page-heading') && child.textContent.includes('CSF 2.0 Core'));
  if (coreStart < 0) return;
  children.forEach((child, index) => {
    if (child.classList.contains('risk-management-tabs') || child.matches('dialog, [data-module-transfer]')) return;
    child.hidden = tab === 'core' ? index < coreStart : index >= coreStart;
  });
  buttons.forEach(button => {
    const active = button.dataset.csfTab === tab;
    button.classList.toggle('button-accent', active);
    button.classList.toggle('button-quiet', !active);
  });
}
function renderSummary() {
  const summaries = categorySummary(); const policyValues = summaries.filter(summary => summary.policy !== null); const practiceValues = summaries.filter(summary => summary.practice !== null); const averagePolicy = policyValues.length ? policyValues.reduce((sum, summary) => sum + summary.policy, 0) / policyValues.length : null; const averagePractice = practiceValues.length ? practiceValues.reduce((sum, summary) => sum + summary.practice, 0) / practiceValues.length : null;
  const targetAverage = summaries.length ? summaries.reduce((sum, summary) => sum + csfTargetScoreFor(summary.category), 0) / summaries.length : 3; document.querySelectorAll('#csfView .target-chip b').forEach(element => { element.textContent = targetAverage.toFixed(1); }); $('csfSummaryBody').innerHTML = `<tr class="summary-overall"><td colspan="2">Overall Average Score</td><td></td><td>${targetAverage.toFixed(1)}</td><td>${averagePolicy === null ? '-' : averagePolicy.toFixed(1)}</td><td>${averagePractice === null ? '-' : averagePractice.toFixed(1)}</td></tr>` + summaries.map(summary => `<tr><td>${summary.fn.id}</td><td>${escapeHtml(summary.category)}</td><td>${summary.count}</td><td><input class="privacy-target-input" type="number" min="0" max="4" step="0.1" value="${csfTargetScoreFor(summary.category).toFixed(1)}" data-csf-target-category="${escapeHtml(summary.category)}" aria-label="Target score for ${escapeHtml(summary.category)}"></td><td>${summary.policy === null ? '-' : summary.policy.toFixed(1)}</td><td>${summary.practice === null ? '-' : summary.practice.toFixed(1)}</td></tr>`).join('');
  document.querySelectorAll('[data-csf-target-category]').forEach(input => input.addEventListener('change', async event => { const category = event.target.dataset.csfTargetCategory; const value = Number(event.target.value); if (!Number.isFinite(value) || value < 0 || value > 4) { event.target.value = csfTargetScoreFor(category).toFixed(1); return; } const previous = csfTargetScoreFor(category); state.targetScores[category] = Math.round(value * 10) / 10; try { await persistCategoryTarget('csf', category, state.targetScores[category]); save(); renderOverview(); } catch (error) { state.targetScores[category] = previous; renderOverview(); } }));
  renderRadar();
}
function renderRadar() {
  const canvas = $('maturityRadar'); const context = canvas.getContext('2d'); const bounds = canvas.getBoundingClientRect(); const ratio = window.devicePixelRatio || 1; const width = Math.max(bounds.width, 320); const height = 430; canvas.width = width * ratio; canvas.height = height * ratio; context.setTransform(ratio, 0, 0, ratio, 0, 0); context.clearRect(0, 0, width, height);
  const summaries = categorySummary(); const average = values => { const scored = values.filter(value => value !== null); return scored.length ? scored.reduce((sum, value) => sum + value, 0) / scored.length : 0; }; const labels = ['Overall Average Score', ...summaries.map(summary => summary.category)]; const series = { target: labels.map(() => 3), policy: [average(summaries.map(summary => summary.policy)), ...summaries.map(summary => summary.policy ?? 0)], practice: [average(summaries.map(summary => summary.practice)), ...summaries.map(summary => summary.practice ?? 0)] }; const active = Object.fromEntries([...document.querySelectorAll('.radar-series')].map(button => [button.dataset.series, button.classList.contains('active')])); const centerX = width / 2; const centerY = height / 2 - 4; const radius = Math.min(width * .29, 145); const angle = Math.PI * 2 / labels.length; const point = (value, index, extra = 0) => { const currentAngle = index * angle - Math.PI / 2; const distance = radius * (value / 5) + extra; return [centerX + Math.cos(currentAngle) * distance, centerY + Math.sin(currentAngle) * distance]; };
  const drawSeries = (values, color, fill = '') => { const points = values.map((value, index) => point(value, index)); context.beginPath(); points.forEach(([x, y], index) => index ? context.lineTo(x, y) : context.moveTo(x, y)); context.closePath(); if (fill) { context.fillStyle = fill; context.fill(); } context.strokeStyle = color; context.lineWidth = 2; context.stroke(); points.forEach(([x, y]) => { context.beginPath(); context.arc(x, y, 3, 0, Math.PI * 2); context.fillStyle = color; context.fill(); }); };
  context.font = '10px DM Sans'; context.textAlign = 'center'; context.textBaseline = 'middle';
  for (let level = 1; level <= 5; level += 1) { context.beginPath(); labels.forEach((_, index) => { const [x, y] = point(level, index); index ? context.lineTo(x, y) : context.moveTo(x, y); }); context.closePath(); context.strokeStyle = '#e3ebe6'; context.lineWidth = 1; context.stroke(); context.fillStyle = '#93a49d'; context.fillText(level, centerX + 8, centerY - radius * level / 5); }
  labels.forEach((label, index) => { const [x, y] = point(5, index); context.beginPath(); context.moveTo(centerX, centerY); context.lineTo(x, y); context.strokeStyle = '#e3ebe6'; context.stroke(); const categoryCode = label.match(/\(([^)]+)\)$/)?.[1] || label; const labelOffset = index % 2 ? 25 : 31; const [labelX, labelY] = point(5, index, labelOffset); context.fillStyle = '#536b64'; context.font = '9px DM Sans'; context.fillText(categoryCode, labelX, labelY); });
  if (active.target) { context.setLineDash([5, 4]); drawSeries(series.target, '#d3b55b'); context.setLineDash([]); } if (active.policy) drawSeries(series.policy, '#e89065'); if (active.practice) drawSeries(series.practice, '#267256', 'rgba(38,114,86,.18)');
  canvas.radarPoints = labels.map((label, index) => { const coordinates = point(series.practice[index], index); return { label, policy: series.policy[index], practice: series.practice[index], target: 3, x: coordinates[0], y: coordinates[1] }; });
}
function renderCsfTable() {
  const query = $('csfSearchInput').value.toLowerCase(); const filter = $('csfFunctionFilter').value;
  const rows = sortAssessmentRows(allControls().filter(item => (filter === 'all' || item.fn.id === filter) && `${item.fn.name} ${item.name} ${item.code} ${item.category}`.toLowerCase().includes(query)), csfSort);
  csfCorePage = renderAssessmentPagination('csfCorePagination', csfCorePage, rows.length); const visibleRows = rows.slice((csfCorePage - 1) * 20, csfCorePage * 20);
  $('csfTableBody').innerHTML = visibleRows.map(item => `<tr><td>${escapeHtml(item.fn.id)}<br>${escapeHtml(item.fn.name)}</td><td>${escapeHtml(item.category || 'CSF Core')}</td><td>${escapeHtml(item.subcategory)}</td><td>${escapeHtml(item.implementation)}</td><td>${escapeHtml(item.references)}</td><td>${attachmentControl(item, 'policy')}</td><td><textarea class="reasoning-input" data-reasoning="policy-${escapeHtml(item.id)}" placeholder="Why this policy score?"></textarea></td><td>${attachmentControl(item, 'practice')}</td><td><textarea class="reasoning-input" data-reasoning="practice-${escapeHtml(item.id)}" placeholder="Why this practice score?"></textarea></td><td><button class="attachment-action-button" type="button" data-open-csf-modal="${escapeHtml(item.id)}">Edit</button><button class="attachment-action-button danger" type="button" data-delete-csf-control="${escapeHtml(item.id)}">Delete</button></td></tr>`).join('') || '<tr><td colspan="10">No CSF controls match this filter.</td></tr>';
  renderScoreControls();
  document.querySelectorAll('[data-reasoning]').forEach(input => { const key = input.dataset.reasoning; input.value = state.notes[key] || ''; input.addEventListener('input', () => { state.notes[key] = input.value; save(); }); });
  document.querySelectorAll('[data-assessment-score]').forEach(button => button.addEventListener('click', () => { const score = Number(button.dataset.assessmentScore); if (button.dataset.scoreType === 'policy') state.policyScores[button.dataset.control] = score; else state.practiceScores[button.dataset.control] = score; save(); renderCsfTable(); renderOverview(); }));
  document.querySelectorAll('[data-attachment]').forEach(input => input.addEventListener('change', event => uploadAttachment(event.target)));
  document.querySelectorAll('[data-replace-attachment]').forEach(input => input.addEventListener('change', event => replaceAttachment(event.target)));
  document.querySelectorAll('[data-open-csf-modal]').forEach(button => button.addEventListener('click', () => openCsfControlModal(button.dataset.openCsfModal)));
  document.querySelectorAll('[data-delete-csf-control]').forEach(button => button.addEventListener('click', () => deleteCsfControl(button.dataset.deleteCsfControl)));
  document.querySelectorAll('#csfTableBody [data-delete-attachment]').forEach(button => button.addEventListener('click', () => deleteAttachment(button.dataset.deleteAttachment, Number(button.dataset.attachmentIndex))));
  document.querySelectorAll('#csfTableBody [data-open-attachment]').forEach(button => button.addEventListener('click', () => openAttachment(button.dataset.openAttachment, Number(button.dataset.attachmentIndex))));
  document.querySelectorAll('#csfTableBody [data-download-attachment]').forEach(button => button.addEventListener('click', () => downloadAttachment(button.dataset.downloadAttachment, Number(button.dataset.attachmentIndex))));
}
function sortAssessmentRows(rows, sortField) {
  return [...rows].sort((first, second) => {
    const firstValue = sortField === 'function' ? first.fn?.name : first[sortField];
    const secondValue = sortField === 'function' ? second.fn?.name : second[sortField];
    return String(firstValue || '').localeCompare(String(secondValue || ''), undefined, { numeric: true, sensitivity: 'base' });
  });
}
async function loadCsfData() { const [response, targetResponse] = await Promise.all([fetch('/api/csf', { cache: 'no-store' }), fetch('/api/frameworks/csf/targets', { cache: 'no-store' })]); if (!response.ok) throw new Error('CSF data unavailable'); csfRows = await response.json(); if (targetResponse.ok) state.targetScores = Object.fromEntries((await targetResponse.json()).map(row => [row.category, Number(row.targetScore)])); renderOverview(); renderCsfTable(); renderUploadedFiles(); renderCsfManager(); if ($('assessmentView').classList.contains('active-view')) renderControls(); }
let iso27001Rows = [];
let iso27001Page = 1;
