function showAssessment(id) {
  if (currentUserRole !== 'admin' && !currentUserPermissions.includes('assessment')) return; activeFunction = id; const fn = functions.find(item => item.id === id); document.querySelectorAll('.view').forEach(view => view.classList.remove('active-view')); $('assessmentView').classList.add('active-view'); $('assessmentTitle').textContent = fn.name; $('assessmentDescription').textContent = fn.description; $('assessmentKicker').textContent = `${fn.id} / NIST CSF CORE`; renderControls(); saveUiState('assessment', id); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.function === id));
}
function renderControls() {
  const fn = functions.find(item => item.id === activeFunction); const controls = controlsFor(fn); const filtered = controls.filter(item => { const query = $('searchInput').value.toLowerCase(); const score = scoreFor(item.id); const filter = $('statusFilter').value; return item.name.toLowerCase().includes(query) && (filter === 'all' || (filter === 'unscored' && score === null) || (filter === 'scored' && score !== null) || (filter === 'gaps' && (score === null || score < 3))); });
  const scored = controls.filter(item => scoreFor(item.id) !== null).length; $('functionProgress').textContent = `${scored} / ${controls.length}`; $('functionMeter').style.width = `${controls.length ? scored / controls.length * 100 : 0}%`;
  csfAssessmentPage = renderAssessmentPagination('csfAssessmentPagination', csfAssessmentPage, filtered.length); const visible = filtered.slice((csfAssessmentPage - 1) * 20, csfAssessmentPage * 20); $('controlList').innerHTML = visible.map(item => `<div class="control-row"><div><div class="control-code">${item.code}</div><div class="control-title">${item.name}</div><div class="control-question">Isi dua nilai terpisah untuk Policy Maturity dan Practice Maturity.</div></div><div><div class="assessment-score-group"><span class="eyebrow">Policy Evidence</span>${attachmentControl(item, 'policy')}</div><div class="assessment-score-group practice"><span class="eyebrow">Practice Evidence</span>${attachmentControl(item, 'practice')}</div></div><div><div class="action-note-group"><span class="eyebrow">Policy Action Notes</span><input class="notes-input" data-note="policy-${item.id}" placeholder="Add policy action note..."></div><div class="action-note-group practice"><span class="eyebrow">Practice Action Notes</span><input class="notes-input" data-note="practice-${item.id}" placeholder="Add practice action note..."></div></div></div>`).join('') || '<div class="control-row">No controls match this filter.</div>';
  renderScoreControls();
  document.querySelectorAll('[data-note]').forEach(input => { const controlId = input.dataset.note.replace(/^(policy|practice)-/, ''); const legacyNote = state.notes[controlId]; input.value = state.notes[input.dataset.note] || legacyNote || ''; input.addEventListener('input', () => { state.notes[input.dataset.note] = input.value; save(); }); });
  document.querySelectorAll('[data-assessment-score]').forEach(button => button.addEventListener('click', () => { const score = Number(button.dataset.assessmentScore); if (button.dataset.scoreType === 'policy') state.policyScores[button.dataset.control] = score; else state.practiceScores[button.dataset.control] = score; save(); renderControls(); renderOverview(); }));
  document.querySelectorAll('[data-attachment]').forEach(input => input.addEventListener('change', event => uploadAttachment(event.target)));
  document.querySelectorAll('[data-replace-attachment]').forEach(input => input.addEventListener('change', event => replaceAttachment(event.target)));
  document.querySelectorAll('[data-delete-attachment]').forEach(button => button.addEventListener('click', () => deleteAttachment(button.dataset.deleteAttachment, Number(button.dataset.attachmentIndex))));
  document.querySelectorAll('[data-open-attachment]').forEach(button => button.addEventListener('click', () => openAttachment(button.dataset.openAttachment, Number(button.dataset.attachmentIndex))));
  document.querySelectorAll('[data-download-attachment]').forEach(button => button.addEventListener('click', () => downloadAttachment(button.dataset.downloadAttachment, Number(button.dataset.attachmentIndex))));
}
