const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const vm = require('node:vm');
const sidebar = fs.readFileSync('frontend/client/src/workspace/components/AppSidebar.vue', 'utf8');
const runtime = fs.readFileSync('frontend/client/src/workspace/features/shared/event-bindings.js', 'utf8');
test('Asset Management opens and closes through the shared sidebar handler', () => {
  const markup = sidebar.match(/<section class="sidebar-group" id="assetNavGroup">([\s\S]*?)<\/section>/)[1];
  const classes = new Set();
  const attributes = { 'aria-expanded': 'true' };
  const listeners = [];
  const items = {hidden:false};
  const button = {setAttribute:(key,value)=>attributes[key]=value,addEventListener:(type,callback)=>{if(type==='click')listeners.push(callback);}};
  const group = {classList:{toggle:(name,on)=>on?classes.add(name):classes.delete(name),contains:name=>classes.has(name)},querySelector:()=>button,contains:()=>false};
  const context = vm.createContext({document:{querySelectorAll:()=>[group],querySelector:()=>null,getElementById:()=>items},MutationObserver:class{observe(){}}});
  const inline = markup.match(/onclick="([^"]*)"/);
  if (inline) listeners.push(()=>vm.runInContext(inline[1],context));
  vm.runInContext(runtime.slice(runtime.indexOf('const sidebarGroups ='),runtime.indexOf('syncActiveSidebarGroup();')+'syncActiveSidebarGroup();'.length),context);
  assert.equal(classes.has('is-collapsed'),true);
  for(const callback of listeners)callback();
  assert.equal(classes.has('is-collapsed'),false);
  assert.equal(items.hidden,false,'Expanded Asset Management must keep submenu content visible');
  assert.equal(attributes['aria-expanded'],'true');
  for(const key of ['asset-register','server-racks','asset-modelling']) assert.ok(markup.includes(`data-view="${key}"`));
  for(const callback of listeners)callback();
  assert.equal(classes.has('is-collapsed'),true);
  assert.equal(attributes['aria-expanded'],'false');
  for(const callback of listeners)callback();
  assert.equal(classes.has('is-collapsed'),false);
  assert.equal(items.hidden,false);
});
