const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs/promises');
const os = require('node:os');
const path = require('node:path');
const access = require('../src/services/evidenceAccessService');
const { pool } = require('../src/config/database');
test('evidence path validation rejects traversal and absolute paths', () => {
  assert.equal(access.normalize('upload/Govern/Policy/test.pdf'),'Govern/Policy/test.pdf');
  for (const value of ['../test.pdf','upload/../test.pdf','/etc/passwd','C:\\test.pdf',null]) assert.throws(()=>access.normalize(value));
});
test('uploader isolation across upload, file routes, assessment and framework references', {skip:process.env.RUN_EVIDENCE_DB_TESTS!=='1'}, async t => {
  const client=await pool.connect(); const directory=await fs.mkdtemp(path.join(os.tmpdir(),'evidence-owner-')); let server;
  try {
    await client.query('CREATE TEMP TABLE role_permissions(role TEXT,permission_key TEXT,allowed BOOLEAN,actions JSONB)');
    await client.query("INSERT INTO role_permissions VALUES('user','files',true,NULL)");
    await client.query('CREATE TEMP TABLE app_users(id BIGINT PRIMARY KEY,username TEXT UNIQUE)');
    await client.query("INSERT INTO app_users VALUES(1,'alice'),(2,'bob'),(3,'admin')");
    await client.query('CREATE TEMP TABLE evidence_files(path TEXT PRIMARY KEY,name TEXT,content BYTEA,mime_type TEXT,open_page INTEGER NOT NULL DEFAULT 1,updated_at TIMESTAMPTZ DEFAULT NOW())');
    await client.query(await fs.readFile(path.join(__dirname,'../database/evidence-ownership.sql'),'utf8'));
    await client.query(await fs.readFile(path.join(__dirname,'../database/evidence-ownership.sql'),'utf8'));
    await client.query('CREATE TEMP TABLE file_storage_settings(id INTEGER PRIMARY KEY,mode TEXT,directory TEXT,updated_at TIMESTAMPTZ DEFAULT NOW())');
    await client.query('CREATE TEMP TABLE file_storage_locations(path TEXT PRIMARY KEY,root TEXT,object_key TEXT,updated_at TIMESTAMPTZ DEFAULT NOW())');
    await client.query('CREATE TEMP TABLE assessment_state(id TEXT PRIMARY KEY,data JSONB,updated_at TIMESTAMPTZ DEFAULT NOW())');
    await client.query('CREATE TEMP TABLE controls(framework_id TEXT,code TEXT,evidence JSONB,updated_at TIMESTAMPTZ)');
    await client.query('CREATE TEMP TABLE policy_register(id BIGINT,title TEXT,attachment_path TEXT,attachment_name TEXT,attachment_type TEXT,updated_at TIMESTAMPTZ)');
    await client.query('CREATE TEMP TABLE policy_register_items(id BIGINT,policy_id BIGINT,subtitle TEXT,content TEXT,sort_order INTEGER)');
    await client.query('CREATE TEMP TABLE tprm_due_diligence_questionnaires(responses JSONB,updated_at TIMESTAMPTZ)');
    await client.query('CREATE TEMP TABLE audit_finding_records(id TEXT,data JSONB,filename TEXT,content BYTEA,updated_at TIMESTAMPTZ)');
    const db={query:client.query.bind(client),connect:async()=>({query:client.query.bind(client),release(){}})};
    t.mock.method(pool,'query',db.query);t.mock.method(pool,'connect',db.connect);
    const storage=require('../src/services/storageService');
    const isolated=storage.createStorageService({db,localRoot:directory,applicationRoot:directory});
    for(const name of ['put','read','exists','remove'])t.mock.method(storage,name,isolated[name]);
    const files=require('../src/services/fileService');
    const alice={username:'alice',role:'user'},bob={username:'bob',role:'user'},admin={username:'admin',role:'admin'};
    async function upload(user,content){const temp=path.join(directory,Math.random()+'.pdf');await fs.writeFile(temp,content);return files.saveFile({functionName:'Govern',kind:'policy',uploadedBy:await access.userId(user),rejectDuplicate:true,file:{path:temp,originalname:'same.pdf',mimetype:'application/pdf',size:content.length}});}
    const a=await upload(alice,'%PDF Alice'),b=await upload(bob,'%PDF Bob');
    assert.notEqual(a.path,b.path,'same filename for different users must not reuse another owner file');
    const aSecond=await upload(alice,'%PDF Alice second');
    assert.notEqual(a.path,aSecond.path,'same filename for the same user must receive a unique identifier');
    await client.query("INSERT INTO evidence_files(path,name,mime_type) VALUES('Govern/Policy/legacy.pdf','legacy.pdf','application/pdf')");
    assert.deepEqual(new Set((await access.list(alice)).map(f=>f.path)),new Set([a.path,aSecond.path]));
    assert.deepEqual((await access.list(bob)).map(f=>f.path),[b.path]);
    assert.equal((await access.list(admin)).length,4);
    await client.query('INSERT INTO policy_register(id,title,attachment_path) VALUES(1,$1,$2),(2,$3,$4)',['Access policy',a.path,'Private policy',b.path]);
    await client.query("INSERT INTO policy_register_items VALUES(1,1,'Access review','Review privileged accounts every quarter',0),(2,2,'Restricted subtitle','Private content Bob',0)");
    const searchable=await access.searchableList(alice);
    assert.equal(searchable.find(file=>file.path===a.path).policyDetails[0].content,'Review privileged accounts every quarter');
    assert.equal(searchable.find(file=>file.path===a.path).source,'Policy Register');
    assert.equal(JSON.stringify(searchable).includes('Private content Bob'),false);
    assert.equal((await access.searchableList(admin)).find(file=>file.path===b.path).policyDetails[0].content,'Private content Bob');
    await client.query('DELETE FROM policy_register_items');
    await client.query('DELETE FROM policy_register');
    await assert.rejects(access.assertAccess(b.path,alice),{status:403});
    await assert.rejects(access.assertReadAccess(b.path,alice),{status:403});
    await access.assertReadAccess(a.path,alice);
    await access.assertReadAccess(b.path,admin);
    await assert.rejects(access.assertAccess('upload/Govern/Policy/legacy.pdf',alice),{status:403});
    await access.assertAccess(b.path,admin);
    await files.replaceFile(a.path.replace('upload/',''),{buffer:Buffer.from('%PDF Updated'),originalname:'new.pdf',mimetype:'application/pdf',size:12});
    assert.equal(String((await client.query('SELECT uploaded_by FROM evidence_files WHERE path=$1',[access.normalize(a.path)])).rows[0].uploaded_by),'1','replacement preserves original uploader');
    await assert.rejects(access.assertReferences([{path:b.path}],[],alice),{status:403});
    await access.assertReferences([{path:b.path}],[{path:b.path}],alice); // preserve existing shared references, but cannot select them elsewhere
    await access.assertReferences([{path:b.path}],[],admin);
    await assert.rejects(access.assertReferences({},[],alice),{status:400});
    const assessment=require('../src/controllers/assessmentController');
    const response={json(){},status(){return this;}};
    await client.query('INSERT INTO assessment_state VALUES($1,$2,NOW())',['default',{attachments:{existing:[{path:b.path}]}}]);
    await assert.rejects(assessment.update({user:alice,body:{attachments:{new:[{path:b.path}]}}},response),{status:403});
    await assessment.update({user:alice,body:{attachments:{existing:[{path:b.path}],new:[{path:a.path}]}}},response);
    const frameworks=require('../src/controllers/frameworkController');
    await client.query("INSERT INTO controls(framework_id,code,evidence) VALUES('iso27001','4.1','[]')");
    await assert.rejects(frameworks.updateControlEvidence({user:alice,params:{frameworkId:'iso27001',code:'4.1'},body:{evidence:[{path:b.path}]}},response),{status:403});
    const permission=require('../src/services/permissionService');let deniedAction=null;t.mock.method(permission,'has',async(role,_page,action)=>role==='admin' || action!==deniedAction);t.mock.method(permission,'hasFileAction',async(role,action)=>role==='admin' || action!==deniedAction);
    const express=require('express');const app=express();app.use(express.json());
    app.use((req,res,next)=>{req.user=req.get('x-test-user')==='admin'?admin:alice;next();});
    app.use('/files',require('../src/routes/fileRoutes'));
    app.use((error,req,res,next)=>res.status(error.status||500).json({error:error.message}));
    server=await new Promise(resolve=>{const s=app.listen(0,'127.0.0.1',()=>resolve(s));});const base='http://127.0.0.1:'+server.address().port;
    assert.equal((await fetch(base+'/files/'+access.normalize(b.path))).status,403,'GET rejects another uploader file');
    assert.equal((await fetch(base+'/files/open/'+access.normalize(b.path),{redirect:'manual'})).status,403,'open rejects another uploader file');
    assert.equal((await fetch(base+'/files/open-page/'+access.normalize(b.path))).status,403,'PDF settings reject another uploader file');
    assert.equal((await (await fetch(base+'/files/access/'+access.normalize(b.path))).json()).canModify,false,'another user cannot modify the evidence');
    for(const method of ['PUT','DELETE'])assert.equal((await fetch(base+'/files/'+access.normalize(b.path),{method})).status,403,method+' blocks other owner');
    assert.equal((await fetch(base+'/files/open-page/'+access.normalize(b.path), {method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({openPage:2})})).status,403,'users cannot change another uploader PDF settings');
    assert.equal((await fetch(base+'/files/open-page/'+access.normalize(a.path), {method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({openPage:2})})).status,200,'users can change their own PDF settings');
    assert.equal((await fetch(base+'/files/'+access.normalize(b.path)+'?library=true',{method:'DELETE'})).status,403,'library delete cannot bypass ownership');
    const replacement=new FormData();replacement.set('file',new Blob(['%PDF Replacement'],{type:'application/pdf'}),'same.pdf');assert.equal((await fetch(base+'/files/'+access.normalize(a.path),{method:'PUT',body:replacement})).status,200,'a regular user can replace their own file with Files Edit permission');
    assert.equal((await isolated.read(access.normalize(a.path))).toString(),'%PDF Replacement');
    await isolated.put('Custom/Policy/own.pdf',{buffer:Buffer.from('%PDF Own'),name:'own.pdf',mimeType:'application/pdf',uploadedBy:1});
    const customReplacement=new FormData();customReplacement.set('file',new Blob(['%PDF Custom'],{type:'application/pdf'}),'own.pdf');
    assert.equal((await fetch(base+'/files/Custom/Policy/own.pdf',{method:'PUT',body:customReplacement})).status,200,'ownership grants replacement regardless of upload folder');
    assert.equal((await fetch(base+'/files/Custom/Policy/own.pdf?library=true',{method:'DELETE'})).status,204,'owners can delete unused uploads regardless of folder');
    await assert.rejects(access.assertAccess('Custom/Policy/own.pdf',alice),{status:403});
    await isolated.put('audit-finding/fixture/proof.txt',{buffer:Buffer.from('old'),name:'proof.txt',mimeType:'application/octet-stream',uploadedBy:1});
    const auditReplacement=new FormData();auditReplacement.set('file',new Blob(['new audit evidence'],{type:'text/plain'}),'proof.txt');
    assert.equal((await fetch(base+'/files/audit-finding/fixture/proof.txt',{method:'PUT',body:auditReplacement})).status,200,'audit file types can be replaced through own Uploaded Files');
    assert.equal((await isolated.read('audit-finding/fixture/proof.txt')).toString(),'new audit evidence');
    assert.equal((await fetch(base+'/files/audit-finding/fixture/proof.txt?library=true',{method:'DELETE'})).status,204);
    assert.equal((await fetch(base+'/files/'+access.normalize(b.path),{headers:{'x-test-user':'admin'}})).status,200);
    assert.equal((await (await fetch(base+'/files/access/'+access.normalize(b.path),{headers:{'x-test-user':'admin'}})).json()).canModify,true,'admin can modify all evidence');
    assert.equal((await fetch(base+'/files?details=true')).status,200);
    for(const [action,method] of [['read','GET'],['update','PUT'],['delete','DELETE']]) { deniedAction=action; assert.equal((await fetch(base+'/files/'+access.normalize(a.path),{method})).status,403,'ownership cannot bypass '+action); }
    deniedAction=null;
    assert.equal((await fetch(base+'/files/'+access.normalize(a.path)+'?library=true',{method:'DELETE'})).status,204,'original deletion detaches all references');
    await assert.rejects(access.assertAccess(a.path,alice),{status:403});
    const form=new FormData();form.set('functionName','Uploaded files');form.set('kind','policy');form.set('uploadedBy','2');form.set('file',new Blob(['%PDF New'],{type:'application/pdf'}),'new.pdf');
    const uploaded=await fetch(base+'/files',{method:'POST',body:form});assert.equal(uploaded.status,201);
    const item=await uploaded.json();assert.ok(item.path.startsWith('upload/Uploaded files/Policy/'));assert.ok((await access.list(alice)).some(file=>file.path===item.path),'standalone uploads appear in the reference library before attachment');assert.equal(String((await client.query('SELECT uploaded_by FROM evidence_files WHERE path=$1',[access.normalize(item.path)])).rows[0].uploaded_by),'1','body cannot spoof uploader');assert.equal((await fetch(base+'/files/'+access.normalize(item.path),{method:'DELETE'})).status,204,'a regular user can delete their own file with Files Delete permission');
  } finally {
    if(server)await new Promise(resolve=>server.close(resolve));
    await client.query('DROP TABLE IF EXISTS pg_temp.role_permissions, pg_temp.audit_finding_records, pg_temp.tprm_due_diligence_questionnaires, pg_temp.policy_register_items, pg_temp.policy_register, pg_temp.controls, pg_temp.assessment_state, pg_temp.file_storage_locations, pg_temp.file_storage_settings, pg_temp.evidence_files, pg_temp.app_users');
    client.release();await pool.end();
    // Directory is created above by mkdtemp, always below the OS temporary root.
    assert.equal(path.dirname(path.resolve(directory)),path.resolve(os.tmpdir()));
    assert.ok(path.basename(directory).startsWith('evidence-owner-'));
    await fs.rm(directory,{recursive:true,force:true,maxRetries:10,retryDelay:200});
  }
});
