function attachmentRecords() {
  const csfRecords = Object.entries(state.attachments || {}).flatMap(([key, attachments]) => {
    const separator = key.indexOf('-'); const kind = key.slice(0, separator); const controlId = key.slice(separator + 1); const item = allControls().find(control => control.id === controlId);
    if (!item || !Array.isArray(attachments)) return [];
    return attachments.map((attachment, index) => ({ ...attachment, key, index, kind, item, sourceType: 'csf' }));
  });
  const privacyRecords = Object.entries(privacyState.attachments || {}).flatMap(([key, attachments]) => {
    if (!key.startsWith('privacy-') || !Array.isArray(attachments)) return [];
    const parts = key.split('-'); const kind = parts[1]; const controlId = parts.slice(2).join('-'); const source = privacyRows.find(row => row.id === controlId); if (!source) return [];
    const item = { ...source, name: source.subcategory.split(':').slice(1).join(':').trim(), fn: { id: source.function.match(/\(([A-Z]+-P)\)/)?.[1] || source.function, name: source.function.split(' (', 1)[0] } };
    return attachments.map((attachment, index) => ({ ...attachment, key, index, kind, item, sourceType: 'privacy' }));
  });
  const isoRecords = [
    ...iso27001Rows.flatMap(item => (Array.isArray(item.evidence) ? item.evidence : []).map((attachment, index) => ({ ...attachment, key: `iso|iso27001|${item.id}`, index, kind: 'policy', sourceType: 'iso27001', item: { ...item, frameworkLabel: 'ISO 27001:2022', name: item.subcategory, fn: { id: item.id, name: item.function } } }))),
    ...iso27001SoaRows.flatMap(item => (Array.isArray(item.evidence) ? item.evidence : []).map((attachment, index) => ({ ...attachment, key: `iso|iso27001-soa|${item.id}`, index, kind: 'policy', sourceType: 'iso27001-soa', item: { ...item, frameworkLabel: 'SOA (Statement of Applicability)', name: item.subcategory, fn: { id: item.id, name: item.function } } }))),
  ];
  const policyRecords = policyRegisterFiles().map(file => ({ ...file, key: 'policy-register', index: file.sourceIndex, kind: 'policy', sourceType: 'policy-register', item: { name: file.name, category: 'Policy Register', subcategory: file.name, frameworkLabel: 'Policy Register', fn: { id: 'POLICY', name: 'Policy Register' } } }));
  return [...csfRecords, ...privacyRecords, ...isoRecords, ...policyRecords].sort((a, b) => (a.name || '').localeCompare(b.name || ''));
}
const canEditUploadedFile = record => record.sourceType === 'policy-register'
  ? canManagePolicyRegister('update')
  : currentUserRole === 'admin' || (currentUserRole === 'editor' && currentUserPermissions.includes('files'));
function renderUploadedFiles() {
  const query = $('uploadedFileSearch').value.toLowerCase(); const kindFilter = $('uploadedFileKindFilter').value;
  const allRecords = attachmentRecords();
  const records = allRecords.filter(record => { const item = record.item; const text = `${record.name} ${record.path} ${item.fn.name} ${item.category} ${item.subcategory}`.toLowerCase(); return (kindFilter === 'all' || record.kind === kindFilter) && text.includes(query); });
  uploadedFileRecordMap = new Map(allRecords.map((record, index) => [`uploaded-${index}`, record]));
  const recordIds = new Map([...uploadedFileRecordMap].map(([id, record]) => [record, id]));
  const total = allRecords.length; $('uploadedFileCount').textContent = `${total} file${total === 1 ? '' : 's'}`;
  uploadedFilesPage = renderListPagination('uploadedFilesPagination', uploadedFilesPage, records.length, 'files'); const visibleRecords = records.slice((uploadedFilesPage - 1) * 20, uploadedFilesPage * 20);
  $('uploadedFilesBody').innerHTML = visibleRecords.map(record => `<tr><td><strong class="uploaded-file-name" title="${escapeHtml(record.path)}">${escapeHtml(record.name)}</strong><small>${escapeHtml(record.path)}</small></td><td><span class="framework-badge">${escapeHtml(record.item.frameworkLabel || (record.key.startsWith('privacy-') ? 'Privacy Framework' : 'CSF 2.0'))}</span></td><td><span class="function-badge">${escapeHtml(record.item.fn.id)}</span>${escapeHtml(record.item.fn.name)}</td><td>${escapeHtml(categoryLabel(record.item.category || 'CSF Core'))}</td><td>${escapeHtml(record.item.name)}</td><td><span class="file-kind ${record.kind}">${record.kind === 'policy' ? 'Policy' : 'Practice'}</span></td><td>${record.updatedAt ? new Date(record.updatedAt).toLocaleDateString('id-ID') : '-'}</td><td><div class="file-actions"><button class="attachment-action-button" type="button" data-open-attachment="${record.key}" data-attachment-index="${record.index}">Open</button><button class="attachment-action-button" type="button" data-download-attachment="${record.key}" data-attachment-index="${record.index}">Download</button>${canEditUploadedFile(record) ? `<button class="attachment-action-button" type="button" data-uploaded-file-edit="${recordIds.get(record)}">Edit</button>` : ''}<button class="attachment-action-button danger" type="button" data-delete-attachment="${record.key}" data-attachment-index="${record.index}"${record.sourceType === 'policy-register' ? ` data-policy-id="${escapeHtml(record.policyId)}"` : ''}>Delete</button></div></td></tr>`).join('') || '<tr><td colspan="8" class="empty-files">Belum ada file yang diupload.</td></tr>';
  document.querySelectorAll('#uploadedFilesBody [data-delete-attachment]').forEach(button => button.addEventListener('click', () => deleteAttachment(button.dataset.deleteAttachment, Number(button.dataset.attachmentIndex))));
  document.querySelectorAll('#uploadedFilesBody [data-open-attachment]').forEach(button => button.addEventListener('click', () => openAttachment(button.dataset.openAttachment, Number(button.dataset.attachmentIndex))));
  document.querySelectorAll('#uploadedFilesBody [data-download-attachment]').forEach(button => button.addEventListener('click', () => downloadAttachment(button.dataset.downloadAttachment, Number(button.dataset.attachmentIndex))));
}
async function useExistingAttachment(targetKey, sourceKey, sourceIndex) {
  const sourceAttachment = sourceKey === 'policy-register' ? policyRegisterFiles().find(file => file.sourceIndex === sourceIndex) : (attachmentStateFor(sourceKey).attachments[sourceKey] || [])[sourceIndex]; if (!sourceAttachment) return;
  try {
    const targetId = targetKey.slice(targetKey.indexOf('-') + 1); const targetItem = allControls().find(control => control.id === targetId); if (!targetItem) return;
    const targetAttachments = state.attachments[targetKey] || []; const existing = targetAttachments.findIndex(attachment => attachment.path === sourceAttachment.path); if (existing < 0) targetAttachments.push(sourceAttachment); state.attachments[targetKey] = targetAttachments; save(); renderCsfTable(); renderUploadedFiles(); if ($('assessmentView').classList.contains('active-view')) renderControls();
  } catch (error) { $('saveState').textContent = 'File gagal digunakan'; }
}
async function ensureUploadStructure() { for (const fn of functions) { const functionDirectory = await uploadDirectoryHandle.getDirectoryHandle(fn.name, { create: true }); await functionDirectory.getDirectoryHandle('Policy', { create: true }); await functionDirectory.getDirectoryHandle('Practice', { create: true }); } }
const updateUploadProgress = (key, percent, message, status = '') => { uploadStatuses.set(key, { percent, message, status }); document.querySelectorAll(`[data-progress-key="${key}"]`).forEach(progress => { progress.className = `upload-progress ${status}`; progress.querySelector('.upload-progress-track i').style.width = `${percent}%`; progress.querySelector('small').textContent = message; }); };
async function uploadAttachment(input) {
  const files = [...input.files]; if (!files.length) return;
  const key = input.dataset.attachment; const functionName = input.dataset.function; const kind = input.dataset.kind; const owner = attachmentStateFor(key); const isPrivacy = input.dataset.scope === 'privacy';
  if (isPrivacy) await privacyDataReady;
  try {
    updateUploadProgress(key, 2, `Uploading ${files.length} file${files.length === 1 ? '' : 's'}...`); const attachments = owner.attachments[key] || []; owner.attachments[key] = attachments; const metadataList = await saveFilesToServer(functionName, kind, files); metadataList.forEach(metadata => { const existing = attachments.findIndex(attachment => attachment.name === metadata.name); if (existing >= 0) attachments[existing] = metadata; else attachments.push(metadata); });
    isPrivacy ? savePrivacy() : save(); updateUploadProgress(key, 100, `${files.length} file${files.length === 1 ? '' : 's'} uploaded`, 'success'); renderCsfTable(); renderUploadedFiles(); if ($('assessmentView').classList.contains('active-view')) renderControls(); if ($('privacyView').classList.contains('active-view')) renderPrivacy();
  } catch (error) { isPrivacy ? savePrivacy() : save(); const duplicate = error.message.includes('already exists'); updateUploadProgress(key, 100, duplicate ? 'File name already exists' : 'Upload failed', 'fail'); $('saveState').textContent = duplicate ? 'Nama file sudah ada' : 'Upload gagal'; renderCsfTable(); renderUploadedFiles(); if ($('assessmentView').classList.contains('active-view')) renderControls(); if ($('privacyView').classList.contains('active-view')) renderPrivacy(); }
  input.value = '';
}
async function replaceAttachment(input) { const key = input.dataset.replaceAttachment; const index = Number(input.dataset.attachmentIndex); const owner = attachmentStateFor(key); const oldAttachment = (owner.attachments[key] || [])[index]; await uploadAttachment({ files: input.files, dataset: { attachment: key, function: input.dataset.function, kind: input.dataset.kind, scope: input.dataset.scope } }); const attachments = owner.attachments[key] || []; const replacementIndex = attachments.findIndex(attachment => attachment.name === input.files[0]?.name); if (replacementIndex >= 0 && replacementIndex !== index) { attachments.splice(index, 1); const moved = attachments.splice(replacementIndex > index ? replacementIndex - 1 : replacementIndex, 1)[0]; attachments.splice(index, 0, moved); owner.attachments[key] = attachments; key.startsWith('privacy-') ? savePrivacy() : save(); renderCsfTable(); renderUploadedFiles(); if ($('privacyView').classList.contains('active-view')) renderPrivacy(); } if (oldAttachment && oldAttachment.name !== input.files[0]?.name) attachmentHandles.delete(`${key}-${oldAttachment.name}`); }
const apiFileUrl = filePath => `/api/files/${filePath.replace(/^upload\//, '').split('/').map(encodeURIComponent).join('/')}`;
async function saveFilesToServer(functionName, kind, files) { const formData = new FormData(); formData.append('functionName', functionName); formData.append('kind', kind); formData.append('rejectDuplicate', 'true'); files.forEach(file => formData.append('files', file, file.name)); const response = await fetch('/api/files/batch', { method: 'POST', body: formData }); if (!response.ok) { const error = await response.json().catch(() => ({})); throw new Error(error.error || 'Upload failed'); } return response.json(); }
function isoRecordContext(key) { const [, framework, ...idParts] = String(key).split('|'); const id = idParts.length ? idParts.join('|') : framework; const isSoa = idParts.length ? framework === 'iso27001-soa' : iso27001SoaRows.some(row => row.id === id); const rows = isSoa ? iso27001SoaRows : iso27001Rows; return { id, isSoa, rows, row: rows.find(item => item.id === id) }; }
function isoAttachmentFor(key, index) { return isoRecordContext(key).row?.evidence?.[index]; }
async function openAttachment(key, index) { const attachment = key === 'policy-register' ? policyRegisterFiles().find(file => file.sourceIndex === index) : key.startsWith('iso|') ? isoAttachmentFor(key, index) : (attachmentStateFor(key).attachments[key] || [])[index]; if (attachment) window.open(apiFileUrl(attachment.path), '_blank', 'noopener'); }
async function downloadAttachment(key, index) { const attachment = key === 'policy-register' ? policyRegisterFiles().find(file => file.sourceIndex === index) : key.startsWith('iso|') ? isoAttachmentFor(key, index) : (attachmentStateFor(key).attachments[key] || [])[index]; if (attachment) { const link = document.createElement('a'); link.href = apiFileUrl(attachment.path); link.download = attachment.name; link.click(); } }
async function deleteAttachment(key, index) { if (key === 'policy-register') { const policyId = document.querySelector(`#uploadedFilesBody [data-delete-attachment="policy-register"][data-attachment-index="${index}"]`)?.dataset.policyId; const row = policyRegisterRows.find(item => String(item.id) === String(policyId)) || policyRegisterRows[index]; if (!row || !confirm(`Hapus policy ${row.title || row.attachmentName}?`)) return; const response = await fetch(`/api/policy-register/${encodeURIComponent(row.id)}`, { method: 'DELETE' }); if (response.ok) await loadPolicyRegisterRows(); else $('saveState').textContent = 'Policy Register gagal dihapus'; return; } if (key.startsWith('iso|')) { const { id, isSoa, row } = isoRecordContext(key); if (!row) return; const attachments = [...(row.evidence || [])]; const attachment = attachments[index]; if (!attachment || !confirm(`Hapus lampiran ${attachment.name}?`)) return; attachments.splice(index, 1); if ((await updateIsoEvidence(isSoa ? 'soa' : 'clauses', id, attachments)).ok) { row.evidence = attachments; renderUploadedFiles(); isSoa ? renderIso27001SoaManager() : renderIso27001Manager(); } return; } const owner = attachmentStateFor(key); const attachments = owner.attachments[key] || []; const attachment = attachments[index]; if (!attachment || !confirm(`Hapus lampiran ${attachment.name}?`)) return; await fetch(apiFileUrl(attachment.path), { method: 'DELETE' }); attachments.splice(index, 1); owner.attachments[key] = attachments; key.startsWith('privacy-') ? savePrivacy() : save(); renderCsfTable(); renderUploadedFiles(); if ($('privacyView').classList.contains('active-view')) renderPrivacy(); }
