const express = require('express');
const controller = require('../controllers/personnelCertificationController');
const { requirePermission, requirePageAccess } = require('../middleware/permission');
const router = express.Router();
router.get('/', requirePermission('personnel-certification', 'read'), controller.list);
router.post('/', requirePageAccess('personnel-certification', 'create'), controller.create);
router.put('/:id/layout', requirePageAccess('personnel-certification', 'update'), controller.updateLayout);
router.put('/:id', requirePageAccess('personnel-certification', 'update'), controller.update);
router.delete('/:id', requirePageAccess('personnel-certification', 'delete'), controller.remove);
module.exports = router;
