const express = require('express');
const controller = require('../controllers/riskManagementController');
const { requirePermission, requirePageAccess } = require('../middleware/permission');
const router = express.Router();
router.get('/dashboard', requirePermission('risk-management', 'read'), controller.dashboard);
router.get('/indicators', requirePermission('risk-management', 'read'), controller.indicators);
router.get('/dropdowns', requirePermission('risk-management', 'read'), controller.dropdowns);
router.post('/dropdowns', requirePageAccess('risk-management', 'create'), controller.createDropdown);
router.put('/dropdowns/:id', requirePageAccess('risk-management', 'update'), controller.updateDropdown);
router.delete('/dropdowns/:id', requirePageAccess('risk-management', 'delete'), controller.removeDropdown);
router.post('/indicators', requirePageAccess('risk-management', 'create'), controller.createIndicator);
router.put('/indicators/:id', requirePageAccess('risk-management', 'update'), controller.updateIndicator);
router.delete('/indicators/:id', requirePageAccess('risk-management', 'delete'), controller.removeIndicator);
router.get('/', requirePermission('risk-management', 'read'), controller.list);
router.post('/', requirePageAccess('risk-management', 'create'), controller.create);
router.put('/:id', requirePageAccess('risk-management', 'update'), controller.update);
router.delete('/:id', requirePageAccess('risk-management', 'delete'), controller.remove);
router.delete('/', requirePageAccess('risk-management', 'delete'), controller.reset);
module.exports = router;