const express = require('express');
const controller = require('../controllers/riskManagementController');
const { requireAdmin } = require('../middleware/authorization');
const { requirePermission } = require('../middleware/permission');
const router = express.Router();
router.get('/dashboard', requirePermission('risk-management'), controller.dashboard);
router.get('/indicators', requirePermission('risk-management'), controller.indicators);
router.get('/dropdowns', requirePermission('risk-management'), controller.dropdowns);
router.post('/dropdowns', requireAdmin, controller.createDropdown);
router.put('/dropdowns/:id', requireAdmin, controller.updateDropdown);
router.delete('/dropdowns/:id', requireAdmin, controller.removeDropdown);
router.post('/indicators', requireAdmin, controller.createIndicator);
router.put('/indicators/:id', requireAdmin, controller.updateIndicator);
router.delete('/indicators/:id', requireAdmin, controller.removeIndicator);
router.get('/', requirePermission('risk-management'), controller.list);
router.post('/', requireAdmin, controller.create);
router.put('/:id', requireAdmin, controller.update);
router.delete('/:id', requireAdmin, controller.remove);
router.delete('/', requireAdmin, controller.reset);
module.exports = router;