const {pool}=require('../config/database');
const {randomUUID}=require('node:crypto');
const invalid=(message,status=400)=>Object.assign(new Error(message),{status});
let ready;
function ensureStore(){return ready ||= pool.query(`CREATE TABLE IF NOT EXISTS asset_diagram_layout (id INTEGER PRIMARY KEY CHECK(id=1), nodes JSONB NOT NULL, version INTEGER NOT NULL DEFAULT 1); CREATE TABLE IF NOT EXISTS asset_diagram_canvases(id UUID PRIMARY KEY, name TEXT NOT NULL UNIQUE, nodes JSONB NOT NULL DEFAULT '[]'::jsonb, version INTEGER NOT NULL DEFAULT 0, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`).catch(e=>{ready=null;throw e;});}
function validate(data){if(!data||!Array.isArray(data.nodes)||data.nodes.length>500||!Number.isSafeInteger(data.version)||data.version<0)throw invalid('Diagram tidak valid.');const ids=new Set();return data.nodes.map(n=>{if(!n||typeof n.id!=='string'||! /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(n.id)||ids.has(n.id)||![n.x,n.y].every(v=>Number.isFinite(v)&&v>=0&&v<=20000))throw invalid('Aset atau posisi diagram tidak valid.');ids.add(n.id);return {id:n.id,x:n.x,y:n.y};});}
async function read(){await ensureStore();const row=(await pool.query('SELECT nodes,version FROM asset_diagram_layout WHERE id=1')).rows[0];return row||{nodes:[],version:0};}
async function save(data){const nodes=validate(data);await ensureStore();const c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(872148)');const old=(await c.query('SELECT version FROM asset_diagram_layout WHERE id=1 FOR UPDATE')).rows[0];if((old?.version||0)!==data.version)throw invalid('Diagram telah diubah pengguna lain. Muat ulang sebelum menyimpan.',409);if(nodes.length){const found=(await c.query('SELECT id FROM managed_assets WHERE id=ANY($1::uuid[])',[nodes.map(n=>n.id)])).rows;if(found.length!==nodes.length)throw invalid('Aset diagram tidak ditemukan. Muat ulang katalog.',409);}const version=data.version+1;await c.query('INSERT INTO asset_diagram_layout(id,nodes,version) VALUES(1,$1,$2) ON CONFLICT(id) DO UPDATE SET nodes=EXCLUDED.nodes,version=EXCLUDED.version',[JSON.stringify(nodes),version]);await c.query('COMMIT');return {nodes,version};}catch(e){await c.query('ROLLBACK');throw e;}finally{c.release();}}
function validateName(data){if(typeof data?.name!=='string'||!data.name.trim()||data.name.trim().length>150)throw invalid('Nama kanvas wajib diisi, maksimal 150 karakter.');if(data.name.trim().toLowerCase()==='kanvas utama')throw invalid('Nama kanvas sudah digunakan.',409);return data.name.trim();}
async function listCanvases(){await ensureStore();return [{id:'main',name:'Kanvas utama'},...(await pool.query('SELECT id,name,version FROM asset_diagram_canvases ORDER BY created_at DESC,id')).rows];}
async function canvasTransaction(action){await ensureStore();const c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(872148)');const result=await action(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');if(e.code==='23505')throw invalid('Nama kanvas sudah digunakan.',409);throw e;}finally{c.release();}}
async function createCanvas(data){const name=validateName(data);return canvasTransaction(async c=>{const id=randomUUID();return (await c.query('INSERT INTO asset_diagram_canvases(id,name) VALUES($1,$2) RETURNING id,name,nodes,version',[id,name])).rows[0];});}
async function readCanvas(id){await ensureStore();const row=(await pool.query('SELECT id,name,nodes,version FROM asset_diagram_canvases WHERE id=$1',[id])).rows[0];if(!row)throw invalid('Kanvas tidak ditemukan.',404);return row;}
async function renameCanvas(id,data){const name=validateName(data);if(!Number.isSafeInteger(data.version)||data.version<0)throw invalid('Versi kanvas tidak valid.');return canvasTransaction(async c=>{const row=(await c.query('SELECT version FROM asset_diagram_canvases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)throw invalid('Kanvas tidak ditemukan.',404);if(row.version!==data.version)throw invalid('Kanvas telah diubah. Muat ulang sebelum menyimpan.',409);return (await c.query('UPDATE asset_diagram_canvases SET name=$2,version=version+1 WHERE id=$1 RETURNING id,name,nodes,version',[id,name])).rows[0];});}
async function saveCanvas(id,data){const nodes=validate(data);return canvasTransaction(async c=>{const row=(await c.query('SELECT version FROM asset_diagram_canvases WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!row)throw invalid('Kanvas tidak ditemukan.',404);if(row.version!==data.version)throw invalid('Kanvas telah diubah. Muat ulang sebelum menyimpan.',409);if(nodes.length&&(await c.query('SELECT id FROM managed_assets WHERE id=ANY($1::uuid[])',[nodes.map(n=>n.id)])).rows.length!==nodes.length)throw invalid('Aset diagram tidak ditemukan.',409);return (await c.query('UPDATE asset_diagram_canvases SET nodes=$2,version=version+1 WHERE id=$1 RETURNING id,name,nodes,version',[id,JSON.stringify(nodes)])).rows[0];});}
module.exports={ensureStore,validate,read,save,validateName,listCanvases,createCanvas,readCanvas,renameCanvas,saveCanvas};
