const { pool } = require('../config/database');
const smtp = require('./smtpService');
const { randomUUID } = require('crypto');
const fail = (message,status=400) => Object.assign(new Error(message),{status});
const statuses=['planned','in-stock','in-use','maintenance','retired','disposed'];
const types=['Server','Firewall','WAF','Load Balancer','Switch','Router','Storage','Software','License','Cloud','Other'];
const relationships=['connects-to','depends-on','protects','balances','hosts','backs-up'];
let ready;
function ensureStore(){return ready ||= require('./tprmService').ensureStore().then(()=>pool.query(`
CREATE TABLE IF NOT EXISTS managed_assets(id UUID PRIMARY KEY, tag TEXT UNIQUE NOT NULL, data JSONB NOT NULL, updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE managed_assets ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;
UPDATE managed_assets SET created_at=updated_at WHERE created_at IS NULL;
ALTER TABLE managed_assets ALTER COLUMN created_at SET DEFAULT NOW(), ALTER COLUMN created_at SET NOT NULL;
ALTER TABLE managed_assets ADD COLUMN IF NOT EXISTS managed_vendor_id BIGINT GENERATED ALWAYS AS (NULLIF(data->>'managedVendorId','')::bigint) STORED REFERENCES tprm_risk_register(id) ON DELETE RESTRICT;
CREATE INDEX IF NOT EXISTS managed_assets_vendor_idx ON managed_assets(managed_vendor_id);
CREATE TABLE IF NOT EXISTS asset_racks(id UUID PRIMARY KEY, name TEXT UNIQUE NOT NULL, location TEXT NOT NULL, units INTEGER NOT NULL CHECK(units BETWEEN 1 AND 60));
CREATE TABLE IF NOT EXISTS asset_rack_devices(asset_id UUID PRIMARY KEY REFERENCES managed_assets(id) ON DELETE RESTRICT, rack_id UUID NOT NULL REFERENCES asset_racks(id) ON DELETE RESTRICT, start_unit INTEGER NOT NULL, height INTEGER NOT NULL);
ALTER TABLE asset_rack_devices ADD COLUMN IF NOT EXISTS facing TEXT NOT NULL DEFAULT 'front' CHECK(facing IN ('front','rear'));
ALTER TABLE asset_rack_devices ADD COLUMN IF NOT EXISTS full_depth BOOLEAN NOT NULL DEFAULT TRUE;
CREATE TABLE IF NOT EXISTS asset_relations(id UUID PRIMARY KEY, source_id UUID NOT NULL REFERENCES managed_assets(id) ON DELETE RESTRICT, target_id UUID NOT NULL REFERENCES managed_assets(id) ON DELETE RESTRICT, type TEXT NOT NULL, notes TEXT NOT NULL DEFAULT '', change_reference TEXT NOT NULL, CHECK(source_id <> target_id), UNIQUE(source_id,target_id,type));
CREATE TABLE IF NOT EXISTS asset_related_risks(asset_id UUID NOT NULL REFERENCES managed_assets(id) ON DELETE CASCADE, risk_id TEXT NOT NULL REFERENCES risk_register(risk_id) ON DELETE CASCADE, PRIMARY KEY(asset_id,risk_id));
CREATE TABLE IF NOT EXISTS asset_renewal_deliveries(asset_id UUID REFERENCES managed_assets(id) ON DELETE CASCADE, renewal_date DATE NOT NULL, recipient TEXT NOT NULL, sent_on DATE NOT NULL, PRIMARY KEY(asset_id,renewal_date,recipient,sent_on));
`)).catch(e=>{ready=null;throw e;});}
function text(value,name,max=250,required=false){if(typeof value!=='string'||value.length>max||(required&&!value.trim()))throw fail(name+' tidak valid.');return value.trim();}
function date(value,name){if(!value)return '';if(typeof value!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(value)||(!Number.isFinite(Date.parse(value+'T00:00:00Z'))||new Date(value+'T00:00:00Z').toISOString().slice(0,10)!==value))throw fail(name+' tidak valid.');return value;}
function validateAsset(d){if(!d||typeof d!=='object')throw fail('Aset tidak valid.');const result={};if(d.managedVendorId!==undefined){if(d.managedVendorId!==null&&d.managedVendorId!==''&&(typeof d.managedVendorId!=='string'||! /^[1-9][0-9]{0,17}$/.test(d.managedVendorId)))throw fail('Vendor pengelola TPRM tidak valid.');result.managedVendorId=d.managedVendorId||null;}if(d.assetAssessment!==undefined&&d.assetAssessment!==null)result.assetAssessment=require('./assetRiskAssessmentService').assess(d.assetAssessment);for(const key of ['tag','name','owner'])result[key]=text(d[key],key,150,true);for(const key of ['serial','vendor','model','location','service','changeReference','description'])result[key]=text(d[key]??'',key,key==='description'?2000:250);if(!types.includes(d.type)||!statuses.includes(d.status)||!['low','medium','high','critical'].includes(d.criticality))throw fail('Jenis, status, atau kritikalitas tidak valid.');Object.assign(result,{type:d.type,status:d.status,criticality:d.criticality});for(const key of ['purchaseDate','renewalDate','warrantyDate'])result[key]=date(d[key],key);if(result.purchaseDate&&result.renewalDate&&result.renewalDate<result.purchaseDate)throw fail('Renewal harus setelah pembelian.');if(typeof d.reminderEnabled!=='boolean'||!Number.isInteger(d.reminderDays)||d.reminderDays<0||d.reminderDays>365)throw fail('Reminder harus 0–365 hari.');result.reminderEnabled=d.reminderEnabled;result.reminderDays=d.reminderDays;result.ownerEmail=text(d.ownerEmail??'','Email',254);if(result.ownerEmail&&!smtp.email(result.ownerEmail))throw fail('Email tidak valid.');if(result.reminderEnabled&&(!result.renewalDate||!smtp.email(result.ownerEmail)))throw fail('Reminder membutuhkan tanggal renewal dan email pemilik.');return result;}
function validatePlacement(d,units,existing){if(d.facing!==undefined&&!['front','rear'].includes(d.facing)||d.fullDepth!==undefined&&typeof d.fullDepth!=='boolean')throw fail('Orientasi/depth perangkat tidak valid.');if(!Number.isInteger(d.startUnit)||!Number.isInteger(d.height)||d.startUnit<1||d.height<1||d.startUnit+d.height-1>units)throw fail('Posisi perangkat melebihi kapasitas rak.');if(existing.some(x=>x.asset_id!==d.assetId&&(d.fullDepth!==false||x.full_depth!==false||(d.facing||'front')===(x.facing||'front'))&&d.startUnit<x.start_unit+x.height&&x.start_unit<d.startUnit+d.height))throw fail('Posisi U bertabrakan dengan perangkat lain.',409);}
async function transaction(fn){await ensureStore();const c=await pool.connect();try{await c.query('BEGIN');await c.query("SELECT pg_advisory_xact_lock(872146)");const result=await fn(c);await c.query('COMMIT');return result;}catch(e){await c.query('ROLLBACK');if(e.code==='23505')throw fail('Data sudah terdaftar.',409);if(['23503','23001'].includes(e.code))throw fail('Aset/rak masih digunakan atau referensi tidak ditemukan.',409);throw e;}finally{c.release();}}
async function list(kind){await ensureStore();const sql={assets:`SELECT a.id, a.data, a.created_at, a.updated_at, r.name AS rack_name, (SELECT third_party FROM tprm_risk_register WHERE id::text=a.data->>'managedVendorId') AS managed_vendor_name, ARRAY(SELECT risk_id FROM asset_related_risks WHERE asset_id=a.id ORDER BY risk_id) AS risk_register_ids FROM managed_assets a LEFT JOIN asset_rack_devices d ON d.asset_id=a.id LEFT JOIN asset_racks r ON r.id=d.rack_id ORDER BY a.created_at DESC, a.id DESC`,racks:'SELECT * FROM asset_racks ORDER BY name',placements:'SELECT * FROM asset_rack_devices ORDER BY start_unit',relations:'SELECT * FROM asset_relations ORDER BY type'}[kind];return (await pool.query(sql)).rows.map(r=>kind==='assets'?{id:r.id,...r.data,...(r.data.assetAssessment?{assetAssessment:require('./assetRiskAssessmentService').assess(r.data.assetAssessment)}:{}),createdAt:r.created_at,updatedAt:r.updated_at,rackName:r.rack_name||'',riskRegisterIds:r.risk_register_ids||[],managedVendorName:r.managed_vendor_name||''}:r);}
async function managedVendorCatalog(){return (await pool.query('SELECT id::text AS id, third_party AS name, service_dependency AS service, relationship_status AS status FROM tprm_risk_register ORDER BY third_party,service_dependency,id')).rows;}
async function validateManagedVendor(c,data){if(data.managedVendorId&&!(await c.query('SELECT id FROM tprm_risk_register WHERE id=$1',[data.managedVendorId])).rows.length)throw fail('Vendor pengelola tidak ditemukan di TPRM. Pilih vendor lain atau kosongkan field.',409);}
async function saveAsset(id,d,photoInput=null){const data=validateAsset(d);const photos=photoInput?require('./assetRackPhotoService'):null;const photoChanges=photos?photos.prepareChanges(photoInput.files,photoInput.body,true):[];if(photos)await photos.ensureStore();const uploadedBy=photoInput?.user?await require('./evidenceAccessService').userId(photoInput.user):null;return transaction(async c=>{if(id){const old=(await c.query('SELECT data FROM managed_assets WHERE id=$1 FOR UPDATE',[id])).rows[0];if(!old)throw fail('Aset tidak ditemukan.',404);if(['retired','disposed'].includes(data.status)&&(await c.query('SELECT 1 FROM asset_rack_devices WHERE asset_id=$1 UNION ALL SELECT 1 FROM asset_relations WHERE source_id=$1 OR target_id=$1',[id])).rowCount)throw fail('Lepaskan perangkat dari rak dan relasi sebelum retirement.',409);if(!Object.hasOwn(d,'managedVendorId'))data.managedVendorId=old.data.managedVendorId||null;await validateManagedVendor(c,data);await c.query('UPDATE managed_assets SET tag=$2,data=$3,updated_at=NOW() WHERE id=$1',[id,data.tag,data]);}else{await validateManagedVendor(c,data);id=randomUUID();await c.query('INSERT INTO managed_assets(id,tag,data) VALUES($1,$2,$3)',[id,data.tag,data]);}if(photos)await photos.applyChanges(c,'assets',id,photoChanges,uploadedBy);return {id,...data};});}
async function saveRack(id,d){const name=text(d.name,'Nama rak',150,true),location=text(d.location,'Lokasi',250,true);if(!Number.isInteger(d.units)||d.units<1||d.units>60)throw fail('Kapasitas rak harus 1–60 U.');return transaction(async c=>{if(id){if((await c.query('SELECT 1 FROM asset_rack_devices WHERE rack_id=$1 AND start_unit+height-1>$2',[id,d.units])).rowCount)throw fail('Kapasitas baru memotong perangkat terpasang.',409);if(!(await c.query('UPDATE asset_racks SET name=$2,location=$3,units=$4 WHERE id=$1 RETURNING id',[id,name,location,d.units])).rowCount)throw fail('Rak tidak ditemukan.',404);}else{id=randomUUID();await c.query('INSERT INTO asset_racks VALUES($1,$2,$3,$4)',[id,name,location,d.units]);}return {id,name,location,units:d.units};});}
async function place(d){text(d.changeReference??'','Referensi perubahan',250);return transaction(async c=>{const rack=(await c.query('SELECT * FROM asset_racks WHERE id=$1',[d.rackId])).rows[0];const asset=(await c.query('SELECT data FROM managed_assets WHERE id=$1',[d.assetId])).rows[0];if(!rack||!asset)throw fail('Rak/aset tidak ditemukan.',404);if(['retired','disposed'].includes(asset.data.status)||['Software','License','Cloud'].includes(asset.data.type))throw fail('Aset ini tidak dapat dipasang di rak.');const current=(await c.query('SELECT d.*,r.name AS rack_name FROM asset_rack_devices d JOIN asset_racks r ON r.id=d.rack_id WHERE d.asset_id=$1',[d.assetId])).rows[0];if(current&&d.previousRackId!==current.rack_id)throw fail('Aset sudah dipakai di rak '+current.rack_name+' (U'+current.start_unit+'-U'+(current.start_unit+current.height-1)+'). Gunakan Ubah posisi atau drag-and-drop untuk memindahkannya.',409);if(!current&&d.previousRackId)throw fail('Posisi aset telah berubah. Muat ulang data rak.',409);validatePlacement(d,rack.units,(await c.query('SELECT * FROM asset_rack_devices WHERE rack_id=$1',[d.rackId])).rows);await c.query('INSERT INTO asset_rack_devices(asset_id,rack_id,start_unit,height,facing,full_depth) VALUES($1,$2,$3,$4,$5,$6) ON CONFLICT(asset_id) DO UPDATE SET rack_id=$2,start_unit=$3,height=$4,facing=$5,full_depth=$6',[d.assetId,d.rackId,d.startUnit,d.height,d.facing||'front',d.fullDepth!==false]);return {ok:true};});}
async function relate(d,id=null){if(d.sourceId===d.targetId||!relationships.includes(d.type))throw fail('Relasi tidak valid.');const notes=text(d.notes??'','Catatan',1000),change=text(d.changeReference??'','Referensi perubahan',250);return transaction(async c=>{const assets=(await c.query('SELECT data FROM managed_assets WHERE id=ANY($1::uuid[])',[ [d.sourceId,d.targetId] ])).rows;if(assets.length!==2||assets.some(x=>['retired','disposed'].includes(x.data.status)))throw fail('Pilih dua aset aktif yang terdaftar.');if(id){if(!(await c.query('UPDATE asset_relations SET source_id=$2,target_id=$3,type=$4,notes=$5,change_reference=$6 WHERE id=$1 RETURNING id',[id,d.sourceId,d.targetId,d.type,notes,change])).rowCount)throw fail('Relasi tidak ditemukan.',404);}else{id=randomUUID();await c.query('INSERT INTO asset_relations VALUES($1,$2,$3,$4,$5,$6)',[id,d.sourceId,d.targetId,d.type,notes,change]);}return {id};});}
async function remove(kind,id){const tables={assets:'managed_assets',racks:'asset_racks',placements:'asset_rack_devices',relations:'asset_relations'};return transaction(async c=>{if(kind==='assets'){const r=(await c.query('SELECT data FROM managed_assets WHERE id=$1',[id])).rows[0];if(r&&!['planned','retired','disposed'].includes(r.data.status))throw fail('Retire aset operasional sebelum menghapusnya.');}if(!(await c.query(`DELETE FROM ${tables[kind]} WHERE ${kind==='placements'?'asset_id':'id'}=$1 RETURNING *`,[id])).rowCount)throw fail('Data tidak ditemukan.',404);});}
function validateRiskIds(ids){if(!Array.isArray(ids)||ids.length>500||ids.some(id=>typeof id!=='string'||!id.trim()||id.length>150)||new Set(ids).size!==ids.length)throw fail('Daftar related risk tidak valid.');return ids;}
async function saveRiskLinks(id,ids){validateRiskIds(ids);return transaction(async c=>{if(!(await c.query('SELECT id FROM managed_assets WHERE id=$1 FOR UPDATE',[id])).rows.length)throw fail('Aset tidak ditemukan.',404);if(ids.length&&(await c.query('SELECT risk_id FROM risk_register WHERE risk_id=ANY($1::text[]) FOR SHARE',[ids])).rows.length!==ids.length)throw fail('Risk Register telah berubah atau risiko tidak ditemukan. Muat ulang pilihan risiko.',409);await c.query('DELETE FROM asset_related_risks WHERE asset_id=$1',[id]);if(ids.length)await c.query('INSERT INTO asset_related_risks(asset_id,risk_id) SELECT $1,unnest($2::text[])',[id,ids]);await c.query('UPDATE managed_assets SET updated_at=NOW() WHERE id=$1',[id]);return {riskRegisterIds:ids};});}
function due(asset,today){return asset.reminderEnabled&&asset.renewalDate&&!['retired','disposed'].includes(asset.status)&&Math.floor((Date.parse(asset.renewalDate+'T00:00:00Z')-Date.parse(today+'T00:00:00Z'))/86400000)<=asset.reminderDays;}
let running=false;
async function runReminders(){if(running)return;running=true;let c,mailer;try{await ensureStore();c=await pool.connect();if(!(await c.query('SELECT pg_try_advisory_lock(872147) AS locked')).rows[0].locked)return;const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Bangkok',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());const assets=(await list('assets')).filter(a=>due(a,today));if(!assets.length)return;const reminderSettings=require('./assetReminderSettingsService');const settings=await reminderSettings.read();const transport=await smtp.createMailer(settings.smtpAccountId);mailer=transport.mailer;for(const a of assets){if((await c.query('SELECT 1 FROM asset_renewal_deliveries WHERE asset_id=$1 AND renewal_date=$2 AND recipient=$3 AND sent_on=$4',[a.id,a.renewalDate,a.ownerEmail,today])).rowCount)continue;try{await smtp.send(mailer,{from:transport.from,to:a.ownerEmail,...reminderSettings.renderMessage(settings,a)});await c.query('INSERT INTO asset_renewal_deliveries VALUES($1,$2,$3,$4) ON CONFLICT DO NOTHING',[a.id,a.renewalDate,a.ownerEmail,today]);}catch(e){console.error('[asset-reminder]',a.id,e.message);}}}finally{mailer?.close?.();try{if(c)await c.query('SELECT pg_advisory_unlock(872147)');}finally{c?.release();running=false;}}}
function startScheduler(){const run=()=>runReminders().catch(e=>console.error('[asset-reminder]',e.message));run();const timer=setInterval(run,60*60*1000);timer.unref();return timer;}
module.exports={ensureStore,list,saveAsset,saveRack,place,relate,remove,validateAsset,validatePlacement,due,statuses,types,relationships,managedVendorCatalog,validateRiskIds,saveRiskLinks,runReminders,startScheduler};
