const fs = require('fs').promises;
const path = require('path');
const { pool } = require('../config/database');
const { uploadRoot } = require('../config/paths');

const mimeTypes = { '.html': 'text/html; charset=utf-8', '.js': 'text/javascript; charset=utf-8', '.css': 'text/css; charset=utf-8', '.json': 'application/json; charset=utf-8', '.png': 'image/png', '.jpg': 'image/jpeg', '.jpeg': 'image/jpeg', '.xlsx': 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' };
const safeSegment = value => path.basename(String(value || '')).replace(/[^a-zA-Z0-9._ -]/g, '_');
const normalizePath = relativePath => path.posix.normalize(String(relativePath || '').replaceAll('\\', '/')).replace(/^\.?\//, '');

const diskPath = relativePath => path.resolve(uploadRoot, relativePath);
async function ensureUploadRoot() { await fs.mkdir(uploadRoot, { recursive: true }); }
async function listFiles() { const result = await pool.query('SELECT path FROM evidence_files ORDER BY name'); return result.rows.map(row => `upload/${row.path}`); }
async function saveFile({ functionName, kind, file }) { const safeFunction = safeSegment(functionName); const safeName = safeSegment(file?.originalname); const folder = kind === 'policy' ? 'Policy' : 'Practice'; if (!safeFunction || !safeName || !file?.path) { const error = new Error('Invalid multipart file payload'); error.status = 400; throw error; } const existing = await pool.query('SELECT path, name, octet_length(content) AS size, mime_type, updated_at FROM evidence_files WHERE name = $1 ORDER BY updated_at DESC LIMIT 1', [safeName]); if (existing.rowCount) { await fs.rm(file.path, { force: true }); return { ...existing.rows[0], path: `upload/${existing.rows[0].path}`, size: Number(existing.rows[0].size || file.size), type: existing.rows[0].mime_type, updatedAt: existing.rows[0].updated_at }; } const relativePath = path.posix.join(safeFunction, folder, safeName); await pool.query(`INSERT INTO evidence_files (path, name, content, mime_type, updated_at) VALUES ($1, $2, NULL, $3, NOW()) ON CONFLICT (path) DO UPDATE SET name = EXCLUDED.name, content = NULL, mime_type = EXCLUDED.mime_type, updated_at = NOW()`, [relativePath, safeName, file.mimetype || 'application/octet-stream']); return { name: safeName, path: `upload/${relativePath}`, size: file.size, type: file.mimetype || 'application/octet-stream', updatedAt: new Date().toISOString() }; }
async function saveFile({ functionName, kind, file, rejectDuplicate = false }) { const safeFunction = safeSegment(functionName); const safeName = safeSegment(file?.originalname); const folder = kind === 'policy' ? 'Policy' : 'Practice'; if (!safeFunction || !safeName || !file?.path) { const error = new Error('Invalid multipart file payload'); error.status = 400; throw error; } const existing = await pool.query('SELECT path, name, octet_length(content) AS size, mime_type, updated_at FROM evidence_files WHERE name = $1 ORDER BY updated_at DESC LIMIT 1', [safeName]); if (existing.rowCount) { await fs.rm(file.path, { force: true }); if (rejectDuplicate) { const error = new Error(`File name already exists: ${safeName}`); error.status = 409; throw error; } return { ...existing.rows[0], path: `upload/${existing.rows[0].path}`, size: Number(existing.rows[0].size || file.size), type: existing.rows[0].mime_type, updatedAt: existing.rows[0].updated_at }; } const relativePath = path.posix.join(safeFunction, folder, safeName); const target = diskPath(relativePath); await fs.mkdir(path.dirname(target), { recursive: true }); await fs.rename(file.path, target); await pool.query(`INSERT INTO evidence_files (path, name, content, mime_type, updated_at) VALUES ($1, $2, NULL, $3, NOW()) ON CONFLICT (path) DO UPDATE SET name = EXCLUDED.name, content = NULL, mime_type = EXCLUDED.mime_type, updated_at = NOW()`, [relativePath, safeName, file.mimetype || 'application/octet-stream']); return { name: safeName, path: `upload/${relativePath}`, size: file.size, type: file.mimetype || 'application/octet-stream', updatedAt: new Date().toISOString() }; }
async function saveFiles({ functionName, kind, files, rejectDuplicate = false }) { const names = files.map(file => safeSegment(file.originalname)); const uniqueNames = new Set(names); if (uniqueNames.size !== names.length) { await Promise.all(files.map(file => fs.rm(file.path, { force: true }))); const error = new Error('Duplicate filenames in upload batch'); error.status = 409; throw error; } const existing = await pool.query('SELECT name FROM evidence_files WHERE name = ANY($1)', [names]); if (existing.rowCount && rejectDuplicate) { await Promise.all(files.map(file => fs.rm(file.path, { force: true }))); const error = new Error(`File name already exists: ${existing.rows[0].name}`); error.status = 409; throw error; } try { return await Promise.all(files.map(file => saveFile({ functionName, kind, file, rejectDuplicate }))); } catch (error) { await Promise.all(files.map(file => fs.rm(file.path, { force: true }))); throw error; } }
async function readFile(relativePath) { const normalized = normalizePath(relativePath); try { return { content: await fs.readFile(diskPath(normalized)), type: (await pool.query('SELECT mime_type FROM evidence_files WHERE path = $1', [normalized])).rows[0]?.mime_type || 'application/octet-stream' }; } catch (error) { const result = await pool.query('SELECT content, mime_type FROM evidence_files WHERE path = $1', [normalized]); if (!result.rowCount) { error.status = 404; throw error; } return { content: result.rows[0].content, type: result.rows[0].mime_type }; } }
async function deleteFile(relativePath) { const normalized = normalizePath(relativePath); const references = await pool.query(`SELECT COUNT(*)::int AS count FROM assessment_state, jsonb_each(data->'attachments') AS attachment(key, value), jsonb_array_elements(attachment.value) AS item WHERE item->>'path' = $1`, [ `upload/${normalized}` ]); if (references.rows[0].count > 1) return; await fs.rm(diskPath(normalized), { force: true }); const result = await pool.query('DELETE FROM evidence_files WHERE path = $1', [normalized]); if (!result.rowCount) { const error = new Error('File not found'); error.status = 404; throw error; } }
async function resetFiles() { await fs.rm(uploadRoot, { recursive: true, force: true }); await ensureUploadRoot(); await pool.query('DELETE FROM evidence_files'); }

module.exports = { ensureUploadRoot, listFiles, saveFile, saveFiles, readFile, deleteFile, resetFiles };
