const { pool } = require('../config/database');

const fields = ['personnel_name', 'employee_id', 'personnel_role', 'certification_name', 'issuer', 'reference_url', 'certification_level', 'status', 'issue_date', 'expiry_date', 'notes', 'on_canvas', 'position_x', 'position_y', 'card_width', 'card_height'];
function invalid(message) { return Object.assign(new Error(message), { status: 400 }); }
function text(value) { return String(value ?? '').trim(); }
function date(value) { return value ? String(value).slice(0, 10) : null; }
function number(value, fallback) { const result = Number(value); return Number.isFinite(result) ? Math.round(result) : fallback; }
function validate(data) { if (!data || !text(data.personnelName) || !text(data.certificationName)) throw invalid('personnelName and certificationName are required'); if (data.issueDate && !/^\d{4}-\d{2}-\d{2}$/.test(data.issueDate)) throw invalid('issueDate must be a valid date'); if (data.expiryDate && !/^\d{4}-\d{2}-\d{2}$/.test(data.expiryDate)) throw invalid('expiryDate must be a valid date'); if (text(data.referenceUrl) && !/^https?:\/\//i.test(text(data.referenceUrl))) throw invalid('referenceUrl must use http or https'); }
function level(value) { return ['Entry Level', 'Intermediate', 'Advanced / Expert'].includes(value) ? value : 'Intermediate'; }
function values(data) { return [text(data.personnelName), text(data.employeeId), text(data.personnelRole), text(data.certificationName), text(data.issuer), text(data.referenceUrl), level(data.certificationLevel), text(data.status || 'Planned'), date(data.issueDate), date(data.expiryDate), text(data.notes), Boolean(data.onCanvas), number(data.positionX, 24), number(data.positionY, 24), number(data.cardWidth, 260), number(data.cardHeight, 190)]; }
function map(row) { return { id: row.id, personnelName: row.personnel_name, employeeId: row.employee_id, personnelRole: row.personnel_role, certificationName: row.certification_name, issuer: row.issuer, referenceUrl: row.reference_url, certificationLevel: level(row.certification_level), status: row.status, issueDate: date(row.issue_date), expiryDate: date(row.expiry_date), notes: row.notes, onCanvas: Boolean(row.on_canvas), positionX: row.position_x, positionY: row.position_y, cardWidth: row.card_width, cardHeight: row.card_height, createdAt: row.created_at, updatedAt: row.updated_at }; }

async function ensureStore() {
  await pool.query(`CREATE TABLE IF NOT EXISTS personnel_certifications (id BIGSERIAL PRIMARY KEY, personnel_name TEXT NOT NULL, employee_id TEXT NOT NULL DEFAULT '', personnel_role TEXT NOT NULL DEFAULT '', certification_name TEXT NOT NULL, issuer TEXT NOT NULL DEFAULT '', reference_url TEXT NOT NULL DEFAULT '', certification_level TEXT NOT NULL DEFAULT 'Intermediate', status TEXT NOT NULL DEFAULT 'Planned', issue_date DATE, expiry_date DATE, notes TEXT NOT NULL DEFAULT '', on_canvas BOOLEAN NOT NULL DEFAULT FALSE, position_x INTEGER NOT NULL DEFAULT 24, position_y INTEGER NOT NULL DEFAULT 24, card_width INTEGER NOT NULL DEFAULT 260, card_height INTEGER NOT NULL DEFAULT 190, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
  await pool.query('ALTER TABLE personnel_certifications ADD COLUMN IF NOT EXISTS reference_url TEXT NOT NULL DEFAULT \'\'');
  await pool.query('ALTER TABLE personnel_certifications ADD COLUMN IF NOT EXISTS certification_level TEXT NOT NULL DEFAULT \'Intermediate\'');
  await pool.query('ALTER TABLE personnel_certifications ADD COLUMN IF NOT EXISTS on_canvas BOOLEAN NOT NULL DEFAULT FALSE');
  // Roadmap catalog rows now live in certification_roadmap_catalog; drop any legacy leftovers here.
  await pool.query("DELETE FROM personnel_certifications WHERE status = 'Catalog'");
}

async function list() { const result = await pool.query('SELECT * FROM personnel_certifications ORDER BY updated_at DESC, id DESC'); return result.rows.map(map); }
async function create(data) { validate(data); const result = await pool.query(`INSERT INTO personnel_certifications (${fields.join(', ')}) VALUES (${fields.map((_, index) => `$${index + 1}`).join(', ')}) RETURNING *`, values(data)); return map(result.rows[0]); }
async function update(id, data) { validate(data); const input = values(data).slice(0, 11); const editableFields = fields.slice(0, 11); const assignments = editableFields.map((field, index) => `${field} = $${index + 1}`).join(', '); const result = await pool.query(`UPDATE personnel_certifications SET ${assignments}, updated_at = NOW() WHERE id = $${editableFields.length + 1} RETURNING *`, [...input, id]); if (!result.rowCount) throw Object.assign(new Error('Certification not found'), { status: 404 }); return map(result.rows[0]); }
async function updateLayout(id, data) { const result = await pool.query('UPDATE personnel_certifications SET on_canvas = TRUE, certification_level = $1, position_x = $2, position_y = $3, card_width = $4, card_height = $5, updated_at = NOW() WHERE id = $6 RETURNING *', [level(data.certificationLevel), number(data.positionX, 24), number(data.positionY, 24), number(data.cardWidth, 260), number(data.cardHeight, 190), id]); if (!result.rowCount) throw Object.assign(new Error('Certification not found'), { status: 404 }); return map(result.rows[0]); }
async function remove(id) { const result = await pool.query('DELETE FROM personnel_certifications WHERE id = $1', [id]); if (!result.rowCount) throw Object.assign(new Error('Certification not found'), { status: 404 }); }
module.exports = { ensureStore, list, create, update, updateLayout, remove };
