const { pool } = require('../config/database');
const fs = require('fs').promises;
const path = require('path');
const seedDataFile = path.join(__dirname, '../../data/personnel-certifications-seed.json');

const fields = ['personnel_name', 'employee_id', 'personnel_role', 'certification_name', 'issuer', 'reference_url', 'certification_level', 'status', 'issue_date', 'expiry_date', 'notes', 'on_canvas', 'position_x', 'position_y', 'card_width', 'card_height'];
function invalid(message) { return Object.assign(new Error(message), { status: 400 }); }
function text(value) { return String(value ?? '').trim(); }
function date(value) { return value ? String(value).slice(0, 10) : null; }
function number(value, fallback) { const result = Number(value); return Number.isFinite(result) ? Math.round(result) : fallback; }
function validate(data) { if (!data || !text(data.personnelName) || !text(data.certificationName)) throw invalid('personnelName and certificationName are required'); if (data.issueDate && !/^\d{4}-\d{2}-\d{2}$/.test(data.issueDate)) throw invalid('issueDate must be a valid date'); if (data.expiryDate && !/^\d{4}-\d{2}-\d{2}$/.test(data.expiryDate)) throw invalid('expiryDate must be a valid date'); if (text(data.referenceUrl) && !/^https?:\/\//i.test(text(data.referenceUrl))) throw invalid('referenceUrl must use http or https'); }
function level(value) { return ['Entry Level', 'Intermediate', 'Advanced / Expert'].includes(value) ? value : 'Intermediate'; }
function values(data) { return [text(data.personnelName), text(data.employeeId), text(data.personnelRole), text(data.certificationName), text(data.issuer), text(data.referenceUrl), level(data.certificationLevel), text(data.status || 'Planned'), date(data.issueDate), date(data.expiryDate), text(data.notes), Boolean(data.onCanvas), number(data.positionX, 24), number(data.positionY, 24), number(data.cardWidth, 260), number(data.cardHeight, 190)]; }
function map(row) { return { id: row.id, personnelName: row.personnel_name, employeeId: row.employee_id, personnelRole: row.personnel_role, certificationName: row.certification_name, issuer: row.issuer, referenceUrl: row.reference_url, certificationLevel: level(row.certification_level), status: row.status, issueDate: date(row.issue_date), expiryDate: date(row.expiry_date), notes: row.notes, onCanvas: Boolean(row.on_canvas), positionX: row.position_x, positionY: row.position_y, cardWidth: row.card_width, cardHeight: row.card_height, createdAt: row.created_at, updatedAt: row.updated_at }; }
function decode(value) { return value.replace(/<[^>]+>/g, '').replace(/&amp;/g, '&').replace(/&quot;/g, '"').replace(/&#39;/g, "'").replace(/&nbsp;/g, ' ').replace(/\s+/g, ' ').trim(); }
function roadmapDomain(className) { if (/network/i.test(className)) return 'Communication and Network Security'; if (/iam/i.test(className)) return 'Identity and Access Management'; if (/engineer/i.test(className)) return 'Security Architecture and Engineering'; if (/asset/i.test(className)) return 'Asset Security'; if (/mgmt/i.test(className)) return 'Security and Risk Management'; if (/test/i.test(className)) return 'Security Assessment and Testing'; if (/software/i.test(className)) return 'Software Security'; if (/ops/i.test(className)) return 'Security Operations'; return 'Security Certification Roadmap'; }
function roadmapLevel(className, name) { const value = `${name} ${className}`.toLowerCase(); const entryKeywords = ['associate', 'foundation', 'foundational', 'beginner', 'entry', 'essentials', 'security+', 'pcsa', 'ccna', 'sc-900', 'az-900', 'az-104', 'rhcsa', 'lfcs', 'cysa+']; const advancedKeywords = ['expert', 'architect', 'master', 'lead', 'principal', 'professional', 'advanced', 'senior', 'cissp', 'cism', 'cisa', 'crisc', 'oscp', 'osce', 'osep', 'gse', 'gsp']; const entryScore = entryKeywords.reduce((score, keyword) => score + (value.includes(keyword) ? 1 : 0), 0); const advancedScore = advancedKeywords.reduce((score, keyword) => score + (value.includes(keyword) ? 1 : 0), 0); return entryScore > advancedScore && entryScore > 0 ? 'Entry Level' : advancedScore > 0 ? 'Advanced / Expert' : 'Intermediate'; }
async function seedRoadmapCatalog() { const source = path.join(__dirname, '../../Security-Certification-Roadmap9.html'); let html; try { html = await fs.readFile(source, 'utf8'); } catch (error) { return; } const records = []; const seen = new Set(); const pattern = /<a\s+class="([^"]*item[^"]*)"([^>]*)>([\s\S]*?)<\/a>/gi; let match; while ((match = pattern.exec(html))) { const name = decode(match[3]); const href = match[2].match(/href="([^"]*)"/i)?.[1] || ''; if (!name || name.length > 80 || seen.has(name)) continue; seen.add(name); records.push([`Roadmap catalog · ${roadmapDomain(match[1])}`, '', roadmapDomain(match[1]), name, 'Security Certification Roadmap', href, roadmapLevel(match[1], name), 'Catalog', null, null, 'Imported from Security-Certification-Roadmap9.html', 24 + (records.length % 5) * 290, 24 + Math.floor(records.length / 5) * 210, 260, 190]); } for (const record of records) { const existing = await pool.query('SELECT id FROM personnel_certifications WHERE status = $1 AND certification_name = $2 LIMIT 1', ['Catalog', record[3]]); if (existing.rowCount) await pool.query('UPDATE personnel_certifications SET personnel_name = $1, personnel_role = $2, issuer = $3, reference_url = $4, certification_level = $5, notes = $6, updated_at = NOW() WHERE id = $7', [record[0], record[2], record[4], record[5], record[6], record[10], existing.rows[0].id]); else await pool.query(`INSERT INTO personnel_certifications (${fields.join(', ')}) VALUES (${fields.map((_, index) => `$${index + 1}`).join(', ')})`, record); } }
async function ensureStore() { await pool.query(`CREATE TABLE IF NOT EXISTS personnel_certifications (id BIGSERIAL PRIMARY KEY, personnel_name TEXT NOT NULL, employee_id TEXT NOT NULL DEFAULT '', personnel_role TEXT NOT NULL DEFAULT '', certification_name TEXT NOT NULL, issuer TEXT NOT NULL DEFAULT '', reference_url TEXT NOT NULL DEFAULT '', certification_level TEXT NOT NULL DEFAULT 'Intermediate', status TEXT NOT NULL DEFAULT 'Planned', issue_date DATE, expiry_date DATE, notes TEXT NOT NULL DEFAULT '', on_canvas BOOLEAN NOT NULL DEFAULT FALSE, position_x INTEGER NOT NULL DEFAULT 24, position_y INTEGER NOT NULL DEFAULT 24, card_width INTEGER NOT NULL DEFAULT 260, card_height INTEGER NOT NULL DEFAULT 190, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`); await pool.query('ALTER TABLE personnel_certifications ADD COLUMN IF NOT EXISTS reference_url TEXT NOT NULL DEFAULT \'\''); await pool.query('ALTER TABLE personnel_certifications ADD COLUMN IF NOT EXISTS certification_level TEXT NOT NULL DEFAULT \'Intermediate\''); await pool.query('ALTER TABLE personnel_certifications ADD COLUMN IF NOT EXISTS on_canvas BOOLEAN NOT NULL DEFAULT FALSE'); await seedRoadmapCatalogFromData(); }
async function seedRoadmapCatalogFromData() { const payload = JSON.parse(await fs.readFile(seedDataFile, 'utf8')); if (!Array.isArray(payload.records)) throw new Error('Personnel certification seed records are invalid'); const names = new Set(); for (const record of payload.records) { if (!text(record.certificationName) || names.has(record.certificationName) || !['Entry Level', 'Intermediate', 'Advanced / Expert'].includes(record.certificationLevel)) throw new Error('Personnel certification seed contains an invalid or duplicate record'); names.add(record.certificationName); const existing = await pool.query('SELECT id FROM personnel_certifications WHERE status = $1 AND certification_name = $2 LIMIT 1', ['Catalog', record.certificationName]); const data = [record.personnelName, '', record.personnelRole, record.certificationName, record.issuer, record.referenceUrl, level(record.certificationLevel), 'Catalog', null, null, record.notes, false, 24, 24, 260, 190]; if (existing.rowCount) await pool.query('UPDATE personnel_certifications SET personnel_name = $1, personnel_role = $2, issuer = $3, reference_url = $4, certification_level = $5, notes = $6, updated_at = NOW() WHERE id = $7', [data[0], data[2], data[4], data[5], data[6], data[10], existing.rows[0].id]); else await pool.query(`INSERT INTO personnel_certifications (${fields.join(', ')}) VALUES (${fields.map((_, index) => `$${index + 1}`).join(', ')})`, data); } }
async function list() { const result = await pool.query('SELECT * FROM personnel_certifications ORDER BY updated_at DESC, id DESC'); return result.rows.map(map); }
async function create(data) { validate(data); const result = await pool.query(`INSERT INTO personnel_certifications (${fields.join(', ')}) VALUES (${fields.map((_, index) => `$${index + 1}`).join(', ')}) RETURNING *`, values(data)); return map(result.rows[0]); }
async function update(id, data) { validate(data); const input = values(data).slice(0, 11); const editableFields = fields.slice(0, 11); const assignments = editableFields.map((field, index) => `${field} = $${index + 1}`).join(', '); const result = await pool.query(`UPDATE personnel_certifications SET ${assignments}, updated_at = NOW() WHERE id = $${editableFields.length + 1} RETURNING *`, [...input, id]); if (!result.rowCount) throw Object.assign(new Error('Certification not found'), { status: 404 }); return map(result.rows[0]); }
async function updateLayout(id, data) { const result = await pool.query('UPDATE personnel_certifications SET on_canvas = TRUE, certification_level = $1, position_x = $2, position_y = $3, card_width = $4, card_height = $5, updated_at = NOW() WHERE id = $6 RETURNING *', [level(data.certificationLevel), number(data.positionX, 24), number(data.positionY, 24), number(data.cardWidth, 260), number(data.cardHeight, 190), id]); if (!result.rowCount) throw Object.assign(new Error('Certification not found'), { status: 404 }); return map(result.rows[0]); }
async function remove(id) { const result = await pool.query('DELETE FROM personnel_certifications WHERE id = $1', [id]); if (!result.rowCount) throw Object.assign(new Error('Certification not found'), { status: 404 }); }
module.exports = { ensureStore, list, create, update, updateLayout, remove };
