const { pool } = require('../config/database');
const { PDFDocument, StandardFonts, rgb } = require('pdf-lib');

const fields = [
  'requestor_name', 'asset_name', 'department', 'previously_accepted', 'risk_description',
  'benefit_justification', 'mitigation_plan', 'business_owner_decision', 'remediation_date',
  'requestor_print_name', 'requestor_email_phone', 'requestor_signature', 'requestor_date',
  'cio_comments', 'cio_name', 'cio_signature', 'cio_date', 'cis_decision', 'cis_reason',
  'cis_conditions', 'cis_name', 'cis_signature', 'cis_date'
];
const requiredText = ['requestorName', 'assetName', 'department', 'riskDescription', 'benefitJustification', 'mitigationPlan'];
const decisions = { businessOwnerDecision: ['temporary', 'one_year', 'denied'], cisDecision: ['approved', 'denied', 'conditional'] };

function invalid(message) { return Object.assign(new Error(message), { status: 400 }); }
function validate(data) {
  if (!data || typeof data !== 'object') throw invalid('Form data is required');
  requiredText.forEach(field => { if (typeof data[field] !== 'string' || !data[field].trim()) throw invalid(`${field} is required`); });
  Object.entries(decisions).forEach(([field, values]) => { if (!values.includes(data[field])) throw invalid(`${field} is invalid`); });
  ['remediationDate', 'requestorDate', 'cioDate', 'cisDate'].forEach(field => { if (data[field] && !/^\d{4}-\d{2}-\d{2}$/.test(data[field])) throw invalid(`${field} must be a valid date`); });
}
function values(data) {
  return [data.requestorName.trim(), data.assetName.trim(), data.department.trim(), Boolean(data.previouslyAccepted), data.riskDescription.trim(), data.benefitJustification.trim(), data.mitigationPlan.trim(), data.businessOwnerDecision, data.remediationDate || null, String(data.requestorPrintName || '').trim(), String(data.requestorEmailPhone || '').trim(), String(data.requestorSignature || '').trim(), data.requestorDate || null, String(data.cioComments || '').trim(), String(data.cioName || '').trim(), String(data.cioSignature || '').trim(), data.cioDate || null, data.cisDecision, String(data.cisReason || '').trim(), String(data.cisConditions || '').trim(), String(data.cisName || '').trim(), String(data.cisSignature || '').trim(), data.cisDate || null];
}
function mapRow(row) {
  return { id: row.id, requestorName: row.requestor_name, assetName: row.asset_name, department: row.department, previouslyAccepted: row.previously_accepted, riskDescription: row.risk_description, benefitJustification: row.benefit_justification, mitigationPlan: row.mitigation_plan, businessOwnerDecision: row.business_owner_decision, remediationDate: row.remediation_date, requestorPrintName: row.requestor_print_name, requestorEmailPhone: row.requestor_email_phone, requestorSignature: row.requestor_signature, requestorDate: row.requestor_date, cioComments: row.cio_comments, cioName: row.cio_name, cioSignature: row.cio_signature, cioDate: row.cio_date, cisDecision: row.cis_decision, cisReason: row.cis_reason, cisConditions: row.cis_conditions, cisName: row.cis_name, cisSignature: row.cis_signature, cisDate: row.cis_date, createdAt: row.created_at, updatedAt: row.updated_at };
}
const select = `SELECT id, ${fields.join(', ')}, created_at, updated_at FROM risk_acceptance_forms`;
async function ensureStore() {
  await pool.query(`CREATE TABLE IF NOT EXISTS risk_acceptance_forms (id BIGSERIAL PRIMARY KEY, requestor_name TEXT NOT NULL, asset_name TEXT NOT NULL, department TEXT NOT NULL, previously_accepted BOOLEAN NOT NULL DEFAULT FALSE, risk_description TEXT NOT NULL, benefit_justification TEXT NOT NULL, mitigation_plan TEXT NOT NULL, business_owner_decision TEXT NOT NULL CHECK (business_owner_decision IN ('temporary', 'one_year', 'denied')), remediation_date DATE, requestor_print_name TEXT NOT NULL DEFAULT '', requestor_email_phone TEXT NOT NULL DEFAULT '', requestor_signature TEXT NOT NULL DEFAULT '', requestor_date DATE, cio_comments TEXT NOT NULL DEFAULT '', cio_name TEXT NOT NULL DEFAULT '', cio_signature TEXT NOT NULL DEFAULT '', cio_date DATE, cis_decision TEXT NOT NULL CHECK (cis_decision IN ('approved', 'denied', 'conditional')), cis_reason TEXT NOT NULL DEFAULT '', cis_conditions TEXT NOT NULL DEFAULT '', cis_name TEXT NOT NULL DEFAULT '', cis_signature TEXT NOT NULL DEFAULT '', cis_date DATE, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`);
}
async function list() { const result = await pool.query(`${select} ORDER BY updated_at DESC`); return result.rows.map(mapRow); }
async function create(data) { validate(data); const result = await pool.query(`INSERT INTO risk_acceptance_forms (${fields.join(', ')}) VALUES (${fields.map((_, index) => `$${index + 1}`).join(', ')}) RETURNING *`, values(data)); return mapRow(result.rows[0]); }
async function update(id, data) { validate(data); const assignments = fields.map((field, index) => `${field} = $${index + 1}`).join(', '); const result = await pool.query(`UPDATE risk_acceptance_forms SET ${assignments}, updated_at = NOW() WHERE id = $${fields.length + 1} RETURNING *`, [...values(data), id]); if (!result.rowCount) throw Object.assign(new Error('Risk acceptance form not found'), { status: 404 }); return mapRow(result.rows[0]); }
async function remove(id) { const result = await pool.query('DELETE FROM risk_acceptance_forms WHERE id = $1', [id]); if (!result.rowCount) throw Object.assign(new Error('Risk acceptance form not found'), { status: 404 }); }
async function get(id) { const result = await pool.query(`${select} WHERE id = $1`, [id]); if (!result.rowCount) throw Object.assign(new Error('Risk acceptance form not found'), { status: 404 }); return mapRow(result.rows[0]); }
function dateText(value) { if (!value) return ''; const text = String(value); if (/^\d{4}-\d{2}-\d{2}/.test(text)) return text.slice(0, 10); const date = new Date(value); return Number.isNaN(date.getTime()) ? '' : date.toISOString().slice(0, 10); }

async function exportPdf(id) {
  const form = await get(id); const pdf = await PDFDocument.create(); const font = await pdf.embedFont(StandardFonts.Helvetica); const bold = await pdf.embedFont(StandardFonts.HelveticaBold);
  const W = 595.28; const H = 841.89; const M = 54; const CW = W - M * 2; const ink = rgb(.08, .1, .11); const muted = rgb(.32, .39, .37); const line = rgb(.78, .82, .8); const accent = rgb(.09, .2, .23); const paper = rgb(.98, .99, .98);
  const wrap = (text, size, width, typeface = font) => { const result = []; String(text || '-').split(/\r?\n/).forEach(paragraph => { let current = ''; paragraph.split(/\s+/).filter(Boolean).forEach(word => { const candidate = current ? `${current} ${word}` : word; if (!current || typeface.widthOfTextAtSize(candidate, size) <= width) current = candidate; else { result.push(current); current = word; } }); result.push(current); }); return result; };
  const header = (page, number) => { page.drawText('Cybersecurity Risk Acceptance Form', { x: M, y: H - 48, size: 17, font: bold, color: accent }); page.drawText('Form version 1.1', { x: W - M - 72, y: H - 45, size: 8, font, color: muted }); page.drawLine({ start: { x: M, y: H - 61 }, end: { x: W - M, y: H - 61 }, thickness: 1.5, color: accent }); page.drawText(`Page ${number} of 3`, { x: W - M - 42, y: 25, size: 7, font, color: muted }); };
  const section = (page, title, y) => { page.drawText(title, { x: M, y, size: 12, font: bold, color: accent }); page.drawLine({ start: { x: M, y: y - 7 }, end: { x: W - M, y: y - 7 }, thickness: .7, color: line }); return y - 24; };
  const paragraph = (page, text, y) => { const size = 9; wrap(text, size, CW).forEach((value, index) => page.drawText(value, { x: M, y: y - index * 13, size, font, color: muted })); return y - wrap(text, size, CW).length * 13 - 10; };
  const field = (page, label, value, y, height = 34) => { page.drawText(label, { x: M, y, size: 8.5, font: bold, color: accent }); const boxY = y - height - 6; page.drawRectangle({ x: M, y: boxY, width: CW, height, borderColor: line, borderWidth: .8, color: paper }); const lines = wrap(value, 9, CW - 16); const max = Math.max(1, Math.floor((height - 12) / 12)); lines.slice(0, max).forEach((text, index) => page.drawText(text, { x: M + 8, y: boxY + height - 16 - index * 12, size: 9, font, color: ink })); return boxY - 15; };
  const inline = (page, label, value, x, y, width = 270) => { if (label) page.drawText(label, { x, y, size: 8.5, font: bold, color: accent }); page.drawLine({ start: { x, y: y - 4 }, end: { x: x + width, y: y - 4 }, thickness: .7, color: line }); page.drawText(wrap(value, 9, width - 4)[0] || '-', { x: x + 2, y: y - 16, size: 9, font, color: ink }); };
  const choice = (page, checked, text, x, y) => { page.drawRectangle({ x, y: y - 1, width: 10, height: 10, borderColor: accent, borderWidth: .8 }); if (checked) page.drawText('X', { x: x + 2, y: y + 1, size: 8, font: bold, color: accent }); page.drawText(text, { x: x + 17, y, size: 9, font, color: ink }); };

  const page1 = pdf.addPage([W, H]); header(page1, 1); let y = H - 94; y = section(page1, 'Purpose', y); y = paragraph(page1, 'Cybersecurity Risk Acceptance is a deliberate executive decision by a business or system owner to acknowledge and accept a cybersecurity risk which, for the reason given, cannot be remediated through available security controls and measures.', y); y = paragraph(page1, 'The decision to accept cybersecurity risks should be made in consultation with other stakeholders, including Information Technology and Cybersecurity.', y); y = paragraph(page1, 'Risk acceptance is appropriate when further remediation or mitigation is not possible or is too costly, and the institutional benefit of the system, application or service exceeds the potential impact of the risk.', y); y = section(page1, 'Procedure', y - 8); y = paragraph(page1, 'Using the form that follows, the application, service or system owner describes the risk to be accepted, its potential impact, why it should be accepted, and mitigating factors, if any.', y); y = paragraph(page1, 'The completed form should be sent to the relevant business owner for review and signature. The business owner can accept the described risk for up to one year, limit the acceptance to a shorter period, or deny the acceptance.', y); y = paragraph(page1, 'The form should then be sent to the CIO or equivalent for acknowledgement and comments, and next to the Cybersecurity Team for final approval.', y); section(page1, 'Risk Conditions', y - 8); paragraph(page1, 'Risk acceptance may apply to financial, reputational, privacy, legal, operational, or high and critical cybersecurity vulnerability risks. If the request is denied, the affected application, service, or system must promptly be brought offline or terminated.', y - 32);
  const page2 = pdf.addPage([W, H]); header(page2, 2); y = H - 94; y = section(page2, 'Application, Service or System Operational Owner', y); inline(page2, 'Name of Requestor', form.requestorName, M, y, 250); inline(page2, 'Asset Name', form.assetName, M + 270, y, 217); y -= 49; inline(page2, 'Department', form.department, M, y, 250); choice(page2, form.previouslyAccepted, 'This risk has been accepted previously', M + 270, y); y -= 34; y = field(page2, 'Description of Risk and/or Compliance Deviation', form.riskDescription, y, 112); y = field(page2, 'Benefit and Justification for Accepting this Risk', form.benefitJustification, y, 112); field(page2, 'Factors that Minimize this Risk / Proposed Mitigation Plan', form.mitigationPlan, y, 150);
  const page3 = pdf.addPage([W, H]); header(page3, 3); y = H - 94; y = section(page3, 'Business Owner Acceptance (Max One Year)', y); choice(page3, form.businessOwnerDecision === 'temporary', 'Yes, for a temporary period', M, y); inline(page3, 'Risk will be remediated by', dateText(form.remediationDate), M + 300, y, 187); y -= 25; choice(page3, form.businessOwnerDecision === 'one_year', 'Yes, for up to one year. Risk acceptance must be recertified annually.', M, y); y -= 25; choice(page3, form.businessOwnerDecision === 'denied', 'No. I find the risk greater than the potential business benefit.', M, y); y -= 48; inline(page3, 'Requestor name (print)', form.requestorPrintName, M, y, 270); inline(page3, 'Email / Telephone', form.requestorEmailPhone, M + 290, y, 197); y -= 42; inline(page3, 'Signature', form.requestorSignature, M, y, 270); inline(page3, 'Date', dateText(form.requestorDate), M + 290, y, 197); y -= 57; y = section(page3, 'CIO (or equivalent) Acknowledgement', y); y = field(page3, 'Comments (if any)', form.cioComments, y, 62); inline(page3, 'Name', form.cioName, M, y, 270); y -= 42; inline(page3, 'Signature', form.cioSignature, M, y, 270); inline(page3, 'Date', dateText(form.cioDate), M + 290, y, 197); y -= 57; y = section(page3, 'CIS Final Review', y); choice(page3, form.cisDecision === 'approved', 'Approved', M, y); choice(page3, form.cisDecision === 'denied', 'Denied - Reason:', M + 150, y); inline(page3, '', form.cisReason, M + 250, y + 5, 231); y -= 29; choice(page3, form.cisDecision === 'conditional', 'Approved with conditions / comments:', M, y); inline(page3, '', form.cisConditions, M + 250, y + 5, 231); y -= 55; inline(page3, 'Name', form.cisName, M, y, 270); y -= 42; inline(page3, 'Signature', form.cisSignature, M, y, 270); inline(page3, 'Date', dateText(form.cisDate), M + 290, y, 197);
  return pdf.save();
}

module.exports = { ensureStore, list, create, update, remove, exportPdf };
