const { pool } = require('../config/database');

const levels = ['High Risk (Tier 1)', 'Medium Risk (Tier 2)', 'Low Risk (Tier 3)'];
const statuses = ['Not started', 'In progress', 'Complete', 'Accepted'];
const relationshipStatuses = ['Active', 'Offboarded', 'Expired', 'Terminated'];
function invalid(message) { return Object.assign(new Error(message), { status: 400 }); }
function text(value) { return String(value ?? '').trim(); }
function normalizeRiskLevel(value) { const candidate = text(value); return levels.includes(candidate) ? candidate : 'Medium Risk (Tier 2)'; }
function normalizeAssessmentStatus(value) { const candidate = text(value); return statuses.includes(candidate) ? candidate : 'Not started'; }
function normalizeRelationshipStatus(value) { const candidate = text(value); const match = relationshipStatuses.find(status => status.toLowerCase() === candidate.toLowerCase()); return match || 'Active'; }
async function validate(data) { if (!text(data.thirdParty) || !text(data.serviceDependency)) throw invalid('thirdParty and serviceDependency are required'); if (data.riskLevel && !levels.includes(data.riskLevel)) throw invalid('Invalid risk level'); if (data.assessmentStatus && !statuses.includes(data.assessmentStatus)) throw invalid('Invalid assessment status'); if (data.relationshipStatus && !relationshipStatuses.some(status => status.toLowerCase() === text(data.relationshipStatus).toLowerCase())) throw invalid('Invalid relationship status'); if (data.nextReview && !/^\d{4}-\d{2}-\d{2}$/.test(data.nextReview)) throw invalid('nextReview must be a valid date'); const questionnaireId = Number(data.questionnaireId); if (!Number.isSafeInteger(questionnaireId) || questionnaireId < 1) throw invalid('A vendor from Vendor assessments is required'); const questionnaire = await pool.query('SELECT vendor_name FROM tprm_due_diligence_questionnaires WHERE id = $1', [questionnaireId]); if (!questionnaire.rowCount || questionnaire.rows[0].vendor_name !== text(data.thirdParty)) throw invalid('Selected vendor assessment does not match thirdParty'); return questionnaireId; }
function map(row) { return { id: row.id, thirdParty: row.third_party, questionnaireId: row.questionnaire_id, serviceDependency: row.service_dependency, riskLevel: row.risk_level, assessmentStatus: row.assessment_status, relationshipStatus: row.relationship_status || 'Active', nextReview: row.next_review, notes: row.notes, riskRegisterIds: Array.isArray(row.risk_register_ids) ? row.risk_register_ids : [], dueDiligenceAssessment: row.due_diligence_assessment || {}, createdAt: row.created_at, updatedAt: row.updated_at }; }
function riskRegisterIds(value) { return Array.isArray(value) ? value.map(item => text(item)).filter(Boolean) : []; }
async function ensureStore() { await pool.query(`CREATE TABLE IF NOT EXISTS tprm_risk_register (id BIGSERIAL PRIMARY KEY, third_party TEXT NOT NULL, service_dependency TEXT NOT NULL, risk_level TEXT NOT NULL DEFAULT 'Medium Risk (Tier 2)', assessment_status TEXT NOT NULL DEFAULT 'Not started', relationship_status TEXT NOT NULL DEFAULT 'Active', next_review DATE, notes TEXT NOT NULL DEFAULT '', risk_register_ids JSONB NOT NULL DEFAULT '[]'::jsonb, questionnaire_id BIGINT REFERENCES tprm_due_diligence_questionnaires(id) ON DELETE SET NULL, due_diligence_assessment JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`); await pool.query("ALTER TABLE tprm_risk_register ADD COLUMN IF NOT EXISTS questionnaire_id BIGINT REFERENCES tprm_due_diligence_questionnaires(id) ON DELETE SET NULL"); await pool.query("ALTER TABLE tprm_risk_register ADD COLUMN IF NOT EXISTS due_diligence_assessment JSONB NOT NULL DEFAULT '{}'::jsonb"); await pool.query("ALTER TABLE tprm_risk_register ADD COLUMN IF NOT EXISTS risk_register_ids JSONB NOT NULL DEFAULT '[]'::jsonb"); await pool.query("ALTER TABLE tprm_risk_register ADD COLUMN IF NOT EXISTS relationship_status TEXT NOT NULL DEFAULT 'Active'"); await pool.query("CREATE TABLE IF NOT EXISTS tprm_related_risks (tprm_id BIGINT NOT NULL REFERENCES tprm_risk_register(id) ON DELETE CASCADE, risk_id TEXT NOT NULL REFERENCES risk_register(risk_id) ON DELETE CASCADE, PRIMARY KEY (tprm_id, risk_id))"); await pool.query("INSERT INTO tprm_related_risks (tprm_id, risk_id) SELECT t.id, selected.risk_id FROM tprm_risk_register t CROSS JOIN LATERAL jsonb_array_elements_text(t.risk_register_ids) AS selected(risk_id) INNER JOIN risk_register risk ON risk.risk_id = selected.risk_id ON CONFLICT DO NOTHING"); }
async function list() { const result = await pool.query("SELECT t.*, COALESCE(array_agg(r.risk_id) FILTER (WHERE r.risk_id IS NOT NULL), ARRAY[]::text[]) AS relation_ids FROM tprm_risk_register t LEFT JOIN tprm_related_risks r ON r.tprm_id = t.id GROUP BY t.id ORDER BY t.updated_at DESC, t.id DESC"); return result.rows.map(row => map({ ...row, risk_register_ids: row.relation_ids.length ? row.relation_ids : row.risk_register_ids })); }
async function syncRelatedRisks(tprmId, ids) { await pool.query('DELETE FROM tprm_related_risks WHERE tprm_id = $1', [tprmId]); for (const riskId of riskRegisterIds(ids)) await pool.query('INSERT INTO tprm_related_risks (tprm_id, risk_id) SELECT $1, $2 WHERE EXISTS (SELECT 1 FROM risk_register WHERE risk_id = $2) ON CONFLICT DO NOTHING', [tprmId, riskId]); }
async function create(data) { const questionnaireId = await validate(data); const riskLevel = normalizeRiskLevel(data.riskLevel); const assessmentStatus = normalizeAssessmentStatus(data.assessmentStatus); const relationshipStatus = normalizeRelationshipStatus(data.relationshipStatus); const result = await pool.query('INSERT INTO tprm_risk_register (third_party, service_dependency, risk_level, assessment_status, relationship_status, next_review, notes, risk_register_ids, questionnaire_id, due_diligence_assessment) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10) RETURNING *', [text(data.thirdParty), text(data.serviceDependency), riskLevel, assessmentStatus, relationshipStatus, data.nextReview || null, text(data.notes), JSON.stringify(riskRegisterIds(data.riskRegisterIds)), questionnaireId, data.dueDiligenceAssessment || {}]); await syncRelatedRisks(result.rows[0].id, data.riskRegisterIds); return map(result.rows[0]); }
async function update(id, data) { const questionnaireId = await validate(data); const riskLevel = normalizeRiskLevel(data.riskLevel); const assessmentStatus = normalizeAssessmentStatus(data.assessmentStatus); const relationshipStatus = normalizeRelationshipStatus(data.relationshipStatus); const result = await pool.query('UPDATE tprm_risk_register SET third_party = $1, service_dependency = $2, risk_level = $3, assessment_status = $4, relationship_status = $5, next_review = $6, notes = $7, risk_register_ids = $8, questionnaire_id = $9, due_diligence_assessment = COALESCE($10::jsonb, due_diligence_assessment), updated_at = NOW() WHERE id = $11 RETURNING *', [text(data.thirdParty), text(data.serviceDependency), riskLevel, assessmentStatus, relationshipStatus, data.nextReview || null, text(data.notes), JSON.stringify(riskRegisterIds(data.riskRegisterIds)), questionnaireId, data.dueDiligenceAssessment ? JSON.stringify(data.dueDiligenceAssessment) : null, id]); if (!result.rowCount) throw Object.assign(new Error('TPRM record not found'), { status: 404 }); await syncRelatedRisks(id, data.riskRegisterIds); return map(result.rows[0]); }
async function remove(id) { const result = await pool.query('DELETE FROM tprm_risk_register WHERE id = $1', [id]); if (!result.rowCount) throw Object.assign(new Error('TPRM record not found'), { status: 404 }); }
module.exports = { ensureStore, list, create, update, remove };
