const { pool } = require('../config/database');

const statuses = ['Draft', 'In progress', 'Complete', 'Expired', 'Final'];
const results = ['Pending', 'Approved', 'Approved with Conditions', 'Rejected'];
function invalid(message) { return Object.assign(new Error(message), { status: 400 }); }
function text(value) { return String(value ?? '').trim(); }
function validate(data) { if (!text(data.vendorName)) throw invalid('vendorName is required'); if (!statuses.includes(data.status)) throw invalid('Invalid questionnaire status'); if (!results.includes(data.result)) throw invalid('Invalid assessment result'); if (data.reviewDate && !/^\d{4}-\d{2}-\d{2}$/.test(data.reviewDate)) throw invalid('reviewDate must be a valid date'); }
function map(row) { return { id: row.id, vendorName: row.vendor_name, status: row.assessment_status, reviewDate: row.review_date, result: row.assessment_result, reviewer: row.reviewer, notes: row.notes, responses: row.responses || {}, createdAt: row.created_at, updatedAt: row.updated_at }; }
async function ensureStore() { await pool.query(`CREATE TABLE IF NOT EXISTS tprm_due_diligence_questionnaires (id BIGSERIAL PRIMARY KEY, vendor_name TEXT NOT NULL, assessment_status TEXT NOT NULL DEFAULT 'Draft', review_date DATE, assessment_result TEXT NOT NULL DEFAULT 'Pending', reviewer TEXT NOT NULL DEFAULT '', notes TEXT NOT NULL DEFAULT '', responses JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`); await pool.query("ALTER TABLE tprm_due_diligence_questionnaires ADD COLUMN IF NOT EXISTS responses JSONB NOT NULL DEFAULT '{}'::jsonb"); }
async function list() { const result = await pool.query('SELECT * FROM tprm_due_diligence_questionnaires ORDER BY updated_at DESC, id DESC'); return result.rows.map(map); }
async function create(data) { validate(data); const result = await pool.query('INSERT INTO tprm_due_diligence_questionnaires (vendor_name, assessment_status, review_date, assessment_result, reviewer, notes, responses) VALUES ($1, $2, $3, $4, $5, $6, $7) RETURNING *', [text(data.vendorName), data.status, data.reviewDate || null, data.result, text(data.reviewer), text(data.notes), data.responses || {}]); return map(result.rows[0]); }
async function update(id, data) { validate(data); const result = await pool.query('UPDATE tprm_due_diligence_questionnaires SET vendor_name = $1, assessment_status = $2, review_date = $3, assessment_result = $4, reviewer = $5, notes = $6, responses = $7, updated_at = NOW() WHERE id = $8 RETURNING *', [text(data.vendorName), data.status, data.reviewDate || null, data.result, text(data.reviewer), text(data.notes), data.responses || {}, id]); if (!result.rowCount) throw Object.assign(new Error('Questionnaire not found'), { status: 404 }); return map(result.rows[0]); }
async function remove(id) { const result = await pool.query('DELETE FROM tprm_due_diligence_questionnaires WHERE id = $1', [id]); if (!result.rowCount) throw Object.assign(new Error('Questionnaire not found'), { status: 404 }); }
module.exports = { ensureStore, list, create, update, remove };
