const { pool } = require('../config/database');

const levels = ['High Risk (Tier 1)', 'Medium Risk (Tier 2)', 'Low Risk (Tier 3)'];
const statuses = ['Not started', 'In progress', 'Complete', 'Accepted'];
function invalid(message) { return Object.assign(new Error(message), { status: 400 }); }
function text(value) { return String(value ?? '').trim(); }
function normalizeRiskLevel(value) { const candidate = text(value); return levels.includes(candidate) ? candidate : 'Medium Risk (Tier 2)'; }
function normalizeAssessmentStatus(value) { const candidate = text(value); return statuses.includes(candidate) ? candidate : 'Not started'; }
async function validate(data) { if (!text(data.thirdParty) || !text(data.serviceDependency)) throw invalid('thirdParty and serviceDependency are required'); if (data.riskLevel && !levels.includes(data.riskLevel)) throw invalid('Invalid risk level'); if (data.assessmentStatus && !statuses.includes(data.assessmentStatus)) throw invalid('Invalid assessment status'); if (data.nextReview && !/^\d{4}-\d{2}-\d{2}$/.test(data.nextReview)) throw invalid('nextReview must be a valid date'); const questionnaireId = Number(data.questionnaireId); if (!Number.isSafeInteger(questionnaireId) || questionnaireId < 1) throw invalid('A vendor from Vendor assessments is required'); const questionnaire = await pool.query('SELECT vendor_name FROM tprm_due_diligence_questionnaires WHERE id = $1', [questionnaireId]); if (!questionnaire.rowCount || questionnaire.rows[0].vendor_name !== text(data.thirdParty)) throw invalid('Selected vendor assessment does not match thirdParty'); return questionnaireId; }
function map(row) { return { id: row.id, thirdParty: row.third_party, questionnaireId: row.questionnaire_id, serviceDependency: row.service_dependency, riskLevel: row.risk_level, assessmentStatus: row.assessment_status, nextReview: row.next_review, notes: row.notes, dueDiligenceAssessment: row.due_diligence_assessment || {}, createdAt: row.created_at, updatedAt: row.updated_at }; }
async function ensureStore() { await pool.query(`CREATE TABLE IF NOT EXISTS tprm_risk_register (id BIGSERIAL PRIMARY KEY, third_party TEXT NOT NULL, service_dependency TEXT NOT NULL, risk_level TEXT NOT NULL DEFAULT 'Medium Risk (Tier 2)', assessment_status TEXT NOT NULL DEFAULT 'Not started', next_review DATE, notes TEXT NOT NULL DEFAULT '', questionnaire_id BIGINT REFERENCES tprm_due_diligence_questionnaires(id) ON DELETE SET NULL, due_diligence_assessment JSONB NOT NULL DEFAULT '{}'::jsonb, created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(), updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW())`); await pool.query("ALTER TABLE tprm_risk_register ADD COLUMN IF NOT EXISTS questionnaire_id BIGINT REFERENCES tprm_due_diligence_questionnaires(id) ON DELETE SET NULL"); await pool.query("ALTER TABLE tprm_risk_register ADD COLUMN IF NOT EXISTS due_diligence_assessment JSONB NOT NULL DEFAULT '{}'::jsonb"); }
async function list() { const result = await pool.query('SELECT * FROM tprm_risk_register ORDER BY updated_at DESC, id DESC'); return result.rows.map(map); }
async function create(data) { const questionnaireId = await validate(data); const riskLevel = normalizeRiskLevel(data.riskLevel); const assessmentStatus = normalizeAssessmentStatus(data.assessmentStatus); const result = await pool.query('INSERT INTO tprm_risk_register (third_party, service_dependency, risk_level, assessment_status, next_review, notes, questionnaire_id, due_diligence_assessment) VALUES ($1, $2, $3, $4, $5, $6, $7, $8) RETURNING *', [text(data.thirdParty), text(data.serviceDependency), riskLevel, assessmentStatus, data.nextReview || null, text(data.notes), questionnaireId, data.dueDiligenceAssessment || {}]); return map(result.rows[0]); }
async function update(id, data) { const questionnaireId = await validate(data); const riskLevel = normalizeRiskLevel(data.riskLevel); const assessmentStatus = normalizeAssessmentStatus(data.assessmentStatus); const result = await pool.query('UPDATE tprm_risk_register SET third_party = $1, service_dependency = $2, risk_level = $3, assessment_status = $4, next_review = $5, notes = $6, questionnaire_id = $7, due_diligence_assessment = COALESCE($8::jsonb, due_diligence_assessment), updated_at = NOW() WHERE id = $9 RETURNING *', [text(data.thirdParty), text(data.serviceDependency), riskLevel, assessmentStatus, data.nextReview || null, text(data.notes), questionnaireId, data.dueDiligenceAssessment ? JSON.stringify(data.dueDiligenceAssessment) : null, id]); if (!result.rowCount) throw Object.assign(new Error('TPRM record not found'), { status: 404 }); return map(result.rows[0]); }
async function remove(id) { const result = await pool.query('DELETE FROM tprm_risk_register WHERE id = $1', [id]); if (!result.rowCount) throw Object.assign(new Error('TPRM record not found'), { status: 404 }); }
module.exports = { ensureStore, list, create, update, remove };
