function renderCertificationReference() { const board = $('certificationReferenceBoard'); if (!board) return; const defaultDomains = ['Communication and Network Security', 'Identity and Access Management', 'Security Architecture and Engineering', 'Asset Security', 'Security and Risk Management', 'Security Assessment and Testing', 'Software Security', 'Security Operations']; const domains = [...new Set([...defaultDomains, ...certificationRoadmapCatalog.map(row => row.domain)])]; const levels = ['Advanced / Expert', 'Intermediate', 'Entry Level']; const canEdit = currentUserRole === 'admin'; board.innerHTML = ''; const grid = document.createElement('div'); grid.className = 'certification-reference-board'; domains.forEach(domain => { const column = document.createElement('section'); column.className = 'certification-reference-domain'; const heading = document.createElement('h4'); heading.textContent = domain; column.appendChild(heading); levels.forEach(level => { const area = document.createElement('div'); area.className = 'certification-reference-level'; area.dataset.roadmapDropZone = 'true'; area.dataset.roadmapDomain = domain; area.dataset.roadmapLevel = level; const label = document.createElement('span'); label.className = 'certification-reference-level-name'; label.textContent = level; const items = document.createElement('div'); certificationRoadmapCatalog.filter(row => row.domain === domain && row.certificationLevel === level).forEach(row => { const item = document.createElement('button'); item.className = 'certification-reference-item'; item.type = 'button'; item.draggable = canEdit; item.dataset.roadmapCatalogId = row.id; item.textContent = row.certificationName; items.appendChild(item); }); area.append(label, items); column.appendChild(area); }); grid.appendChild(column); }); board.appendChild(grid); certificationReferenceLoaded = true; }
async function moveRoadmapCatalogItem(id, destination) { const row = certificationRoadmapCatalog.find(item => String(item.id) === String(id)); if (!row || (row.domain === destination.dataset.roadmapDomain && row.certificationLevel === destination.dataset.roadmapLevel)) return; const response = await fetch(`/api/certification-roadmap-catalog/${row.id}`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ ...row, domain: destination.dataset.roadmapDomain, certificationLevel: destination.dataset.roadmapLevel }) }); if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Unable to move catalog item'); Object.assign(row, await response.json()); renderCertificationReference(); renderCertificationCatalogOptions(); }
$('certificationReferenceBoard').addEventListener('dragstart', event => { const item = event.target.closest('[data-roadmap-catalog-id]'); if (!item || currentUserRole !== 'admin') return event.preventDefault(); event.dataTransfer.effectAllowed = 'move'; event.dataTransfer.setData('text/plain', item.dataset.roadmapCatalogId); item.classList.add('dragging'); });
$('certificationReferenceBoard').addEventListener('dragend', event => event.target.closest('[data-roadmap-catalog-id]')?.classList.remove('dragging'));
$('certificationReferenceBoard').addEventListener('dragover', event => { const destination = event.target.closest('[data-roadmap-drop-zone]'); if (!destination || currentUserRole !== 'admin') return; event.preventDefault(); event.dataTransfer.dropEffect = 'move'; destination.classList.add('is-drop-target'); });
$('certificationReferenceBoard').addEventListener('dragleave', event => event.target.closest('[data-roadmap-drop-zone]')?.classList.remove('is-drop-target'));
$('certificationReferenceBoard').addEventListener('drop', async event => { const destination = event.target.closest('[data-roadmap-drop-zone]'); if (!destination || currentUserRole !== 'admin') return; event.preventDefault(); destination.classList.remove('is-drop-target'); try { await moveRoadmapCatalogItem(event.dataTransfer.getData('text/plain'), destination); } catch (error) { $('roadmapCatalogStatus').textContent = error.message; } });
async function saveRoadmapCatalog(event) { event.preventDefault(); const id = $('roadmapCatalogId').value; const response = await fetch(id ? `/api/certification-roadmap-catalog/${id}` : '/api/certification-roadmap-catalog', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(roadmapCatalogData()) }); if (!response.ok) { $('roadmapCatalogStatus').textContent = (await response.json().catch(() => ({}))).error || 'Save failed'; return; } $('roadmapCatalogModal').close(); await loadCertifications(); }
async function deleteRoadmapCatalog() { const id = $('roadmapCatalogId').value; if (!id || !confirm('Delete this roadmap catalog item?')) return; const response = await fetch(`/api/certification-roadmap-catalog/${id}`, { method: 'DELETE' }); if (!response.ok) { $('roadmapCatalogStatus').textContent = 'Delete failed'; return; } $('roadmapCatalogModal').close(); await loadCertifications(); }
async function loadCertifications() { const [personnelResponse, organizationResponse, catalogResponse] = await Promise.all([fetch('/api/personnel-certifications', { cache: 'no-store' }), fetch('/api/personnel-certifications/organization-personnel', { cache: 'no-store' }), fetch('/api/certification-roadmap-catalog', { cache: 'no-store' })]); if (!personnelResponse.ok || !organizationResponse.ok) throw new Error('Certification data unavailable'); personnelCertifications = (await personnelResponse.json()).map(row => ({ ...row, status: row.status || 'Planned' })); organizationPersonnel = await organizationResponse.json(); certificationRoadmapCatalog = catalogResponse.ok ? await catalogResponse.json() : []; renderCertificationCatalogOptions(); certificationReferenceLoaded = false; renderCertificationPersonnelOptions(); renderCertifications(); renderOrganizationPersonnelStructure(); }
async function saveCertification(event) {
  event.preventDefault();
  if (!$('certificationForm').reportValidity()) return;
  const id = $('certificationId').value;
  try {
    const response = await fetch(id ? `/api/personnel-certifications/${id}` : '/api/personnel-certifications', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(certificationData()) });
    if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Sertifikasi gagal disimpan');
    $('certificationModal').close();
    await loadCertifications();
    $('personnelWorkflowStatus').textContent = id ? 'Sertifikasi diperbarui.' : 'Sertifikasi tersimpan. Anda dapat menambahkan sertifikasi lain untuk pegawai yang sama.';
  } catch (error) { $('certificationStatus').textContent = error.message; }
}
function resetOrganizationPersonnelForm() { $('organizationPersonnelForm').reset(); $('organizationPersonnelId').value = ''; $('organizationPersonnelFormMode').textContent = 'PEGAWAI BARU'; $('organizationPersonnelFormTitle').textContent = 'Tambah pegawai'; $('organizationPersonnelStatus').textContent = 'Ready'; }
function openOrganizationPersonnelForm(person = null) { resetOrganizationPersonnelForm(); if (person) { $('organizationPersonnelId').value = person.id; $('organizationPersonnelName').value = person.personnelName || ''; $('organizationPersonnelEmployeeId').value = person.employeeId || ''; $('organizationPersonnelRole').value = person.personnelRole || ''; $('organizationPersonnelSupervisor').value = person.supervisorName || ''; $('organizationPersonnelFormMode').textContent = 'EDIT PEGAWAI'; $('organizationPersonnelFormTitle').textContent = `Edit ${person.personnelName}`; } $('organizationPersonnelModal').showModal(); }
async function saveOrganizationPersonnel(event) {
  event.preventDefault();
  const id = $('organizationPersonnelId').value;
  const data = { personnelName: $('organizationPersonnelName').value.trim(), employeeId: $('organizationPersonnelEmployeeId').value.trim(), personnelRole: $('organizationPersonnelRole').value.trim(), supervisorName: $('organizationPersonnelSupervisor').value.trim() };
  try {
    const response = await fetch(id ? `/api/personnel-certifications/organization-personnel/${id}` : '/api/personnel-certifications/organization-personnel', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) });
    if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Pegawai gagal disimpan');
    $('organizationPersonnelModal').close();
    await loadCertifications();
    $('personnelWorkflowStatus').textContent = id ? 'Data pegawai diperbarui.' : 'Pegawai terdaftar. Pilih Tambah sertifikasi pada daftar pegawai untuk melanjutkan.';
  } catch (error) { $('organizationPersonnelStatus').textContent = error.message; }
}
async function deleteOrganizationPersonnel(id) {
  if (!confirm('Hapus pegawai? Pegawai yang masih memiliki sertifikasi harus dipindahkan atau dihapus sertifikasinya terlebih dahulu.')) return;
  try {
    const response = await fetch(`/api/personnel-certifications/organization-personnel/${id}`, { method: 'DELETE' });
    if (!response.ok) throw new Error((await response.json().catch(() => ({}))).error || 'Pegawai gagal dihapus');
    await loadCertifications();
    $('personnelWorkflowStatus').textContent = 'Pegawai dihapus.';
  } catch (error) { $('personnelWorkflowStatus').textContent = error.message; }
}
async function deleteCertification(id) { if (!confirm('Delete this personnel certification?')) return; const response = await fetch(`/api/personnel-certifications/${id}`, { method: 'DELETE' }); if (response.ok) await loadCertifications(); }
document.querySelector('#certificationDelete').addEventListener('click', async () => { const id = $('certificationId').value; if (!id) return; await deleteCertification(id); resetCertificationForm(); $('certificationModal').close(); });
async function addCertificationToCanvas(id) { const row = personnelCertifications.find(item => String(item.id) === String(id)); if (!row) return; const sameLevel = personnelCertifications.filter(item => item.certificationLevel === row.certificationLevel); const layout = { positionX: 24 + (sameLevel.length - 1) % 4 * 285, positionY: 18 + Math.floor((sameLevel.length - 1) / 4) * 205, cardWidth: row.cardWidth || 260, cardHeight: row.cardHeight || 190 }; const response = await fetch(`/api/personnel-certifications/${row.id}/layout`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(layout) }); if (response.ok) { Object.assign(row, layout, { onCanvas: true }); renderCertifications(); $('certificationStatus').textContent = 'Personnel record added to canvas'; } }
async function saveCertificationLayout(card, targetCanvas, targetLevel) { const row = personnelCertifications.find(item => String(item.id) === card.dataset.certificationId); if (!row || !currentUserPermissions.includes('personnel-certification')) return; const canvasRect = targetCanvas.getBoundingClientRect(); const cardRect = card.getBoundingClientRect(); const data = { certificationLevel: targetLevel, positionX: Math.max(0, Math.round(cardRect.left - canvasRect.left)), positionY: Math.max(0, Math.round(cardRect.top - canvasRect.top)), cardWidth: Math.round(card.offsetWidth), cardHeight: Math.round(card.offsetHeight) }; const response = await fetch(`/api/personnel-certifications/${row.id}/layout`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (response.ok) { Object.assign(row, data); resizeCertificationCanvases(); } }
function enableCertificationBoard() { const board = $('certificationBoard'); if (!board || board.dataset.bound) return; board.dataset.bound = 'true'; let interaction = null; board.addEventListener('pointerdown', event => { if (!currentUserPermissions.includes('personnel-certification')) return; const card = event.target.closest('.certification-card'); if (!card || event.target.closest('button')) return; const resize = event.target.closest('.resize-handle'); interaction = { card, resize, startX: event.clientX, startY: event.clientY, left: parseFloat(card.style.left) || 0, top: parseFloat(card.style.top) || 0, width: card.offsetWidth, height: card.offsetHeight }; card.setPointerCapture(event.pointerId); event.preventDefault(); }); board.addEventListener('pointermove', event => { if (!interaction) return; const deltaX = event.clientX - interaction.startX; const deltaY = event.clientY - interaction.startY; if (interaction.resize) { interaction.card.style.width = `${Math.max(145, interaction.width + deltaX)}px`; interaction.card.style.height = `${Math.max(62, interaction.height + deltaY)}px`; } else { interaction.card.style.left = `${Math.max(0, interaction.left + deltaX)}px`; interaction.card.style.top = `${interaction.top + deltaY}px`; } }); board.addEventListener('pointerup', async event => { if (!interaction) return; const current = interaction; interaction = null; suppressCertificationCardClick = Math.hypot(event.clientX - current.startX, event.clientY - current.startY) > 5; if (suppressCertificationCardClick) window.setTimeout(() => { suppressCertificationCardClick = false; }, 0); current.card.releasePointerCapture(event.pointerId); const lane = [...board.querySelectorAll('.certification-lane')].find(item => { const rect = item.getBoundingClientRect(); return event.clientY >= rect.top && event.clientY <= rect.bottom; }); const targetCanvas = lane?.querySelector('.certification-lane-canvas') || current.card.parentElement; const targetLevel = lane ? certificationLevels[[...board.querySelectorAll('.certification-lane')].indexOf(lane)] : certificationLevels.find(level => level === current.card.closest('.certification-lane')?.querySelector('h4')?.textContent) || 'Intermediate'; await saveCertificationLayout(current.card, targetCanvas, targetLevel); if (lane && lane !== current.card.closest('.certification-lane')) renderCertifications(); }); }
async function resetRiskRegister() { if (!riskManagementRows.length) return; if (!confirm('Reset Risk Register? Semua risiko dan opsi dropdown akan dihapus permanen.')) return; if (!confirm('Konfirmasi terakhir: mulai Risk Register dari kosong?')) return; const response = await fetch('/api/risk-management', { method: 'DELETE' }); if (!response.ok) { $('riskRegisterStatus').textContent = 'Reset failed'; return; } resetRiskManagementForm(); await loadRiskManagement(); $('riskRegisterStatus').textContent = 'Risk Register reset'; }
$('riskManagementNewButton').addEventListener('click', openRiskManagementModal);
$('riskRegisterCancel').addEventListener('click', () => $('riskManagementModal').close());
$('riskRegisterResetButton').addEventListener('click', resetRiskRegister);
$('riskRegisterExportButton').addEventListener('click', exportRiskRegister); $('riskRegisterTemplateButton').addEventListener('click', downloadRiskImportExample); $('riskRegisterImportInput').addEventListener('change', event => { const [file] = event.target.files; if (file) importRiskRegister(file); });
function resetRiskIndicatorForm() { $('riskIndicatorForm').reset(); $('riskIndicatorId').value = ''; $('riskIndicatorForm').hidden = true; }
function fillRiskIndicatorForm(row) { $('riskIndicatorId').value = row.id; $('riskIndicatorType').value = row.indicator_type; $('riskIndicatorScore').value = row.score ?? ''; $('riskIndicatorLabel').value = row.label; $('riskIndicatorSort').value = row.sort_order; $('riskIndicatorDescription').value = row.description; $('riskIndicatorForm').hidden = false; }
async function saveRiskIndicator(event) { event.preventDefault(); const id = $('riskIndicatorId').value; const data = { indicatorType: $('riskIndicatorType').value, score: $('riskIndicatorScore').value, label: $('riskIndicatorLabel').value, sortOrder: $('riskIndicatorSort').value, description: $('riskIndicatorDescription').value }; const response = await fetch(id ? `/api/risk-management/indicators/${id}` : '/api/risk-management/indicators', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(data) }); if (response.ok) { resetRiskIndicatorForm(); await loadRiskManagement(); } }
async function deleteRiskIndicator(id) { if (!confirm('Delete this indicator?')) return; const response = await fetch(`/api/risk-management/indicators/${id}`, { method: 'DELETE' }); if (response.ok) await loadRiskManagement(); }

