async function resetFramework(framework) { const isPrivacy = framework === 'privacy'; const label = isPrivacy ? 'Privacy' : 'CSF'; if (!confirm(`Reset ${label} assessment? Progress, notes, dan referensi evidence ${label} akan dihapus.`)) return; $('saveState').textContent = `Menghapus assessment ${label}...`; try { const empty = { scores: {}, policyScores: {}, practiceScores: {}, notes: {}, attachments: {} }; const response = await fetch(isPrivacy ? '/api/privacy/assessment/reset' : '/api/assessment/reset', { method: 'POST' }); if (!response.ok) throw new Error('Server reset gagal'); if (isPrivacy) { privacyState = empty; renderPrivacy(); if ($('privacyAssessmentView').classList.contains('active-view')) renderPrivacyAssessment($('privacyAssessmentTitle').textContent); } else { state = empty; renderOverview(); renderCsfTable(); if ($('assessmentView').classList.contains('active-view')) renderControls(); } renderUploadedFiles(); $('saveState').textContent = `${label} assessment berhasil direset`; } catch (error) { $('saveState').textContent = `Reset gagal: ${error.message}`; } }
async function resetIso27001Assessment() { if (!confirm('Reset ISO 27001 assessment? Semua evidence upload, isi assessment, dan sasaran keamanan akan dihapus. Data kontrol standar tetap dipertahankan.')) return; $('saveState').textContent = 'Menghapus assessment ISO 27001...'; try { const response = await fetch('/api/frameworks/iso27001/assessment/reset', { method: 'POST' }); if (!response.ok) throw new Error('Server reset gagal'); await Promise.all([loadIso27001Data(), loadIso27001SoaData(), loadIsoObjectives()]); renderUploadedFiles(); $('saveState').textContent = 'ISO 27001 assessment berhasil direset'; } catch (error) { $('saveState').textContent = `Reset gagal: ${error.message}`; } }
renderOverview(); renderCsfTable(); renderUploadedFiles();
const storedUploadFolderName = localStorage.getItem(uploadFolderStorageKey); if (storedUploadFolderName) syncUploadFolderStatus(`Folder: ${storedUploadFolderName}`);
restoreUploadDirectoryHandle().then(restored => { if (!restored && storedUploadFolderName) syncUploadFolderStatus(`Folder: ${storedUploadFolderName} - izin diperlukan`); });
$('startButton').addEventListener('click', () => { const target = $('csfTableBody').closest('.excel-wrap'); window.scrollTo({ top: target.getBoundingClientRect().top + window.scrollY - 24, behavior: 'auto' }); }); $('backButton').addEventListener('click', () => { document.querySelectorAll('.view').forEach(view => view.classList.remove('active-view')); $('csfView').classList.add('active-view'); saveUiState('csf'); document.querySelectorAll('.nav-item').forEach(item => item.classList.remove('active')); }); $('csfResetButton').remove(); $('csfTopResetButton').addEventListener('click', () => resetFramework('csf')); $('privacyResetButton').addEventListener('click', () => resetFramework('privacy')); $('searchInput').addEventListener('input', renderControls); $('statusFilter').addEventListener('change', renderControls);
$('iso27001ResetButton').addEventListener('click', resetIso27001Assessment);
loadPolicyRegisterRows().catch(() => {});
const uploadedFileSourceLabel = record => ({ csf: 'NIST CSF 2.0', privacy: 'Privacy Framework', iso27001: 'ISO 27001:2022', 'iso27001-soa': 'SOA', 'policy-register': 'Policy Register' }[record?.sourceType] || 'Assessment');
