<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<aside v-pre class="sidebar">
        <button class="sidebar-toggle" id="sidebarToggle" type="button" aria-label="Minimize sidebar" title="Minimize sidebar"><span>&lt;</span></button>
        <section class="sidebar-group" id="assessmentNavGroup">
          <button class="sidebar-group-toggle" id="assessmentNavToggle" type="button" aria-controls="assessmentNav" aria-expanded="true"><span>Assessment map</span><span class="sidebar-group-chevron" aria-hidden="true">v</span></button>
          <div class="sidebar-group-items" id="assessmentNav">
            <button class="nav-item active" data-view="framework" type="button" title="Choose framework" aria-label="Choose framework"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="3" y="3" width="7" height="7" rx="1.5"/><rect x="14" y="3" width="7" height="7" rx="1.5"/><rect x="3" y="14" width="7" height="7" rx="1.5"/><rect x="14" y="14" width="7" height="7" rx="1.5"/></svg></span><span>Choose framework</span></button>
            <button class="nav-item" data-view="risk-acceptance" type="button" title="Risk Acceptance" aria-label="Risk Acceptance"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 12 3 3 5-6"/></svg></span><span>Risk Acceptance</span></button>
            <button class="nav-item" data-view="risk-management" type="button" title="Risk Management" aria-label="Risk Management"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 3v17h17M8 15v-4m5 4V7m5 8v-6"/></svg></span><span>Risk Management</span></button>
            <button class="nav-item" data-view="audit-finding-tracker" type="button" title="Audit Finding Tracker" aria-label="Audit Finding Tracker"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 12 3 3 5-6"/></svg></span><span>Audit Finding Tracker</span></button>
            <button class="nav-item" data-view="policy-register" type="button" title="Policy Register" aria-label="Policy Register"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H5v20h14V7l-5-5Z"/><path d="M14 2v6h5M8 12h8m-8 4h6"/></svg></span><span>Policy Register</span></button>
            <button class="nav-item" data-view="personnel-certification" type="button" title="Personnel Certification" aria-label="Personnel Certification"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><circle cx="9" cy="8" r="3"/><path d="M3 21v-3a6 6 0 0 1 12 0v3m1-16a3 3 0 0 1 0 6m3 10v-3a6 6 0 0 0-3-5"/></svg></span><span>Personnel Certification</span></button>
          </div>
        </section>
        <section class="sidebar-group" id="tprmNavGroup">
          <button class="sidebar-group-toggle" id="tprmNavToggle" type="button" aria-controls="tprmNav" aria-expanded="false"><span>TPRM</span><span class="sidebar-group-chevron" aria-hidden="true">v</span></button>
          <div class="sidebar-group-items" id="tprmNav">
            <button class="nav-item" data-view="tprm" type="button" title="TPRM Framework" aria-label="TPRM Framework"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Z"/><path d="m8 12 3 3 5-6"/></svg></span><span>TPRM Framework</span></button>
            <button class="nav-item" data-view="tprm-tiering" type="button" title="Vendor Tiering Matrix" aria-label="Vendor Tiering Matrix"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M4 3v17h17M8 15v-4m5 4V7m5 8v-6"/></svg></span><span>Vendor Tiering Matrix</span></button>
            <button class="nav-item" data-view="tprm-questionnaire" type="button" title="Due Diligence Questionnaire" aria-label="Due Diligence Questionnaire"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 12 3 3 5-6"/></svg></span><span>Due Diligence Questionnaire</span></button>
            <button class="nav-item" data-view="questionnaire-templates" type="button" title="Questionnaire Templates" aria-label="Questionnaire Templates"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H5v20h14V7l-5-5Z"/><path d="M14 2v6h5M8 12h8m-8 4h6"/></svg></span><span>Questionnaire Templates</span></button>
            <button class="nav-item" data-view="tprm-register" type="button" title="TPRM Risk Register" aria-label="TPRM Risk Register"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="m12 3 10 18H2L12 3Z"/><path d="M12 9v5m0 3v.1"/></svg></span><span>TPRM Risk Register</span></button>
          </div>
        </section>
        <section class="sidebar-group" id="frameworkNavGroup">
          <button class="sidebar-group-toggle" id="frameworkNavToggle" type="button" aria-controls="frameworkNav" aria-expanded="false"><span>Framework</span><span class="sidebar-group-chevron" aria-hidden="true">v</span></button>
          <div class="sidebar-group-items" id="frameworkNav">
            <button class="nav-item" data-view="csf" type="button" title="CSF 2.0" aria-label="CSF 2.0"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Z"/><path d="m8 12 3 3 5-6"/></svg></span><span>CSF 2.0</span></button>
            <button class="nav-item" data-view="privacy" type="button" title="Privacy Framework" aria-label="Privacy Framework"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/></svg></span><span>Privacy Framework</span></button>
            <button class="nav-item" data-view="iso27001" type="button" title="ISO 27001:2022" aria-label="ISO 27001:2022"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 12 3 3 5-6"/></svg></span><span>ISO 27001:2022</span></button>
            <button class="nav-item" data-view="iso27001-soa" type="button" hidden title="SOA (Statement of Applicability)" aria-label="SOA (Statement of Applicability)"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M14 2H5v20h14V7l-5-5Z"/><path d="M14 2v6h5M8 12h8m-8 4h6"/></svg></span><span>SOA (Statement of Applicability)</span></button>
            <button class="nav-item" data-view="privacy-manage" type="button" title="Manage Privacy" aria-label="Manage Privacy"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/></svg></span><span>Manage Privacy</span></button>
            <button class="nav-item" data-view="csf-manage" type="button" title="Manage CSF" aria-label="Manage CSF"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Z"/><path d="m8 12 3 3 5-6"/></svg></span><span>Manage CSF</span></button>
            <button class="nav-item" data-view="files" type="button" title="Uploaded files" aria-label="Uploaded files"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h7l2 2h9v12H3V6Z"/><path d="M3 6V4h6l2 2"/></svg></span><span>Uploaded files</span></button>
            <button class="nav-item" data-view="backups" type="button" title="Database Backup" aria-label="Database Backup"><span class="nav-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v14c0 4 16 4 16 0V5M4 12c0 4 16 4 16 0"/></svg></span><span>Database Backup</span></button>
          </div>
        </section>
        <div class="sidebar-footer">
          <div class="framework-note"><span class="status-dot"></span><div><strong>Framework</strong><small>NIST CSF 2.0</small></div></div>
          <small>Local workspace<br>v1.0 assessment</small>
        </div>
      </aside>
</template>
