<!-- Uses the existing workspace classes and static runtime contract. -->
<template>
<section v-pre id="auditFindingView" class="view">
  <div class="page-heading"><div><p class="eyebrow">CYBERSECURITY GOVERNANCE</p><h2>Audit Finding Tracker</h2><p class="lede">Kelola Audit → Finding → Follow-up → Evidence dalam satu alur penelusuran.</p></div><button id="aftNew" class="button button-accent" type="button">Tambah Audit</button></div>
  <div class="risk-dashboard-grid"><article class="stat-panel"><span class="stat-label">Audit</span><strong id="aftAuditCount">0</strong></article><article class="stat-panel"><span class="stat-label">Finding terbuka</span><strong id="aftOpenCount">0</strong></article><article class="stat-panel"><span class="stat-label">Follow-up</span><strong id="aftFollowupCount">0</strong></article><article class="stat-panel"><span class="stat-label">Evidence</span><strong id="aftEvidenceCount">0</strong></article></div>
  <div class="risk-summary-grid"><article class="stat-panel"><span class="stat-label">Audit lewat tenggat</span><strong id="aftOverdueAuditCount">0</strong><span class="stat-detail">Audit belum Closed dengan tenggat sebelum hari ini</span></article><article class="stat-panel"><span class="stat-label">Finding lewat tenggat</span><strong id="aftOverdueFindingCount">0</strong><span class="stat-detail">Finding belum Closed dengan tenggat sebelum hari ini</span></article></div>
  <details id="aftReminderPanel" class="insight-panel" hidden><summary>Pengaturan reminder finding / SMTP Admin</summary>
    <p id="aftReminderConnection" class="muted" role="status"></p>
    <button id="aftReminderSmtp" class="button button-quiet" type="button">Buka SMTP Admin</button>
    <form id="aftReminderForm" class="risk-register-form"><div class="risk-register-grid">
      <label><input id="aftReminderEnabled" type="checkbox"> Aktifkan reminder finding otomatis</label>
      <label>Ingatkan mulai H-<input id="aftReminderDays" type="number" min="0" max="365" value="7" required></label>
    </div><div class="risk-register-text-grid"><label>Email penerima (satu per baris)<textarea id="aftReminderRecipients" rows="4" placeholder="auditor@example.com&#10;pic.it@example.com&#10;manager@example.com" aria-describedby="aftReminderRecipientsHint"></textarea><small id="aftReminderRecipientsHint" class="muted">Contoh: masukkan auditor@example.com pada baris pertama, lalu tekan Enter untuk menambahkan pic.it@example.com pada baris berikutnya. Isi alamat email saja, tanpa nama, tanda koma, titik koma, atau format PIC = email. Ganti alamat contoh dengan email penerima sebenarnya.</small></label></div>
    <p class="muted">Semua penerima di atas menerima reminder setiap finding yang belum Closed, memiliki tenggat, dan masuk jadwal H- atau sudah terlambat. Diperiksa setiap jam selama server aktif; dikirim satu kali per finding, tenggat, dan penerima. Koneksi email mengikuti SMTP yang didaftarkan di Admin.</p>
    <article class="insight-panel"><h3>Contoh email yang diterima</h3><p class="muted">Contoh di bawah hanya ilustrasi. Email otomatis menggunakan data audit dan finding sebenarnya.</p><p><strong>Dari:</strong> alamat pengirim pada SMTP Admin<br><strong>Kepada:</strong> auditor@example.com (dikirim terpisah ke setiap penerima)<br><strong>Subjek:</strong> Reminder finding audit: Audit Keamanan Informasi</p><p><strong>Judul:</strong> Audit Keamanan Informasi<br><strong>Finding:</strong> Review akses belum selesai</p><p><strong>Deskripsi finding:</strong> Lakukan review akses pengguna dan lampirkan evidence persetujuan.<br><strong>PIC:</strong> Tim IT Security<br><strong>Status:</strong> Open<br><strong>Tenggat:</strong> 2026-12-31</p><p>Mohon tindak lanjuti finding melalui Audit Finding Tracker.</p><p class="muted">Contoh jadwal: H-7 dengan tenggat 31 Desember 2026 mulai memenuhi jadwal pengiriman pada 24 Desember 2026. Email dikirim pada pemeriksaan scheduler berikutnya, selama reminder aktif dan finding belum Closed.</p></article>
    <div class="csf-form-actions"><button id="aftReminderSave" class="button button-accent" type="submit">Simpan reminder</button><button id="aftReminderReload" class="button button-quiet" type="button">Muat ulang pengaturan</button></div></form>
    <div class="toolbar"><label>Email tujuan percobaan<input id="aftReminderTestTo" type="email" placeholder="nama.anda@example.com" aria-describedby="aftReminderTestHint"><small id="aftReminderTestHint" class="muted">Isi satu alamat email Anda untuk menerima email contoh melalui SMTP Admin. Tombol ini langsung mengirim email percobaan; penerima reminder otomatis tidak berubah.</small></label><button id="aftReminderTest" class="button button-quiet" type="button">Kirim email percobaan</button></div>
    <p id="aftReminderStatus" class="save-state" role="status" aria-live="polite"></p>
  </details>
  <nav id="aftBreadcrumb" class="risk-management-tabs" aria-label="Hierarki audit"></nav>
  <p id="aftContext" class="muted"></p>
  <div class="toolbar"><label class="search-box"><span>/</span><input id="aftSearch" type="search" placeholder="Cari data pada tingkat ini" aria-label="Cari audit finding"></label><select id="aftFilter" aria-label="Filter status"><option value="">Semua status</option><option>Open</option><option>In progress</option><option>Closed</option></select><button id="aftRefresh" class="button button-quiet" type="button">Muat ulang</button></div>
  <p id="aftStatus" class="save-state" role="status" aria-live="polite"></p>
  <div class="excel-wrap"><table class="excel-table"><thead><tr><th>Judul / Referensi</th><th>PIC</th><th>Status</th><th>Tenggat</th><th>Detail</th><th>Aksi</th></tr></thead><tbody id="aftBody"></tbody></table></div>
  <dialog id="aftModal" class="certification-modal"><form id="aftForm" class="risk-register-form"><div class="section-heading compact"><h3 id="aftFormTitle">Tambah Audit</h3></div><div class="risk-register-grid">
    <label>Judul<input name="title" required maxlength="200"></label><label>Referensi<input name="reference" maxlength="100"></label><label>PIC<input name="owner" maxlength="160"></label><label>Status<select name="status"><option>Open</option><option>In progress</option><option>Closed</option></select></label><label>Tenggat<input name="dueDate" type="date"></label><label id="aftSeverityLabel">Severity<select name="severity"><option>Low</option><option selected>Medium</option><option>High</option><option>Critical</option></select></label>
  </div><div class="risk-register-text-grid"><label>Deskripsi / rekomendasi / hasil tindak lanjut<textarea name="description" rows="4" maxlength="10000"></textarea></label><label id="aftFileLabel">File evidence (maksimum 10 MB)<input name="file" type="file"><small class="muted">Saat mengubah data, kosongkan untuk mempertahankan file.</small></label></div><p id="aftFormStatus" role="status" aria-live="polite"></p><div class="csf-form-actions"><button id="aftSave" class="button button-accent" type="submit">Simpan</button><button id="aftCancel" class="button button-quiet" type="button">Tutup</button></div></form></dialog>
</section>
</template>
