<!-- Uses the existing workspace classes and static runtime contract. -->
<template>
<section v-pre id="auditFindingView" class="view">
  <div class="page-heading"><div><p class="eyebrow">CYBERSECURITY GOVERNANCE</p><h2>Audit Finding Tracker</h2><p class="lede">Kelola Audit → Finding → Follow-up → Evidence dalam satu alur penelusuran.</p></div></div>
  <div class="risk-management-tabs" role="tablist" aria-label="Audit Finding Tracker">
    <button id="aftDashboardTab" class="button button-accent" type="button" role="tab" data-aft-tab="dashboard" aria-controls="aftDashboardPanel" aria-selected="true">1. Dashboard</button>
    <button id="aftSmtpTab" class="button button-quiet" type="button" role="tab" data-aft-tab="smtp" aria-controls="aftSmtpPanel" aria-selected="false" tabindex="-1">2. Setting SMTP</button>
    <button id="aftManageTab" class="button button-quiet" type="button" role="tab" data-aft-tab="manage" aria-controls="aftManagePanel" aria-selected="false" tabindex="-1">3. Kelola Audit</button>
  </div>
  <p id="aftStatus" class="save-state" role="status" aria-live="polite"></p>
  <div id="aftDashboardPanel" role="tabpanel" aria-labelledby="aftDashboardTab">
  <div class="risk-dashboard-grid"><article class="stat-panel" role="button" tabindex="0" data-aft-card="audits" aria-controls="aftManagePanel" title="Klik untuk melihat data" style="cursor:pointer"><span class="stat-label">Jenis audit</span><strong id="aftAuditCount">0</strong><span class="stat-detail">tercatat dalam tracker</span></article><article class="stat-panel" role="button" tabindex="0" data-aft-card="open-findings" aria-controls="aftManagePanel" title="Klik untuk melihat data" style="cursor:pointer"><span class="stat-label">Finding terbuka</span><strong id="aftOpenCount">0</strong><span class="stat-detail">masih perlu tindak lanjut</span></article><article class="stat-panel" role="button" tabindex="0" data-aft-card="overdue-findings" aria-controls="aftManagePanel" title="Klik untuk melihat data" style="cursor:pointer"><span class="stat-label">Lewat tenggat</span><strong id="aftOverdueFindingCount">0</strong><span class="stat-detail">finding membutuhkan perhatian</span></article><article class="stat-panel" role="button" tabindex="0" data-aft-card="closed-findings" aria-controls="aftManagePanel" title="Klik untuk melihat data" style="cursor:pointer"><span class="stat-label">Finding selesai</span><strong id="aftClosedFindingCount">0</strong><span class="stat-detail" id="aftResolutionRate">0% penyelesaian</span></article></div>
  <div class="risk-summary-grid"><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">STATUS FINDING</p><h3>Prioritas saat ini</h3></div></div><div id="aftFindingSummary" class="risk-summary-list"></div></article><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">REMINDER</p><h3>Aturan pengiriman</h3></div></div><p class="muted">Reminder hanya berdasarkan jenis audit dan finding. Follow-up serta Evidence tidak memicu email.</p><button class="button button-quiet" type="button" data-aft-tab="smtp">Buka pengaturan reminder</button></article><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">AKSI CEPAT</p><h3>Kelola pekerjaan</h3></div></div><p class="muted">Buka daftar audit untuk menambah atau memperbarui finding.</p><button id="aftDashboardManageInline" class="button button-accent" type="button">Kelola Audit</button></article></div>
  <div class="csf-form-actions"><button id="aftDashboardManage" class="button button-accent" type="button">Kelola Audit dan Finding</button><button id="aftDashboardRefresh" class="button button-quiet" type="button">Muat ulang ringkasan</button></div>
  </div>
  <div id="aftSmtpPanel" role="tabpanel" aria-labelledby="aftSmtpTab" hidden>
  <p id="aftReminderAccess" class="muted" hidden>Pengaturan SMTP dan reminder hanya dapat dikelola oleh Admin. Hubungi Admin untuk mengatur penerima dan jadwal reminder Finding.</p>
  <section id="aftReminderPanel" class="insight-panel" hidden><h3>Reminder berdasarkan jenis audit dan finding</h3>
    <p id="aftReminderConnection" class="muted" role="status"></p>
    <button id="aftReminderSmtp" class="button button-quiet" type="button">Buka SMTP Admin</button>
    <form id="aftReminderForm" class="risk-register-form"><div class="risk-register-grid">
      <label><input id="aftReminderEnabled" type="checkbox"> Aktifkan reminder finding otomatis</label>
      <label>Ingatkan mulai H-<input id="aftReminderDays" type="number" min="0" max="365" value="7" required></label>
    </div><div class="risk-register-text-grid"><label>Email penerima (satu per baris)<textarea id="aftReminderRecipients" rows="4" placeholder="auditor@example.com&#10;pic.it@example.com&#10;manager@example.com" aria-describedby="aftReminderRecipientsHint"></textarea><small id="aftReminderRecipientsHint" class="muted">Contoh: masukkan auditor@example.com pada baris pertama, lalu tekan Enter untuk menambahkan pic.it@example.com pada baris berikutnya. Isi alamat email saja, tanpa nama, tanda koma, titik koma, atau format PIC = email. Ganti alamat contoh dengan email penerima sebenarnya.</small></label></div>
    <p class="muted">Email berisi jenis audit dan finding. Reminder dikirim untuk finding yang belum Closed, memiliki tenggat, dan telah masuk jadwal H- atau terlambat. Follow-up dan Evidence tidak digunakan sebagai pemicu. Koneksi email mengikuti SMTP Admin.</p>
    <article class="insight-panel"><h3>Contoh email</h3><p><strong>Subjek:</strong> Reminder finding — Audit Keamanan Informasi: Review akses belum selesai</p><p><strong>Jenis audit:</strong> Audit Keamanan Informasi<br><strong>Finding:</strong> Review akses belum selesai<br><strong>Status:</strong> Open<br><strong>Tenggat finding:</strong> 2026-12-31</p></article>
    <div class="csf-form-actions"><button id="aftReminderSave" class="button button-accent" type="submit">Simpan reminder</button><button id="aftReminderReload" class="button button-quiet" type="button">Muat ulang pengaturan</button></div></form>
    <div class="toolbar"><label>Email tujuan percobaan<input id="aftReminderTestTo" type="email" placeholder="nama.anda@example.com" aria-describedby="aftReminderTestHint"><small id="aftReminderTestHint" class="muted">Isi satu alamat email Anda untuk menerima email contoh melalui SMTP Admin. Tombol ini langsung mengirim email percobaan; penerima reminder otomatis tidak berubah.</small></label><button id="aftReminderTest" class="button button-quiet" type="button">Kirim email percobaan</button></div>
    <p id="aftReminderStatus" class="save-state" role="status" aria-live="polite"></p>
  </section>
  </div>
  <div id="aftManagePanel" role="tabpanel" aria-labelledby="aftManageTab" hidden>
  <div class="section-heading"><div><h3>Kelola Audit</h3><p class="muted">Pilih Audit, lalu kelola Finding, Follow-up, dan Evidence.</p></div><button id="aftNew" class="button button-accent" type="button">Tambah Audit</button></div>
  <nav id="aftBreadcrumb" class="risk-management-tabs" aria-label="Hierarki audit"></nav>
  <p id="aftContext" class="muted"></p>
  <div class="toolbar"><label class="search-box"><span>/</span><input id="aftSearch" type="search" placeholder="Cari data pada tingkat ini" aria-label="Cari audit finding"></label><select id="aftFilter" aria-label="Filter status"><option value="">Semua status</option><option>Open</option><option>In progress</option><option>Closed</option></select><button id="aftRefresh" class="button button-quiet" type="button">Muat ulang</button></div>
  
  <div class="excel-wrap"><table class="excel-table"><thead><tr><th>Judul / Referensi</th><th>PIC</th><th>Status</th><th>Tenggat</th><th>Detail</th><th>Aksi</th></tr></thead><tbody id="aftBody"></tbody></table></div>
  </div>
  <dialog id="aftModal" class="certification-modal"><form id="aftForm" class="risk-register-form"><div class="section-heading compact"><h3 id="aftFormTitle">Tambah Audit</h3></div><div class="risk-register-grid">
    <label>Judul<input name="title" required maxlength="200"></label><label>Referensi<input name="reference" maxlength="100"></label><label>PIC<input name="owner" maxlength="160"></label><label>Status<select name="status"><option>Open</option><option>In progress</option><option>Closed</option></select></label><label>Tenggat<input name="dueDate" type="date"></label><label id="aftSeverityLabel">Severity<select name="severity"><option>Low</option><option selected>Medium</option><option>High</option><option>Critical</option></select></label>
  </div><div class="risk-register-text-grid"><label>Deskripsi / rekomendasi / hasil tindak lanjut<textarea name="description" rows="4" maxlength="10000"></textarea></label><label id="aftFileLabel">File evidence (maksimum 10 MB)<input name="file" type="file"><small class="muted">Saat mengubah data, kosongkan untuk mempertahankan file.</small></label></div><p id="aftFormStatus" role="status" aria-live="polite"></p><div class="csf-form-actions"><button id="aftSave" class="button button-accent" type="submit">Simpan</button><button id="aftCancel" class="button button-quiet" type="button">Tutup</button></div></form></dialog>
</section>
</template>
