<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="csfView" class="view">
          <div class="risk-management-tabs"><button class="button button-accent" type="button" data-csf-tab="overview">CSF overview</button><button class="button button-quiet" type="button" data-csf-tab="core">CSF 2.0 Core</button></div>
          <div class="page-heading"><div><p class="eyebrow">MATURITY SNAPSHOT</p><h2>CSF 2.0 Control Room</h2><p class="lede">Overview dan assessment NIST Cybersecurity Framework 2.0 dalam satu halaman.</p></div><div class="csf-actions"><button class="button button-accent" id="startButton" type="button">Mulai assessment <span aria-hidden="true">&rarr;</span></button><button class="button button-dark" id="csfTopResetButton" type="button">Reset CSF assessment</button></div></div>
          <div class="hero-grid"><article class="score-panel"><div class="panel-kicker">Overall maturity</div><div class="score-line"><strong id="overallScore">0.0</strong><span>/ 5.0</span></div><p id="overallLabel">Not assessed</p><div class="meter"><span id="overallMeter"></span></div><div class="score-foot"><span>0 Initial</span><span>5 Optimized</span></div></article><article class="stat-panel"><span class="stat-label">Completion</span><strong id="completionValue">0%</strong><span class="stat-detail" id="completionDetail">0 of 24 controls scored</span><div class="mini-ring" id="completionRing"></div></article><article class="stat-panel"><span class="stat-label">Priority gaps</span><strong id="gapValue">24</strong><span class="stat-detail">controls below target level 3</span><div class="gap-bars"><i></i><i></i><i></i><i></i><i></i></div></article></div>
          <div class="section-heading"><div><p class="eyebrow">FRAMEWORK COVERAGE</p><h3>NIST CSF 2.0</h3></div><span class="target-chip">Target maturity <b>3.0</b></span></div><div class="function-cards" id="functionCards"></div>
          <div class="section-heading"><div><p class="eyebrow">NIST CSF SUMMARY</p><h3>Category maturity</h3></div><span class="muted">Policy and Practice average by Category</span></div><div class="excel-wrap summary-wrap"><table class="excel-table summary-table"><thead><tr><th>Function</th><th>Category</th><th># Controls</th><th>Target Score</th><th>Policy Maturity</th><th>Practice Maturity</th></tr></thead><tbody id="csfSummaryBody"></tbody></table></div>
          <div class="section-heading radar-heading"><div><p class="eyebrow">CATEGORY MATURITY PROFILE</p><h3>Policy and practice by category</h3></div><span class="muted">Average of subcategories · Scale 0 to 4</span></div><article class="radar-panel"><div class="radar-chart-wrap"><canvas id="maturityRadar" width="700" height="430" aria-label="Spider diagram NIST CSF Summary"></canvas><div class="radar-tooltip" id="radarTooltip"></div></div><div class="radar-legend"><button type="button" class="radar-series active" data-series="policy"><i class="legend-policy"></i>Policy Score</button><button type="button" class="radar-series active" data-series="practice"><i class="legend-practice"></i>Practice Score</button><button type="button" class="radar-series active" data-series="target"><i class="legend-target"></i>Target Score</button></div></article><div class="lower-grid"><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">NEXT MOVES</p><h3>Recommended focus</h3></div><span class="muted">Based on lowest scores</span></div><div id="recommendations"></div></article><article class="legend-panel"><p class="eyebrow">MATURITY SCALE</p><h3>What the levels mean</h3><div class="legend-list"><div><b>0</b><span><strong>Incomplete</strong><small>Practice is absent or unknown.</small></span></div><div><b>1</b><span><strong>Initial</strong><small>Ad hoc and reactive practices.</small></span></div><div><b>2</b><span><strong>Developing</strong><small>Practices exist but vary.</small></span></div><div><b>3</b><span><strong>Defined</strong><small>Documented and repeatable.</small></span></div><div><b>4</b><span><strong>Adaptive</strong><small>Continuously improving.</small></span></div></div></article></div>
          <div class="page-heading"><div><p class="eyebrow">NIST CYBERSECURITY FRAMEWORK</p><h2>CSF 2.0 Core</h2><p class="lede">Spreadsheet view of functions, categories, subcategories, references, and maturity scoring.</p></div><div class="csf-actions"><button class="button button-quiet" id="addCsfButton" type="button">Add CSF control</button><button class="button button-accent" id="csfAssessmentButton" type="button">Open assessment <span aria-hidden="true">&rarr;</span></button><button class="button button-dark" id="csfResetButton" type="button">Reset CSF assessment</button></div></div>
          <dialog id="csfControlModal" class="certification-modal"><form id="csfControlModalForm" class="risk-register-form"><input id="csfControlModalOriginalId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow" id="csfControlModalMode">NEW CONTROL</p><h3 id="csfControlModalTitle">Create CSF control</h3></div><span class="save-state" id="csfControlModalStatus">Ready</span></div><div class="csf-form-grid"><label>Control ID<input id="csfControlModalId" required placeholder="GV.OC-01"></label><label>Function<input id="csfControlModalFunction" required placeholder="Govern"></label><label>Category<input id="csfControlModalCategory" required></label><label>Subcategory<input id="csfControlModalSubcategory" required></label><label>Implementation examples<textarea id="csfControlModalImplementation" rows="3"></textarea></label><label>Informative references<textarea id="csfControlModalReferences" rows="3"></textarea></label></div><div class="csf-form-actions"><button class="button button-accent" type="submit" id="csfControlModalSubmit">Create control</button><button class="button button-quiet" type="button" id="csfControlModalCancel">Close</button></div></form></dialog>
          <div class="toolbar"><label class="search-box"><span>/</span><input id="csfSearchInput" type="search" placeholder="Search CSF core..." autocomplete="off"></label><select id="csfFunctionFilter" aria-label="Filter function"><option value="all">All functions</option><option value="GV">Govern</option><option value="ID">Identify</option><option value="PR">Protect</option><option value="DE">Detect</option><option value="RS">Respond</option><option value="RC">Recover</option></select><select id="csfSort" aria-label="Sort CSF controls ascending"><option value="id">Sort: Control ID (A-Z)</option><option value="function">Sort: Function (A-Z)</option><option value="category">Sort: Category (A-Z)</option><option value="subcategory">Sort: Subcategory (A-Z)</option></select></div>
          <div class="excel-wrap"><table class="excel-table"><thead><tr><th>Function</th><th>Category</th><th>Subcategory</th><th>Implementation examples</th><th>Informative references</th><th>Policy maturity</th><th>Policy score reasoning</th><th>Practice maturity</th><th>Practice score reasoning</th><th>Actions</th></tr></thead><tbody id="csfTableBody"></tbody></table><div class="assessment-pagination" id="csfCorePagination"></div></div>
        </section>
</template>
