<template>
<section v-pre id="fileBackupsView" class="view backup-page">
  <div class="page-heading backup-page-heading"><div><p class="eyebrow">BACKUP SYSTEM</p><h2>File Backup</h2><p class="lede">Cadangkan seluruh file yang telah diunggah, termasuk foto depan/belakang aset, foto rak, dan gambar Knowledge Notes dalam arsip ZIP.</p></div><div class="csf-actions backup-primary-action"><button class="button button-accent" id="fileBackupCreateButton" type="button">Create file backup</button><span class="file-count" id="fileBackupCount">0 backups</span></div></div>
  <p class="muted">Arsip mencakup file unggahan terdaftar beserta metadata. Pilih folder untuk backup bertahap; subfolder ikut dicadangkan. Batas ZIP 500 MB, hasil ekstraksi 2 GB, setiap file 500 MB. Buat juga Database Backup untuk data dan referensi lampiran.</p>
  <label>Folder untuk backup <select id="fileBackupFolder"><option value="">Semua folder</option></select></label>
  <label>Folder untuk restore <input id="fileBackupRestoreFolder" type="text" list="fileBackupFolderOptions" placeholder="Kosongkan untuk semua; contoh Policy/2026"><datalist id="fileBackupFolderOptions"></datalist></label>
  <p class="muted">Folder restore mengacu pada path di dalam arsip, termasuk subfolder. Anda bisa mengetik folder yang belum ada di aplikasi. Path asli dipertahankan di storage aktif; file di luar folder pilihan tidak diubah.</p>
  <div class="backup-restore-panel"><div><p class="eyebrow">RECOVERY CONTROL</p><h3>Restore files</h3><p class="muted">Pilih ZIP File Backup NIST Basis (maksimal 500 MB). File dengan path yang sama akan diganti; file lain tetap tersimpan. Restore menggunakan lokasi storage aktif. Pulihkan Database Backup terlebih dahulu jika data dan referensi lampiran juga perlu dipulihkan.</p></div><div class="backup-restore-actions"><label class="button button-quiet" for="fileBackupRestoreInput">Select backup file<input id="fileBackupRestoreInput" type="file" accept=".zip" hidden></label><span class="muted" id="fileBackupRestoreFileName">No file selected</span><button class="button button-danger" id="fileBackupRestoreButton" type="button" disabled>Restore selected backup</button></div></div>
  <div class="section-heading backup-archive-heading"><div><p class="eyebrow">BACKUP ARCHIVE</p><h3>Available file backups</h3><p class="muted" id="fileBackupStatus" role="status">Backup hanya dapat diakses administrator.</p></div></div>
  <div class="excel-wrap backup-archive-table"><table class="excel-table"><thead><tr><th>File</th><th>Created</th><th>Size</th><th>Actions</th></tr></thead><tbody id="fileBackupBody"></tbody></table></div>
</section>
</template>
