<template>
<section v-pre id="fileBackupsView" class="view backup-page">
  <div class="page-heading backup-page-heading"><div><p class="eyebrow">BACKUP SYSTEM</p><h2>File Backup</h2><p class="lede">Cadangkan seluruh file yang telah diunggah dalam arsip ZIP.</p></div><div class="csf-actions backup-primary-action"><button class="button button-accent" id="fileBackupCreateButton" type="button">Create file backup</button><span class="file-count" id="fileBackupCount">0 backups</span></div></div>
  <p class="muted">Arsip mencakup file unggahan dari penyimpanan lokal dan shared storage beserta manifest metadata. Struktur folder unggahan dipertahankan. Buat juga Database Backup untuk mencadangkan data dan referensi lampiran semua modul.</p>
  <div class="backup-restore-panel"><div><p class="eyebrow">RECOVERY CONTROL</p><h3>Restore files</h3><p class="muted">Pilih ZIP File Backup NIST Basis (maksimal 500 MB). File dengan path yang sama akan diganti; file lain tetap tersimpan. Restore menggunakan lokasi storage aktif. Pulihkan Database Backup terlebih dahulu jika data dan referensi lampiran juga perlu dipulihkan.</p></div><div class="backup-restore-actions"><label class="button button-quiet" for="fileBackupRestoreInput">Select backup file<input id="fileBackupRestoreInput" type="file" accept=".zip" hidden></label><span class="muted" id="fileBackupRestoreFileName">No file selected</span><button class="button button-danger" id="fileBackupRestoreButton" type="button" disabled>Restore selected backup</button></div></div>
  <div class="section-heading backup-archive-heading"><div><p class="eyebrow">BACKUP ARCHIVE</p><h3>Available file backups</h3><p class="muted" id="fileBackupStatus" role="status">Backup hanya dapat diakses administrator.</p></div></div>
  <div class="excel-wrap backup-archive-table"><table class="excel-table"><thead><tr><th>File</th><th>Created</th><th>Size</th><th>Actions</th></tr></thead><tbody id="fileBackupBody"></tbody></table></div>
</section>
</template>
