<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="frameworkView" class="view">
          <div class="workspace-breadcrumb"><span>Workspace</span><span aria-hidden="true">/</span><strong>Framework library</strong></div>
          <div class="framework-chooser-heading">
            <p class="eyebrow">ASSESSMENT WORKSPACE</p>
            <h2>A clearer view of your<br>security maturity.</h2>
            <p class="lede">Kelola assessment, identifikasi gap, dan dokumentasikan evidence dalam satu workspace.</p>
            <svg class="hero-emblem" viewBox="0 0 180 180" fill="none" aria-hidden="true"><circle cx="90" cy="90" r="77" stroke="#e2e8f0" stroke-dasharray="4 6"/><circle cx="90" cy="90" r="57" fill="#eff6ff"/><path d="m90 50-30 12v27c0 24 30 40 30 40s30-16 30-40V62L90 50Z" fill="white" stroke="#2563eb" stroke-width="2"/><path d="m76 87 10 10 19-22" stroke="#2563eb" stroke-width="3" stroke-linecap="round" stroke-linejoin="round"/><circle cx="159" cy="55" r="5" fill="#93c5fd"/><circle cx="27" cy="130" r="4" fill="#cbd5e1"/></svg>
          </div>
          <div class="workspace-intro"><div><h3>Choose your framework</h3><p>Pilih kerangka kerja untuk memulai atau melanjutkan assessment.</p></div><span class="framework-badge">Framework library</span></div>
          <div class="framework-choices">
            <article class="framework-choice framework-choice-csf"><div class="choice-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M12 3 4 6v6c0 5 8 9 8 9s8-4 8-9V6l-8-3Z"/><path d="m8 12 3 3 5-6"/></svg></div><div class="choice-number">FRAMEWORK 01</div><p class="eyebrow">CYBERSECURITY</p><h3>NIST CSF 2.0</h3><p>Ukur maturity keamanan siber berdasarkan Function, Category, dan Subcategory pada NIST Cybersecurity Framework 2.0.</p><div class="choice-meta"><span>6 Functions</span><span>Policy + Practice</span></div><button class="button button-dark" id="chooseCsfButton" type="button">Open CSF 2.0 <span aria-hidden="true">&rarr;</span></button></article>
            <article class="framework-choice framework-choice-privacy"><div class="choice-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="10" width="16" height="11" rx="2"/><path d="M8 10V7a4 4 0 0 1 8 0v3m-4 5v2"/></svg></div><div class="choice-number">FRAMEWORK 02</div><p class="eyebrow">DATA PRIVACY</p><h3>NIST Privacy Framework</h3><p>Nilai pengelolaan risiko privasi berdasarkan Privacy Framework Core, lengkap dengan penilaian Policy dan Practice.</p><div class="choice-meta"><span>5 Functions</span><span>100 Controls</span></div><button class="button button-accent" id="choosePrivacyButton" type="button">Open Privacy Framework <span aria-hidden="true">&rarr;</span></button></article>
            <article class="framework-choice framework-choice-iso27001"><div class="choice-icon"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><rect x="4" y="3" width="16" height="18" rx="2"/><path d="m8 12 3 3 5-6"/></svg></div><div class="choice-number">FRAMEWORK 03</div><p class="eyebrow">INFORMATION SECURITY</p><h3>ISO 27001:2022</h3><p>Kelola assessment sertifikasi informasi berdasarkan Annex A clauses dan control objectives pada ISO 27001:2022.</p><div class="choice-meta"><span>Clauses A.5-A.8</span><span>SOA + control mapping</span></div><button class="button button-dark" id="chooseIso27001Button" type="button">Open ISO 27001:2022 <span aria-hidden="true">&rarr;</span></button></article>
          </div>
          <p class="workspace-help"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="M3 6h7l2 2h9v12H3V6Z"/><path d="M3 6V4h6l2 2"/></svg><span>Setiap assessment menghubungkan controls, catatan tindakan, dan evidence pendukung.</span></p>
        </section>
</template>
