<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="iso27001View" class="view">
          <div class="risk-management-tabs"><button class="button button-accent" type="button" data-iso-tab="dashboard">Dashboard ISO 27001:2022</button><button class="button button-quiet" type="button" data-iso-tab="objectives">Sasaran keamanan informasi</button><button class="button button-quiet" type="button" data-iso-tab="objective-calendar">Kalender evaluasi</button><button class="button button-quiet" type="button" data-iso-tab="clauses">Clauses 4-10</button><button class="button button-quiet" type="button" data-iso-tab="soa">SOA</button></div>
          <div id="iso27001DashboardPanel">
            <div class="page-heading"><div><p class="eyebrow">ISO 27001:2022</p><h2>Dashboard ISO 27001:2022</h2><p class="lede">Ringkasan kesiapan klausa, Annex A, dan sasaran keamanan informasi tahun berjalan.</p></div><div class="csf-actions"><label> Tahun<select id="isoDashboardYear"></select></label><button class="button button-dark" id="iso27001ResetButton" type="button">Reset ISO 27001 assessment</button></div></div>
            <div class="risk-dashboard-grid"><article class="stat-panel"><span>Clauses 4-10</span><strong id="isoDashboardClauses">0%</strong><small>Requirement dengan evidence</small></article><article class="stat-panel"><span>Annex A / SOA</span><strong id="isoDashboardSoa">0%</strong><small>Control yang applicable</small></article><article class="stat-panel"><span>Sasaran tahun berjalan</span><strong id="isoDashboardObjectives">0/0</strong><small>Sasaran tercapai</small></article><article class="stat-panel"><span>Pemantauan berisiko</span><strong id="isoDashboardAtRisk">0</strong><small>Periode perlu perhatian</small></article></div>
            <div class="iso-dashboard-chart-grid"><article class="iso-chart-panel"><div class="section-heading compact"><div><p class="eyebrow">CLAUSES 4-10</p><h3>Evidence per klausul</h3></div><span class="muted">Requirement terisi</span></div><div id="isoClauseChart" class="iso-bar-chart"></div></article><article class="iso-chart-panel"><div class="section-heading compact"><div><p class="eyebrow">ANNEX A / SOA</p><h3>Applicability control</h3></div><span class="muted">Status control</span></div><div id="isoSoaChart" class="iso-donut-layout"></div></article><article class="iso-chart-panel"><div class="section-heading compact"><div><p class="eyebrow">OBJECTIVES</p><h3>Status sasaran</h3></div><span class="muted">Periode evaluasi</span></div><div id="isoObjectiveStatusChart" class="iso-bar-chart"></div></article><article class="iso-chart-panel"><div class="section-heading compact"><div><p class="eyebrow">MONITORING PLAN</p><h3>Frekuensi evaluasi</h3></div><span class="muted">Tahun terpilih</span></div><div id="isoFrequencyChart" class="iso-bar-chart"></div></article></div>
            <div class="section-heading"><div><p class="eyebrow">MONITORING</p><h3>Ringkasan sasaran tahun berjalan</h3></div></div><div class="excel-wrap"><table class="excel-table"><thead><tr><th>Sasaran</th><th>PIC</th><th>Bulanan</th><th>Triwulan</th><th>Semester</th><th>Tahunan</th></tr></thead><tbody id="isoDashboardObjectiveBody"></tbody></table></div>
          </div>
          <div id="iso27001ObjectivesPanel" hidden>
            <div class="page-heading"><div><p class="eyebrow">INFORMATION SECURITY OBJECTIVES</p><h2>Sasaran keamanan informasi</h2><p class="lede">Tetapkan sasaran untuk setiap tahun dan pantau pencapaiannya secara berkala.</p></div><div class="csf-actions"><button class="button button-accent" id="isoObjectiveNewButton" type="button">Tambah sasaran</button><label>Tahun<select id="isoObjectiveYearFilter"></select></label></div></div>
            <dialog id="isoObjectiveModal" class="certification-modal"><form id="isoObjectiveForm" class="risk-register-form"><input id="isoObjectiveId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow" id="isoObjectiveFormMode">LANGKAH 1 - SASARAN BARU</p><h3 id="isoObjectiveFormTitle">Tentukan sasaran dan frekuensi evaluasi</h3></div><span class="save-state" id="isoObjectiveFormStatus">Ready</span></div><div class="risk-register-grid"><label>Tahun<input id="isoObjectiveFormYear" type="number" min="2000" max="2100" required></label><label>Sasaran<input id="isoObjectiveFormObjective" required></label><label>Indikator / KPI<input id="isoObjectiveFormIndicator"></label><label>Baseline<input id="isoObjectiveFormBaseline"></label><label>Target akhir tahun<input id="isoObjectiveFormTarget"></label><label>PIC / pemilik<input id="isoObjectiveFormOwner"></label><label>Dievaluasi per<select id="isoObjectiveFormFrequency"><option value="monthly">Bulanan (12 periode)</option><option value="quarterly">Triwulan (4 periode)</option><option value="semester">Semester (2 periode)</option><option value="annual">Tahunan (1 periode)</option></select></label><label>Catatan umum<textarea id="isoObjectiveFormNotes" rows="3"></textarea></label></div><div class="csf-form-actions"><button class="button button-accent" type="submit">Simpan sasaran</button><button class="button button-quiet" id="isoObjectiveFormCancel" type="button">Tutup</button></div></form></dialog>
            <div class="excel-wrap"><table class="excel-table"><thead><tr><th>Tahun</th><th>Sasaran / KPI</th><th>Frekuensi</th><th>Target akhir</th><th>PIC</th><th>Progress kalender</th><th>Aksi</th></tr></thead><tbody id="isoObjectivesBody"></tbody></table></div>
          </div>
          <div id="iso27001ObjectiveCalendarPanel" hidden>
            <div class="page-heading"><div><p class="eyebrow">EVALUATION CALENDAR</p><h2>Kalender evaluasi sasaran</h2><p class="lede">Daftar sasaran dari Tambah Sasaran dalam kalender Januari sampai Desember.</p></div><div class="csf-actions"><label>Tahun kalender<select id="isoObjectiveCalendarYear"></select></label><button class="button button-accent" id="isoObjectiveCalendarSave" type="button">Simpan kalender</button></div></div>
            <div id="isoObjectiveCalendarEmpty" class="empty-state">Tambahkan sasaran terlebih dahulu untuk mengisi kalender evaluasi.</div>
            <div id="isoObjectiveCalendarContent" hidden><div id="isoObjectiveCalendarForm" class="objective-calendar-table-wrap"></div></div>
          </div>
          <div id="iso27001ClausesPanel">
          <div class="page-heading"><div><p class="eyebrow">FRAMEWORK ADMINISTRATION</p><h2>ISO/IEC 27001:2022 Clauses 4-10</h2><p class="lede">Kelola requirement dan audit checklist dari sheet ISO 27001 Clauses 4-10.</p></div><div class="csf-actions"><button class="button button-accent" id="iso27001NewButton" type="button">New requirement</button><span class="file-count" id="iso27001Count">0 controls</span></div></div>
          <dialog id="iso27001Modal" class="certification-modal"><form id="iso27001Form" class="risk-register-form">
            <input id="iso27001OriginalId" type="hidden">
            <div class="section-heading compact"><div><p class="eyebrow" id="iso27001FormMode">NEW REQUIREMENT</p><h3 id="iso27001FormTitle">Create ISO 27001 requirement</h3></div><span class="muted">Checklist tersimpan di PostgreSQL</span></div>
            <div class="risk-register-grid"><label>Clause / Section<input id="iso27001FormId" required placeholder="4.1"></label><label>Clause<input id="iso27001FormFunction" required placeholder="Clause 4"></label><label>Category<input id="iso27001FormCategory" required value="ISO 27001 Clauses 4-10"></label><label>Requirement title<input id="iso27001FormSubcategory" required></label><label>Mandatory requirements & key deliverables<textarea id="iso27001FormImplementation" rows="4"></textarea></label><label>Auditor verification / expected questions<textarea id="iso27001FormReferences" rows="4"></textarea></label><label>Minimum Evidence Required<textarea id="iso27001FormMinimumEvidence" rows="4"></textarea></label></div>
            <div class="csf-form-actions"><button class="button button-accent" type="submit" id="iso27001FormSubmit">Create requirement</button><button class="button button-quiet" type="button" id="iso27001FormCancel">Close</button><span class="save-state" id="iso27001FormStatus">Ready</span></div>
          </form></dialog>
          <div class="section-heading"><div><p class="eyebrow">ISO 27001 REQUIREMENTS</p><h3>Clauses 4-10</h3></div><label class="search-box"><span>/</span><input id="iso27001Search" type="search" placeholder="Search ISO requirements..." autocomplete="off"></label></div><div class="toolbar"><select id="iso27001ClauseFilter" aria-label="Filter ISO 27001 clause"><option value="all">All clauses</option><option value="4">Clause 4</option><option value="5">Clause 5</option><option value="6">Clause 6</option><option value="7">Clause 7</option><option value="8">Clause 8</option><option value="9">Clause 9</option><option value="10">Clause 10</option></select><button class="button button-quiet" id="iso27001ClearFilters" type="button">Clear filters</button></div>
          <div class="excel-wrap"><table class="excel-table iso-evidence-table"><thead><tr><th>Clause</th><th>Requirement</th><th>Mandatory requirements &amp; key deliverables</th><th>Minimum Evidence Required</th><th>Evidence</th><th>Actions</th></tr></thead><tbody id="iso27001Body"></tbody></table><div class="assessment-pagination" id="iso27001Pagination"></div></div>
          </div>

        <div id="iso27001SoaPanel" hidden>
          <div class="page-heading"><div><p class="eyebrow">STATEMENT OF APPLICABILITY</p><h2>SOA (Statement of Applicability)</h2><p class="lede">Kelola 93 control ISO 27001:2022 Annex A dari workbook audit checklist.</p></div><div class="csf-actions"><button class="button button-accent" id="iso27001SoaNewButton" type="button">New control</button><span class="file-count" id="iso27001SoaCount">0 controls</span></div></div>
          <dialog id="iso27001SoaModal" class="certification-modal"><form id="iso27001SoaForm" class="risk-register-form">
            <input id="iso27001SoaOriginalId" type="hidden">
            <div class="section-heading compact"><div><p class="eyebrow" id="iso27001SoaFormMode">NEW CONTROL</p><h3 id="iso27001SoaFormTitle">Create SOA control</h3></div><span class="save-state" id="iso27001SoaFormStatus">Ready</span></div>
            <div class="risk-register-grid"><label>Control Ref<input id="iso27001SoaFormId" required placeholder="A.5.1"></label><label>Domain category<input id="iso27001SoaFormFunction" required placeholder="Organisational"></label><label>Category<input id="iso27001SoaFormCategory" required value="ISO 27001 Annex A Controls"></label><label>Control name<input id="iso27001SoaFormSubcategory" required></label><label>Applicability<select id="iso27001SoaFormApplicability"><option value="Applicable">Applicable</option><option value="Not applicable">Not applicable</option></select></label><label>Implementation requirements &amp; mandatory deliverables<textarea id="iso27001SoaFormImplementation" rows="4"></textarea></label><label>Auditor verification / expected questions<textarea id="iso27001SoaFormReferences" rows="4"></textarea></label><label>Minimum Evidence Required<textarea id="iso27001SoaFormMinimumEvidence" rows="4"></textarea></label></div>
            <div class="csf-form-actions"><button class="button button-accent" type="submit" id="iso27001SoaFormSubmit">Create control</button><button class="button button-quiet" type="button" id="iso27001SoaFormCancel">Close</button></div>
          </form></dialog>
          <div class="section-heading"><div><p class="eyebrow">ANNEX A CONTROLS</p><h3>Statement of Applicability</h3></div><label class="search-box"><span>/</span><input id="iso27001SoaSearch" type="search" placeholder="Search SOA controls..." autocomplete="off"></label></div><div class="toolbar"><select id="iso27001SoaDomainFilter" aria-label="Filter SOA domain"><option value="all">All domains</option><option>Organisational</option><option>People</option><option>Physical</option><option>Technological</option></select><button class="button button-quiet" id="iso27001SoaClearFilters" type="button">Clear filters</button></div>
          <div class="excel-wrap"><table class="excel-table iso-evidence-table"><thead><tr><th>Control Ref</th><th>Control Name</th><th>Applicability</th><th>Implementation requirements &amp; mandatory deliverables</th><th>Minimum Evidence Required</th><th>Evidence</th><th>Actions</th></tr></thead><tbody id="iso27001SoaBody"></tbody></table><div class="assessment-pagination" id="iso27001SoaPagination"></div></div>
        </div>
        </section>
</template>
