<script setup>
import { ref, computed, onMounted, onBeforeUnmount, nextTick, defineAsyncComponent } from 'vue';
import { isImageFile } from '../features/shared/noteImages.mjs';
import { noteUrl, noteIdFromHash } from '../features/shared/noteNavigation.mjs';
import { links, resolveNote } from '../features/shared/noteLinks.mjs';
import { formatSelection } from '../features/shared/noteEditor.mjs';
import KnowledgeGraph from './KnowledgeGraph.vue';
const KnowledgeTextEditor=defineAsyncComponent(()=>import('./KnowledgeTextEditor.vue'));
import { readNoteImport, collectDirectoryFiles } from '../features/shared/noteImport.mjs';
import { treeRows } from '../features/shared/noteTree.mjs';
import { searchScopes, searchNotes, highlight } from '../features/shared/noteSearch.mjs';
const searchScope=ref('all');
const results=computed(()=>searchNotes(notes.value,search.value,searchScope.value));
const expanded=ref(new Set()), context=ref(null), dragging=ref(null), dropTarget=ref(null);
const folders=ref([]), activeFolder=ref('*'), folderName=ref(''), editor=ref(null), folderInput=ref(null);
const noteImages=ref([]);
const notes=ref([]), draft=ref({title:'',content:'',folder:''}), dirty=ref(false), busy=ref(false), ready=ref(false), search=ref(''), tab=ref('editor'), status=ref(''), access=ref({}), input=ref(null);
const editable=computed(()=>ready.value && !busy.value && access.value[draft.value.id?'update':'create']);
const folderOptions=computed(()=>[...new Set([...folders.value,...notes.value.map(n=>n.folder).filter(Boolean)])].sort());
const rows=computed(()=>treeRows(folderOptions.value,notes.value,expanded.value,search.value,searchScope.value));
const outgoing=computed(()=>links(draft.value.content).map(title=>({title,note:resolveNote(notes.value,title,draft.value.folder||'')})));
const backlinks=computed(()=>notes.value.filter(n=>n.id!==draft.value.id && links(n.content).some(title=>resolveNote(notes.value,title,n.folder||'')?.id===draft.value.id)));
const formats=[['bold','Bold'],['italic','Italic'],['strike','Coret'],['heading','H1'],['subheading','H2'],['bullet','Daftar'],['ordered','Nomor'],['task','Checklist'],['quote','Kutipan'],['code','Code'],['codeblock','Blok kode'],['link','Tautan'],['wiki','Tautan catatan']];
async function format(kind){if(!editable.value||!editor.value)return;const result=formatSelection(draft.value.content,editor.value.selectionStart,editor.value.selectionEnd,kind);draft.value.content=result.content;dirty.value=true;await nextTick();editor.value.focus();editor.value.setSelectionRange(result.start,result.end);}
function shortcut(event){if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save();return;}if((event.ctrlKey||event.metaKey)&&['b','i'].includes(event.key.toLowerCase())){event.preventDefault();format(event.key.toLowerCase()==='b'?'bold':'italic');}}
function rememberExpanded(){try{localStorage.setItem('nist-note-folders-expanded',JSON.stringify([...expanded.value]));}catch{}}
function expandPath(path){const parts=path.split('/').filter(Boolean);const value=new Set(expanded.value);for(let i=1;i<=parts.length;i++)value.add(parts.slice(0,i).join('/'));expanded.value=value;rememberExpanded();}
function toggleFolder(path){activeFolder.value=path;const value=new Set(expanded.value);if(value.has(path))value.delete(path);else value.add(path);expanded.value=value;context.value=null;rememberExpanded();}
async function addFolder(){if(!access.value.create||busy.value)return;busy.value=true;const name=folderName.value.trim();const path=(activeFolder.value&&activeFolder.value!=='*'?activeFolder.value+'/':'')+name;try{folders.value=await request('/folders','POST',{path});activeFolder.value=path;expandPath(path);folderName.value='';status.value='Folder '+path+' dibuat.';}catch(e){status.value=e.message;}finally{busy.value=false;}}
function showMenu(row){context.value=row;if(row.type==='folder')activeFolder.value=row.path;}
function startDrag(event,row){if(busy.value||!access.value.update){event.preventDefault();return;}dragging.value=row;event.dataTransfer.setData('application/x-knowledge-note',JSON.stringify(row.type==='folder'?{type:'folder',path:row.path}:{type:'note',id:row.note.id}));event.dataTransfer.effectAllowed='move';context.value=null;}
function dragOver(event,path){if(!access.value.update||busy.value)return;if(!event.dataTransfer.types.includes('application/x-knowledge-note'))return;event.preventDefault();event.dataTransfer.dropEffect='move';dropTarget.value=path;}
function endDrag(){dragging.value=null;dropTarget.value=null;}
async function moveNote(note,path){if(busy.value||!access.value.update||(note.folder||'')===path)return;if(dirty.value){status.value='Simpan perubahan editor sebelum memindahkan catatan.';return;}busy.value=true;try{const saved=await request('/'+note.id,'PUT',{...note,folder:path});notes.value=notes.value.map(n=>n.id===saved.id?saved:n);if(draft.value.id===saved.id)draft.value={...saved};expandPath(path);activeFolder.value=path;status.value='Catatan dipindahkan ke '+(path||'Vault')+'.';}catch(e){status.value=e.message;}finally{busy.value=false;}}
async function moveFolder(source,destination){if(busy.value||!access.value.update)return;if(dirty.value){status.value='Simpan perubahan editor sebelum memindahkan folder.';return;}busy.value=true;try{const result=await request('/folders','PUT',{source,destination});folders.value=result.folders;notes.value=result.notes;const current=notes.value.find(n=>n.id===draft.value.id);if(current)draft.value={...current};const opened=new Set([...expanded.value].map(p=>p===source||p.startsWith(source+'/')?destination+p.slice(source.length):p));expanded.value=opened;activeFolder.value=destination;expandPath(destination);status.value='Folder dipindahkan ke '+destination+'.';}catch(e){status.value=e.message;}finally{busy.value=false;}}
async function drop(event,path){event.preventDefault();dropTarget.value=null;let item;try{item=JSON.parse(event.dataTransfer.getData('application/x-knowledge-note'));}catch{return;}if(item.type==='folder'){const destination=(path?path+'/':'')+item.path.split('/').pop();if(item.path!==destination)await moveFolder(item.path,destination);}else if(item.type==='note'){const note=notes.value.find(n=>n.id===item.id);if(note)await moveNote(note,path);}endDrag();}
async function renameItem(){const row=context.value;context.value=null;if(!row)return;if(row.type==='folder'){const parent=row.path.split('/').slice(0,-1).join('/');const name=window.prompt('Nama folder baru',row.label);if(name&&name!==row.label)await moveFolder(row.path,(parent?parent+'/':'')+name.trim());}else{if(dirty.value){status.value='Simpan perubahan editor sebelum mengganti nama.';return;}const title=window.prompt('Judul catatan baru',row.note.title);if(!title||title===row.note.title)return;busy.value=true;try{const result=await request('/'+row.note.id,'PUT',{...row.note,title});notes.value=notes.value.map(n=>n.id===result.id?result:n);if(draft.value.id===result.id)draft.value={...result};status.value='Judul diubah. Perbarui tautan yang memakai judul lama.';}catch(e){status.value=e.message;}finally{busy.value=false;}}}
async function deleteItem(mode='empty'){
 const row=context.value;context.value=null;
 if(!row||busy.value||!access.value.delete)return;
 if(row.type==='note'){select(row.note);if(draft.value.id===row.note.id)await remove();return;}
 const inside=folder=>folder===row.path||folder?.startsWith(row.path+'/');
 const count=notes.value.filter(note=>inside(note.folder)).length;
 const message=mode==='all'
  ? `Hapus folder ${row.path}, seluruh subfolder, dan ${count} catatan di dalamnya? Data yang dihapus tidak dapat dikembalikan.`
  : `Hapus folder kosong ${row.path}? Folder yang masih berisi catatan tidak akan dihapus.`;
 if(dirty.value&&inside(draft.value.folder)&&!discard())return;
 if(!window.confirm(message))return;
 busy.value=true;
 try{
  folders.value=await request('/folders','DELETE',{path:row.path,mode});
  if(mode==='all'){
   notes.value=notes.value.filter(note=>!inside(note.folder));
   if(inside(draft.value.folder)){draft.value={title:'',content:'',folder:''};dirty.value=false;}
  }
  if(inside(activeFolder.value))activeFolder.value='';
  expanded.value=new Set([...expanded.value].filter(path=>!inside(path)));rememberExpanded();
  status.value=mode==='all'?'Folder, subfolder, dan seluruh catatan di dalamnya dihapus.':'Folder kosong dihapus.';
 }catch(e){status.value=e.message;}finally{busy.value=false;}
}
function newInFolder(){activeFolder.value=context.value?.path||'';context.value=null;fresh();}
function subfolder(){activeFolder.value=context.value?.path||'';expandPath(activeFolder.value);context.value=null;nextTick(()=>document.getElementById('knNewFolderName')?.focus());}

async function request(path='',method='GET',body) {
 const response=await fetch('/api/knowledge-notes'+path,{method,headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});
 if(!response.ok) throw new Error((await response.json().catch(()=>({}))).error||'Permintaan gagal.');
 return response.status===204?null:response.json();
}
function discard(){return !dirty.value||window.confirm('Abaikan perubahan catatan yang belum disimpan?');}
function select(note){if(busy.value||!discard())return;draft.value={...note,folder:note.folder||''};activeFolder.value=note.folder||'';expandPath(activeFolder.value);dirty.value=false;tab.value='editor';context.value=null;history.replaceState(null,'',noteUrl(note.id));}
function openNoteById(id){const note=notes.value.find(note=>String(note.id)===String(id));if(!note){status.value='Catatan tujuan tidak ditemukan.';return;}select(note);if(String(draft.value.id)===String(note.id))history.replaceState(null,'',noteUrl(note.id));}
function navigateFromUrl(){const id=noteIdFromHash(window.location.hash);if(!id)return;if(!ready.value){open();return;}if(!busy.value){open();openNoteById(id);}}
async function copyNoteUrl(){if(!draft.value.id)return;const url=new URL(noteUrl(draft.value.id),window.location.origin).href;try{await navigator.clipboard.writeText(url);status.value='URL catatan disalin.';}catch{window.prompt('Salin URL catatan:',url);}}
function fresh(){if(busy.value||!discard())return;draft.value={title:'',content:'',folder:activeFolder.value==='*'?'':activeFolder.value};dirty.value=false;tab.value='editor';}
function follow(title){const note=resolveNote(notes.value,title,draft.value.folder||'');if(note)select(note);else if(access.value.create&&discard()){const target=title.replace(/\.md$/i,'');const slash=target.lastIndexOf('/');draft.value={title:target.slice(slash+1),content:'',folder:slash>=0?target.slice(0,slash):(activeFolder.value==='*'?'':activeFolder.value)};dirty.value=true;tab.value='editor';}}
async function load(){if(busy.value)return;busy.value=true;try{const response=await fetch('/api/auth/me');if(!response.ok)throw new Error('Sesi berakhir.');const user=await response.json();access.value=user.role==='admin'?{read:true,create:true,update:true,delete:true}:user.actions?.['knowledge-notes']||{};if(!access.value.read)throw new Error('Akses Knowledge Notes tidak tersedia.');const [loadedNotes,loadedFolders,loadedImages]=await Promise.all([request(),request('/folders'),request('/images')]);notes.value=loadedNotes;folders.value=loadedFolders;noteImages.value=loadedImages;ready.value=true;status.value='Catatan tersimpan di server.';}catch(e){status.value=e.message;}finally{busy.value=false;if(ready.value)navigateFromUrl();}}
async function save(){if(!editable.value)return;busy.value=true;try{const note=await request(draft.value.id?'/'+draft.value.id:'',draft.value.id?'PUT':'POST',draft.value);notes.value=notes.value.filter(n=>n.id!==note.id).concat(note);draft.value={...note};dirty.value=false;folders.value=await request('/folders');status.value='Catatan disimpan.';}catch(e){status.value=e.message;}finally{busy.value=false;}}
async function remove(){if(!draft.value.id||!access.value.delete||!confirm('Hapus catatan ini? Tautan dari catatan lain akan menjadi belum tersedia.'))return;busy.value=true;try{await request('/'+draft.value.id,'DELETE');notes.value=notes.value.filter(n=>n.id!==draft.value.id);draft.value={title:'',content:'',folder:''};dirty.value=false;status.value='Catatan dihapus.';}catch(e){status.value=e.message;}finally{busy.value=false;}}
function download(name,content,type){const url=URL.createObjectURL(new Blob([content],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function exportMd(){download((draft.value.title||'catatan').replace(/[<>:"/\\|?*]/g,'_')+'.md',draft.value.content,'text/markdown');}
async function chooseImportFolder(){
 if(!access.value.create||busy.value)return;
 if(typeof window.showDirectoryPicker!=='function'){folderInput.value.click();return;}
 let selected;
 try{selected=await window.showDirectoryPicker({mode:'read'});}
 catch(error){if(error.name==='AbortError')return;if(error.name==='SecurityError'){folderInput.value.click();return;}status.value=error.message;return;}
 busy.value=true;status.value='Menelusuri folder dan seluruh subfolder...';
 let files;const unreadable=[],directoryFolders=[];
 try{files=await collectDirectoryFiles(selected,'',{onUnreadable:(path,error)=>unreadable.push(path+': '+error.message),onFolder:path=>directoryFolders.push(path)});}catch(error){status.value='Folder tidak dapat dibaca: '+error.message;return;}finally{busy.value=false;}
 if(unreadable.length){status.value='Impor dibatalkan; belum ada file atau folder yang disimpan. Lokasi gagal dibaca: '+unreadable.join('; ')+'. Coba Pilih folder alternatif atau pastikan folder tersedia secara lokal.';return;}
 await importFiles({target:{files,value:''}},[],directoryFolders);
}
async function importFiles(event, unreadable=[],directoryFolders=[]){
 const files=[...event.target.files];event.target.value='';
 if((!files.length&&!directoryFolders.length)||!access.value.create||busy.value)return;
 busy.value=true;status.value='Membaca file catatan...';
 try{
  const skipped=[];
  const destination=activeFolder.value==='*'?'':activeFolder.value;
  const imageFiles=files.filter(file=>isImageFile(file.name));
  const assetPaths=imageFiles.map(file=>[destination,file.webkitRelativePath||file.name].filter(Boolean).join('/'));
  const assetFolders=assetPaths.map(path=>path.split('/').slice(0,-1).join('/')).filter(Boolean);
  const noteFiles=files.filter(file=>!isImageFile(file.name));
  const payload=!noteFiles.length&&imageFiles.length ? {notes:[],folders:[...new Set([...directoryFolders,...assetFolders])]} : await readNoteImport(noteFiles,activeFolder.value==='*'?'':activeFolder.value,{onSkipped:path=>skipped.push(path),onUnreadable:(path,error)=>unreadable.push(path+': '+error.message),folderPaths:[...directoryFolders,...assetFolders.map(path=>destination&&path.startsWith(destination+'/')?path.slice(destination.length+1):path)]});
  if(unreadable.length)throw new Error('Impor dibatalkan; belum ada file atau folder yang disimpan.');
  if(imageFiles.length){
   if(imageFiles.length>100||imageFiles.reduce((sum,file)=>sum+file.size,0)>100*1024*1024||imageFiles.some(file=>file.size>10*1024*1024))throw new Error('Maksimum 100 gambar / total 100 MB; setiap gambar maksimal 10 MB.');
   const body=new FormData();body.append('payload',JSON.stringify(payload));body.append('paths',JSON.stringify(assetPaths));
   imageFiles.forEach(file=>body.append('images',file.originalFile||file,file.name));
   const response=await fetch('/api/knowledge-notes/import-with-images',{method:'POST',body});
   const result=await response.json();if(!response.ok)throw new Error(result.error||'Impor gambar gagal.');notes.value=result;
  }else notes.value=await request('/import','POST',payload);
  noteImages.value=await request('/images');
  folders.value=await request('/folders');
  for(const folder of payload.folders)expandPath(folder);
  search.value='';
  status.value=payload.notes.length+' catatan dan '+payload.folders.length+' folder dan '+imageFiles.length+' gambar berhasil diimpor. Struktur folder dipertahankan.'+(skipped.length?' '+skipped.length+' file bukan .md/.txt tidak diimpor: '+skipped.slice(0,5).join(', ')+(skipped.length>5?' …':''):'');
 }catch(e){status.value=e.message;}finally{if(unreadable.length)status.value+=' '+unreadable.length+' lokasi gagal dibaca: '+unreadable.slice(0,5).join('; ')+(unreadable.length>5?' …':'')+'. Coba Pilih folder alternatif untuk membaca ulang.';busy.value=false;}
}
function open(){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active-view'));document.getElementById('knowledgeNotesView').classList.add('active-view');document.querySelectorAll('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.view==='knowledge-notes'));try{const state=JSON.parse(localStorage.getItem('nist-maturity-ui')||'{}');localStorage.setItem('nist-maturity-ui',JSON.stringify({...state,view:'knowledge-notes'}));}catch{}if(!ready.value)load();}
function unload(event){if(dirty.value){event.preventDefault();event.returnValue='';}}
onMounted(()=>{try{expanded.value=new Set(JSON.parse(localStorage.getItem('nist-note-folders-expanded')||'[]'));}catch{}document.querySelector('[data-view="knowledge-notes"]')?.addEventListener('click',open);window.addEventListener('beforeunload',unload);window.addEventListener('hashchange',navigateFromUrl);if(noteIdFromHash(window.location.hash))open();try{if(JSON.parse(localStorage.getItem('nist-maturity-ui')||'{}').view==='knowledge-notes')open();}catch{}});
onBeforeUnmount(()=>{document.querySelector('[data-view="knowledge-notes"]')?.removeEventListener('click',open);window.removeEventListener('beforeunload',unload);window.removeEventListener('hashchange',navigateFromUrl);});
</script>
<template>
<section id="knowledgeNotesView" class="view kn">
 <h2>Knowledge Notes <small>Knowledge Vault</small></h2><p>Hubungkan pengetahuan dengan <code>[[Judul catatan]]</code>, alias <code>[[Judul|Label]]</code>, dan #tag.</p>
 <div class="toolbar"><button @click="fresh" :disabled="!access.create||busy">+ Catatan</button><button @click="save" :disabled="!editable||!dirty">Simpan</button><button @click="remove" :disabled="!access.delete||!draft.id||busy">Hapus</button><button @click="input.click()" :disabled="!access.create||busy">Impor file</button><button @click="chooseImportFolder" :disabled="!access.create||busy">Impor folder</button><button @click="folderInput.click()" :disabled="!access.create||busy">Pilih folder alternatif</button><input ref="folderInput" type="file" webkitdirectory multiple hidden @change="importFiles"><input ref="input" type="file" accept=".md,.txt,.json,.png,.jpg,.jpeg,.gif,.webp" multiple hidden @change="importFiles"><button @click="copyNoteUrl" :disabled="!draft.id||busy">Salin URL catatan</button><button @click="exportMd">Ekspor catatan .md</button><button :disabled="!ready" @click="download('knowledge-notes.json',JSON.stringify({format:'knowledge-notes-v1',notes,folders:folderOptions},null,2),'application/json')">Ekspor semua JSON</button><a v-if="ready" href="/api/knowledge-notes/export">Unduh ZIP</a><button @click="load" :disabled="busy">Muat ulang daftar</button></div>
 <p class="import-help">Impor file: pilih catatan .md/.txt beserta gambar terkait sekaligus. Impor folder: seluruh subfolder dan gambar ikut dibaca. Gambar: PNG, JPG, GIF, WEBP.</p><p role="status" aria-live="polite">{{ status }} <strong v-if="dirty"> · Perubahan belum disimpan</strong></p>
 <div class="layout"><aside class="explorer" @keydown.esc="context=null">
 <div class="explorer-heading"><strong>FILES</strong><button @click="expanded=new Set();rememberExpanded()" title="Tutup semua folder">↟</button></div>
 <input v-model="search" type="search" aria-label="Cari file, judul, isi, folder, tag, atau tautan" placeholder="Cari file, judul, isi...">
 <select v-model="searchScope" class="search-scope" aria-label="Cari berdasarkan"><option v-for="[value,label] in searchScopes" :key="value" :value="value">{{ label }}</option></select>
 <details class="search-help"><summary>Opsi pencarian</summary><p>Beberapa kata mencari semua kata. Gunakan tanda kutip untuk frasa dan minus untuk pengecualian.</p><code>isi:"akses data" -tag:arsip</code><br><code>file:Policy.md folder:Keamanan</code><p>Pencarian mencakup file catatan yang telah diimpor atau disimpan di Knowledge Notes.</p></details>
 <div v-if="search.trim()" class="search-results" aria-label="Hasil pencarian"><div class="search-count" role="status">{{ results.length }} file ditemukan <button @click="search=''" aria-label="Hapus pencarian">×</button></div><button v-for="result in results" :key="result.note.id" class="search-result" :data-search-note="result.note.id" :disabled="busy" @click="select(result.note)"><strong data-no-translate><template v-for="(chunk,i) in highlight(result.note.title,search)" :key="i"><mark data-no-translate v-if="chunk.match">{{ chunk.text }}</mark><span data-no-translate v-else>{{ chunk.text }}</span></template></strong><small data-no-translate>{{ result.path }}</small><p data-no-translate><template v-for="(chunk,i) in highlight(result.snippet,search)" :key="i"><mark v-if="chunk.match">{{ chunk.text }}</mark><span data-no-translate v-else>{{ chunk.text }}</span></template></p></button><p v-if="!results.length">Tidak ada file yang cocok. Coba kata lain atau pilih Semua.</p></div>
 <div class="folder-create"><input id="knNewFolderName" v-model="folderName" aria-label="Nama folder baru" :placeholder="activeFolder&&activeFolder!=='*'?'Subfolder di '+activeFolder:'Folder baru'" @keydown.enter="addFolder"><button @click="addFolder" :disabled="!access.create||busy||!folderName.trim()" title="Buat folder">+ Folder</button></div>
 <button class="vault-row" :class="{selected:activeFolder==='', 'drop-target':dropTarget===''}" @click="activeFolder='';context=null" @dragover="dragOver($event,'')" @dragleave="dropTarget=null" @drop="drop($event,'')">◇ Knowledge Vault <small>{{ notes.length }}</small></button>
 <div class="file-tree" role="tree" aria-label="Folder dan catatan">
 <div v-for="row in rows" :key="row.type==='folder'?row.path:row.note.id" class="tree-row" :class="{selected:row.type==='folder'?activeFolder===row.path:draft.id===row.note.id,'drop-target':row.type==='folder'&&dropTarget===row.path}" :style="{paddingLeft:(10+row.depth*16)+'px'}" role="treeitem" :aria-level="row.depth+1" :aria-expanded="row.type==='folder'?expanded.has(row.path):undefined" :aria-selected="row.type==='folder'?activeFolder===row.path:draft.id===row.note.id" :draggable="access.update&&!busy" @dragstart="startDrag($event,row)" @dragend="endDrag" @dragover="row.type==='folder'&&dragOver($event,row.path)" @dragleave="dropTarget=null" @drop="row.type==='folder'&&drop($event,row.path)" @contextmenu.prevent="showMenu(row)">
 <button class="tree-label" :data-folder="row.type==='folder'?row.path:undefined" :data-note="row.type==='note'?row.note.id:undefined" @click="row.type==='folder'?toggleFolder(row.path):select(row.note)"><span class="tree-icon">{{ row.type==='folder'?(expanded.has(row.path)?'▾':'▸'):'▤' }}</span><span data-no-translate>{{ row.type==='folder'?row.label:row.note.title }}</span><small v-if="row.type==='folder'">{{ row.count }}</small></button><button class="tree-more" @click="showMenu(row)" :aria-label="'Menu '+(row.label||row.note?.title)">⋯</button>
 </div><p v-if="!rows.length" class="tree-empty">{{ search?'Tidak ada hasil pencarian.':'Vault kosong. Buat folder atau catatan pertama.' }}</p>
 </div>
 <div v-if="context" class="tree-menu" role="menu"><strong data-no-translate>{{ context.label||context.note?.title }}</strong><button v-if="context.type==='folder'" :disabled="!access.create||busy" @click="newInFolder">Catatan baru di sini</button><button v-if="context.type==='folder'" :disabled="!access.create||busy" @click="subfolder">Subfolder baru</button><button :disabled="!access.update||busy" @click="renameItem">Ganti nama</button><button :disabled="!access.delete||busy" @click="deleteItem('empty')">{{ context.type==='folder'?'Hapus folder kosong':'Hapus catatan' }}</button><button v-if="context.type==='folder'" :disabled="!access.delete||busy" @click="deleteItem('all')">Hapus semua isi folder</button><button @click="context=null">Tutup menu</button></div>
 <small class="explorer-help">Drag catatan atau folder ke folder tujuan. Klik kanan atau tombol menu untuk opsi.</small>
 </aside>
 <main><div class="note-breadcrumb">{{ draft.folder || 'Knowledge Vault' }} / {{ draft.title || 'Catatan baru' }}</div><div class="toolbar view-tabs"><button @click="tab='editor'">Editor</button><button @click="tab='preview'">Pratinjau</button><button @click="tab='source'">Markdown</button><button @click="tab='graph'">Graf hubungan</button></div>
 <template v-if="tab!=='graph'"><input v-model="draft.title" :disabled="!editable" maxlength="200" aria-label="Judul catatan" placeholder="Judul catatan" @input="dirty=true"><label class="folder-label">Folder catatan<select v-model="draft.folder" :disabled="!editable" @change="dirty=true"><option value="">Tanpa folder</option><option data-no-translate v-for="folder in folderOptions" :key="folder" :value="folder">{{ folder }}</option></select></label><KnowledgeTextEditor v-if="tab==='editor'||tab==='preview'" :key="String(draft.id||'new')+tab" :model-value="draft.content" :notes="notes" :folder="draft.folder" :images="noteImages" :editable="editable" :readonly="tab==='preview'" @update:model-value="draft.content=$event;dirty=true" @save="save" @open-note="openNoteById" @image-added="noteImages=noteImages.concat($event)"/><template v-else><div class="toolbar formatting" role="toolbar" aria-label="Format Markdown"><button v-for="[kind,label] in formats" :key="kind" :disabled="!editable" @mousedown.prevent @click="format(kind)">{{ label }}</button></div><textarea ref="editor" @keydown="shortcut" v-model="draft.content" :disabled="!editable" aria-label="Isi Markdown" placeholder="Sumber Markdown" @input="dirty=true"/></template></template>
 <KnowledgeGraph v-else :notes="notes" :selected-id="draft.id" @open="select"/>
 </main><aside><h3>Tautan keluar</h3><button v-for="link in outgoing" :key="link.title" @click="follow(link.title)"><span data-no-translate>{{ link.title }}</span> {{ link.note?'':'(belum tersedia)' }}</button><p v-if="!outgoing.length">Tambahkan [[judul]] untuk membuat hubungan.</p><h3>Backlinks</h3><button v-for="note in backlinks" :key="note.id" @click="select(note)"><span data-no-translate>{{ note.title }}</span></button><p v-if="!backlinks.length">Belum ada catatan yang menautkan judul ini.</p><small>Hubungan diperbarui setelah catatan disimpan. Judul harus unik di dalam folder yang sama. Gunakan [[folder/judul]] untuk tautan lintas folder. Jika judul diubah, perbarui tautan yang memakai judul lama.</small></aside></div>
</section>
</template>
<style scoped>
.search-scope{margin-top:8px;font-size:12px}.search-help{font-size:11px;color:#64748b;margin:9px 0}.search-help summary{cursor:pointer}.search-help p{line-height:1.6}.search-help code{font-size:10px;overflow-wrap:anywhere}.search-results{max-height:330px;overflow:auto;border-bottom:1px solid #e3dded;padding-bottom:8px}.search-count{display:flex;justify-content:space-between;align-items:center;font-size:11px;color:#64748b}.layout .search-count button{width:auto;margin:0;padding:3px 8px}.layout .search-result{font-size:12px;padding:10px;background:white;text-align:left}.search-result strong,.search-result small{display:block;overflow-wrap:anywhere}.search-result small{font-size:10px;margin-top:4px}.search-result p{font-size:11px;line-height:1.6;margin:7px 0 0;overflow-wrap:anywhere}.search-result mark{background:#ede2ff;color:#5b21b6;padding:0 1px;border-radius:2px}
.kn{color:#243248}.kn h2{font-size:28px}.kn p,.kn small{color:#64748b}.toolbar{display:flex;gap:8px;flex-wrap:wrap;align-items:center;margin:12px 0}.kn button,.kn a{padding:8px 12px;border:1px solid #d8dce8;border-radius:6px;background:white;color:#6148af;cursor:pointer}.kn button:disabled{opacity:.45;cursor:default}.layout{display:grid;grid-template-columns:220px minmax(0,1fr) 230px;border:1px solid #d8dce8;border-radius:12px;overflow:hidden;background:white}.layout aside{padding:16px;background:#f8f7fc}.layout aside button{display:block;width:100%;text-align:left;margin:6px 0;overflow-wrap:anywhere}.layout main{padding:16px;min-width:0}.kn input:not([type=file]),.kn textarea{box-sizing:border-box;width:100%;padding:12px;border:1px solid #d8dce8;border-radius:6px}.kn textarea{height:460px;margin-top:12px;font-family:monospace;resize:vertical;line-height:1.7}.selected{background:#eee6ff!important}.preview{min-height:460px;white-space:pre-wrap;overflow-wrap:anywhere}.preview .heading{font-size:22px;font-weight:700}.graph svg{width:100%;min-height:360px}.graph line{stroke:#c4b5df;stroke-width:2}.graph circle{fill:#7c5cbf}.graph text{fill:#334155;font-size:12px}.graph g{cursor:pointer}.kn small{line-height:1.6}@media(max-width:1000px){.layout{grid-template-columns:180px minmax(0,1fr)}.layout aside:last-child{grid-column:1/-1}}@media(max-width:650px){.layout{grid-template-columns:1fr}.layout aside:last-child{grid-column:auto}}
.kn select{width:100%;padding:9px;border:1px solid #d8dce8;border-radius:6px;background:white;color:#243248}.folder-label{display:block;margin:12px 0;font-size:13px}.folder-label select{margin-top:5px}.note-folder{display:block;font-size:10px;margin-top:4px}.formatting{padding:8px;background:#f8f7fc;border-radius:6px}.preview blockquote{border-left:3px solid #7c5cbf;padding-left:14px}.preview pre,.preview code{background:#f1eef8;padding:3px 6px;border-radius:4px}.preview h1{font-size:28px}.preview h2{font-size:24px}.preview h3{font-size:20px}.preview hr{border:0}.preview p{min-height:1em}.folder-create{margin:12px 0}

.layout{grid-template-columns:250px minmax(0,1fr) 210px;min-height:690px}.explorer{position:relative;display:flex;flex-direction:column;min-width:0}.explorer-heading{display:flex;align-items:center;justify-content:space-between;font-size:11px;letter-spacing:1.5px;margin-bottom:12px}.layout .explorer .explorer-heading button{width:auto;margin:0}.folder-create{display:flex;gap:5px}.layout .folder-create input{min-width:0;padding:8px}.layout .folder-create button{width:auto;white-space:nowrap;font-size:11px}.file-tree{flex:1;overflow:auto;max-height:600px;margin:4px -8px 12px}.layout .explorer .vault-row{font-weight:600;display:flex;justify-content:space-between}.tree-row{display:flex;align-items:center;border-radius:5px;min-height:34px;padding-right:3px}.layout .tree-row button{background:none;border:0;border-radius:0;margin:0;padding:7px 2px;color:inherit}.layout .tree-label{display:flex;align-items:center;gap:7px;flex:1;min-width:0;width:auto;font-size:12px}.tree-label>span:nth-child(2){overflow:hidden;text-overflow:ellipsis;white-space:nowrap;text-align:left}.tree-label small{margin-left:auto;padding-right:5px;font-size:10px}.tree-icon{width:16px;flex-shrink:0;color:#8b78b8}.layout .tree-more{width:24px;flex-shrink:0;opacity:.4}.tree-row:hover{background:#eeeaf6}.tree-row:hover .tree-more{opacity:1}.drop-target{outline:2px solid #8b5cf6;background:#e8ddff!important}.tree-menu{position:absolute;z-index:5;top:140px;left:18px;right:12px;background:white;border:1px solid #d8dce8;padding:10px;box-shadow:0 8px 35px #25203d26;border-radius:8px}.tree-menu strong{font-size:12px;overflow-wrap:anywhere}.layout .tree-menu button{font-size:12px}.explorer-help{font-size:11px}.note-breadcrumb{font-size:11px;color:#9a8cba;margin:0 0 8px}.view-tabs{border-bottom:1px solid #e8e2f2;padding-bottom:10px}.kn h2 small{font-size:12px;font-weight:400;margin-left:10px}.tree-empty{font-size:12px;padding:10px}@media(max-width:1150px){.layout{grid-template-columns:220px minmax(0,1fr)}.layout>aside:last-child{grid-column:1/-1;display:flex;flex-wrap:wrap;gap:10px;align-items:center}.layout>aside:last-child h3{margin:0}.layout>aside:last-child button{width:auto}.layout>aside:last-child small{width:100%}}@media(max-width:650px){.layout{grid-template-columns:1fr}.file-tree{max-height:260px}.tree-menu{top:100px}.layout>aside:last-child{grid-column:auto}}
</style>
