<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="privacyView" class="view">
          <div class="risk-management-tabs"><button class="button button-accent" type="button" data-privacy-tab="overview">Privacy overview</button><button class="button button-quiet" type="button" data-privacy-tab="core">PRIVACY FRAMEWORK CORE</button></div>
          <div class="page-heading"><div><p class="eyebrow">NIST PRIVACY FRAMEWORK 1.0</p><h2>Privacy Framework Core</h2><p class="lede">Assessment Privacy berdasarkan Privacy Framework Core dan ringkasan kategori dari workbook.</p></div><div class="csf-actions"><button class="button button-accent" id="privacyStartButton" type="button">Mulai assessment <span aria-hidden="true">&rarr;</span></button><button class="button button-dark" id="privacyResetButton" type="button">Reset Privacy assessment</button></div></div>
          <div class="hero-grid"><article class="score-panel"><div class="panel-kicker">Overall privacy maturity</div><div class="score-line"><strong id="privacyOverallScore">0.0</strong><span>/ 5.0</span></div><p id="privacyOverallLabel">Belum dinilai</p><div class="meter"><span id="privacyOverallMeter"></span></div><div class="score-foot"><span>1 Initial</span><span>5 Adaptive</span></div></article><article class="stat-panel"><span class="stat-label">Completion</span><strong id="privacyCompletionValue">0%</strong><span class="stat-detail" id="privacyCompletionDetail">0 controls scored</span></article><article class="stat-panel"><span class="stat-label">Priority gaps</span><strong id="privacyGapValue">0</strong><span class="stat-detail">controls below target level 3</span></article></div>
          <div class="section-heading"><div><p class="eyebrow">FRAMEWORK COVERAGE</p><h3>NIST Privacy Framework 1.0</h3></div><span class="target-chip">Target maturity <b>3.0</b></span></div>
          <div class="function-cards privacy-function-cards" id="privacyFunctionCards"></div>
          <div class="section-heading"><div><p class="eyebrow">PRIVACY SUMMARY</p><h3>Category maturity</h3></div><span class="target-chip">Target maturity <b>3.0</b></span></div>
          <div class="excel-wrap"><table class="excel-table summary-table"><thead><tr><th>Function</th><th>NIST Privacy 1.0 Categories</th><th>Target Score</th><th>Policy Score</th><th>Practice Score</th></tr></thead><tbody id="privacySummaryBody"></tbody></table></div>
          <div class="section-heading radar-heading"><div><p class="eyebrow">CATEGORY MATURITY PROFILE</p><h3>Policy and practice by category</h3></div><span class="muted">Average of subcategories · Scale 1 to 5</span></div>
          <article class="radar-panel"><div class="radar-chart-wrap"><canvas id="privacyMaturityRadar" width="700" height="430" aria-label="Spider diagram NIST Privacy Framework Summary"></canvas><div class="radar-tooltip" id="privacyRadarTooltip"></div></div><div class="radar-legend"><button type="button" class="radar-series active" data-privacy-series="policy"><i class="legend-policy"></i>Policy Score</button><button type="button" class="radar-series active" data-privacy-series="practice"><i class="legend-practice"></i>Practice Score</button><button type="button" class="radar-series active" data-privacy-series="target"><i class="legend-target"></i>Target Score</button></div></article>
          <div class="lower-grid"><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">NEXT MOVES</p><h3>Recommended focus</h3></div><span class="muted">Based on lowest scores</span></div><div id="privacyRecommendations"></div></article><article class="legend-panel"><p class="eyebrow">MATURITY SCALE</p><h3>What the levels mean</h3><div class="legend-list"><div><b>1</b><span><strong>Initial</strong><small>Privacy practices are absent or ad hoc.</small></span></div><div><b>2</b><span><strong>Repeatable</strong><small>Basic practices exist but vary.</small></span></div><div><b>3</b><span><strong>Defined</strong><small>Documented and repeatable practices.</small></span></div><div><b>4</b><span><strong>Managed</strong><small>Measured and consistently governed.</small></span></div><div><b>5</b><span><strong>Optimized</strong><small>Continuously improving and adaptive.</small></span></div></div></article></div>
          <dialog id="privacyControlModal" class="certification-modal"><form id="privacyControlModalForm" class="risk-register-form"><input id="privacyControlModalOriginalId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow" id="privacyControlModalMode">NEW CONTROL</p><h3 id="privacyControlModalTitle">Create Privacy control</h3></div><span class="save-state" id="privacyControlModalStatus">Ready</span></div><div class="csf-form-grid"><label>Control ID<input id="privacyControlModalId" required placeholder="ID.IM-P1"></label><label>Function<input id="privacyControlModalFunction" required placeholder="IDENTIFY-P"></label><label>Category<input id="privacyControlModalCategory" required></label><label>Subcategory<input id="privacyControlModalSubcategory" required></label><label>Implementation examples<textarea id="privacyControlModalImplementation" rows="3"></textarea></label><label>Informative references<textarea id="privacyControlModalReferences" rows="3"></textarea></label></div><div class="csf-form-actions"><button class="button button-accent" type="submit" id="privacyControlModalSubmit">Create control</button><button class="button button-quiet" type="button" id="privacyControlModalCancel">Close</button></div></form></dialog>
          <div class="section-heading"><div><p class="eyebrow">PRIVACY FRAMEWORK CORE</p><h3>Assessment controls</h3></div><div class="csf-actions"><button class="button button-quiet" id="addPrivacyButton" type="button">Add Privacy control</button><button class="button button-accent" id="privacyAssessmentButton" type="button">Open assessment <span aria-hidden="true">&rarr;</span></button><span class="muted" id="privacyControlCount">0 controls</span></div></div>
          <div class="toolbar"><label class="search-box"><span>/</span><input id="privacySearchInput" type="search" placeholder="Search Privacy controls..." autocomplete="off"></label><select id="privacyFunctionFilter" aria-label="Filter Privacy function"><option value="all">All functions</option></select><select id="privacySort" aria-label="Sort Privacy controls ascending"><option value="id">Sort: Control ID (A-Z)</option><option value="function">Sort: Function (A-Z)</option><option value="category">Sort: Category (A-Z)</option><option value="subcategory">Sort: Subcategory (A-Z)</option></select></div>
          <div class="excel-wrap"><table class="excel-table privacy-table"><thead><tr><th>Function</th><th>Category</th><th>Subcategory</th><th>Implementation examples</th><th>Informative references</th><th>Policy maturity</th><th>Policy score reasoning</th><th>Practice maturity</th><th>Practice score reasoning</th><th>Actions</th></tr></thead><tbody id="privacyTableBody"></tbody></table><div class="assessment-pagination" id="privacyAssessmentPagination"></div></div>
        </section>
</template>
