<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="riskAcceptanceView" class="view">
          <div class="page-heading"><div><p class="eyebrow">CYBERSECURITY GOVERNANCE</p><h2>Risk Acceptance Form</h2><p class="lede">Dokumentasikan permintaan penerimaan risiko siber dan simpan persetujuannya di database.</p></div><span class="file-count" id="riskAcceptanceCount">0 forms</span></div>
          <form id="riskAcceptanceForm" class="risk-acceptance-form">
            <input id="riskAcceptanceId" type="hidden">
            <div class="risk-document-page"><div class="risk-document-header"><h3>Cybersecurity Risk Acceptance Form</h3><span>Version 1.1</span></div><p class="risk-document-intro">Cybersecurity risk acceptance is a deliberate executive decision by a business owner to acknowledge and accept a cybersecurity risk which, for the reason given, cannot be remediated through available security controls and measures.</p><p class="risk-document-intro">Using this form, the application, service, or system owner describes the risk to be accepted, its potential impact, why it should be accepted, and mitigating factors, if any.</p><div class="section-heading compact"><div><p class="eyebrow">REQUEST DETAILS</p><h3>Application, Service or System Operational Owner</h3></div><span class="muted" id="riskAcceptanceStatus">New form</span></div>
            <div class="csf-form-grid"><label>Name of Requestor<input id="riskRequestorName" required maxlength="160"></label><label>Asset Name<input id="riskAssetName" required maxlength="200"></label><label>Department<input id="riskDepartment" required maxlength="160"></label><label class="checkbox-field"><span>Previous acceptance</span><span><input id="riskPreviouslyAccepted" type="checkbox"> This risk was accepted previously</span></label></div>
            <div class="risk-form-grid"><label>Description of Risk and/or Compliance Deviation<textarea id="riskDescription" required rows="5"></textarea></label><label>Benefit and Justification for Accepting this Risk<textarea id="riskBenefitJustification" required rows="5"></textarea></label><label>Factors that Minimize this Risk / Proposed Mitigation Plan<textarea id="riskMitigationPlan" required rows="5"></textarea></label></div>
            </div>

            <div class="risk-document-page"><div class="risk-form-section"><div class="section-heading compact"><div><p class="eyebrow">BUSINESS OWNER ACCEPTANCE</p><h3>Maximum one year</h3></div></div><div class="risk-choice-grid"><label><span>Decision</span><select id="riskBusinessOwnerDecision" required><option value="temporary">Yes, for a temporary period</option><option value="one_year">Yes, for up to one year</option><option value="denied">No, request denied</option></select></label><label><span>Risk will be remediated by</span><input id="riskRemediationDate" type="date"></label></div><div class="csf-form-grid"><label>Requestor name (print)<input id="riskRequestorPrintName"></label><label>Email / Telephone<input id="riskRequestorEmailPhone"></label><label>Signature<input id="riskRequestorSignature"></label><label>Date<input id="riskRequestorDate" type="date"></label></div></div>

            <div class="risk-form-section"><div class="section-heading compact"><div><p class="eyebrow">CIO ACKNOWLEDGEMENT</p><h3>CIO or equivalent</h3></div></div><label class="risk-wide-field">Comments (if any)<textarea id="riskCioComments" rows="4"></textarea></label><div class="csf-form-grid"><label>Name<input id="riskCioName"></label><label>Signature<input id="riskCioSignature"></label><label>Date<input id="riskCioDate" type="date"></label></div></div>
            </div>

            <div class="risk-document-page"><div class="risk-form-section"><div class="section-heading compact"><div><p class="eyebrow">CIS REVIEW</p><h3>Cybersecurity Team decision</h3></div></div><div class="risk-choice-grid"><label><span>Decision</span><select id="riskCisDecision" required><option value="approved">Approved</option><option value="denied">Denied</option><option value="conditional">Approved with conditions / comments</option></select></label><label>Reason (if denied)<textarea id="riskCisReason" rows="3"></textarea></label><label>Conditions / comments<textarea id="riskCisConditions" rows="3"></textarea></label></div><div class="csf-form-grid"><label>Name<input id="riskCisName"></label><label>Signature<input id="riskCisSignature"></label><label>Date<input id="riskCisDate" type="date"></label></div></div>
            </div>
            <div class="csf-form-actions"><button class="button button-accent" type="submit" id="riskAcceptanceSubmit">Save risk acceptance form</button><button class="button button-quiet" type="button" id="riskAcceptanceCancel">Clear form</button><span class="save-state" id="riskAcceptanceFormStatus">Ready</span></div>
          </form>
          <div class="section-heading"><div><p class="eyebrow">SAVED REQUESTS</p><h3>Risk acceptance forms</h3></div><span class="muted">Open a saved form to update it</span></div>
          <div class="excel-wrap"><table class="excel-table risk-acceptance-table"><thead><tr><th>Requestor</th><th>Asset</th><th>Department</th><th>Business Owner</th><th>CIS</th><th>Updated</th><th>Actions</th></tr></thead><tbody id="riskAcceptanceBody"></tbody></table><div class="assessment-pagination" id="riskAcceptancePagination"></div></div>
        </section>
</template>
