<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="riskAcceptanceView" class="view">
          <div class="page-heading"><div><p class="eyebrow">CYBERSECURITY GOVERNANCE</p><h2>Risk Acceptance</h2><p class="lede">Dokumentasikan permintaan penerimaan risiko siber dan simpan persetujuannya di database.</p></div><span class="file-count" id="riskAcceptanceCount">0 forms</span></div>
          <div class="risk-management-tabs" role="tablist" aria-label="Risk Acceptance">
            <button id="riskAcceptanceDashboardTab" class="button button-accent" type="button" role="tab" aria-selected="true" aria-controls="riskAcceptanceDashboardPanel" data-risk-acceptance-tab="dashboard">Dashboard</button>
            <button id="riskAcceptanceListTab" class="button button-quiet" type="button" role="tab" aria-selected="false" tabindex="-1" aria-controls="riskAcceptanceListPanel" data-risk-acceptance-tab="list">List Risk Acceptance</button>
          </div>
          <div class="csf-actions ra-new-request"><button id="riskAcceptanceNew" type="button" class="button button-accent">+ Request Risk Acceptance</button></div>
          <p id="riskAcceptancePageStatus" class="save-state" role="status" aria-live="polite"></p>
          <div id="riskAcceptanceDashboardPanel" role="tabpanel" aria-labelledby="riskAcceptanceDashboardTab">
            <article class="insight-panel ra-controls"><div class="section-heading compact"><div><p class="eyebrow">ACCEPTANCE GOVERNANCE</p><h3>Akuntabilitas &amp; review persetujuan</h3></div><div class="csf-actions"><button id="raRefresh" class="button button-quiet" type="button">Refresh data</button><button id="raAlertsButton" class="button button-quiet" type="button" aria-expanded="false" aria-controls="raAlerts">Pengingat review <span id="raAlertCount">0</span></button></div></div>
            <div class="rd-filters"><label>Status persetujuan<select id="raStatus"><option value="">Semua status</option><option value="pending">Pending / pengesahan belum lengkap</option><option value="approved">Approved</option><option value="conditional">Approved with conditions</option><option value="rejected">Rejected</option></select></label><label>Aset / sistem<select id="raAsset"><option value="">Semua aset</option></select></label><label>Departemen<select id="raDepartment"><option value="">Semua departemen</option></select></label><label>Jadwal review<select id="raReview"><option value="">Semua jadwal</option><option value="soon">H-30 atau lebih dekat</option><option value="overdue">Overdue review</option><option value="missing">Tanpa tanggal remediasi</option></select></label><button id="raReset" class="button button-quiet" type="button">Reset filter</button></div><p id="raFilterStatus" class="muted" role="status" aria-live="polite"></p><p class="muted">Status dashboard mempertimbangkan keputusan dan kelengkapan nama, tanda tangan, serta tanggal pemohon, CIO, dan CIS. Tanda tangan berupa input formulir, bukan tanda tangan digital terverifikasi.</p></article>
            <div id="raAlerts" class="insight-panel" hidden></div>
            <div id="raKpis" class="rd-kpis"></div>
            <div class="ra-visuals"><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">REMEDIATION &amp; REVIEW CALENDAR</p><h3>Kalender jadwal review</h3></div><label>Bulan<input id="raMonth" type="month" aria-label="Bulan kalender review"></label></div><p class="muted">Berdasarkan tanggal &quot;Risk will be remediated by&quot;. Kuning: H-30; merah: overdue. Klik tanggal untuk menyaring daftar.</p><div class="ra-weekdays" aria-hidden="true"><span>Min</span><span>Sen</span><span>Sel</span><span>Rab</span><span>Kam</span><span>Jum</span><span>Sab</span></div><div id="raCalendar" class="ra-calendar"></div><p id="raCalendarStatus" class="muted"></p></article>
            <article class="insight-panel"><p class="eyebrow">BUSINESS ACCOUNTABILITY</p><h3>Persetujuan per departemen</h3><div id="raDepartments" class="rd-bars"></div><div class="ra-legend"><span class="ra-dot ra-approved">Approved</span><span class="ra-dot ra-conditional">Bersyarat</span><span class="ra-dot ra-pending">Pending</span><span class="ra-dot ra-rejected">Rejected</span></div><h3>Distribusi aset / sistem</h3><div id="raAssets" class="rd-bars"></div></article></div>
            <div class="ra-visuals"><article class="insight-panel"><p class="eyebrow">MULTI-STAGE ACKNOWLEDGEMENT</p><h3>Kelengkapan pengesahan</h3><div id="raWorkflow" class="ra-workflow"></div><p class="muted">Menampilkan kelengkapan input tiap tahap. Routing persetujuan berdasarkan level risiko belum tersedia.</p></article><article class="insight-panel"><p class="eyebrow">DATA COVERAGE</p><h3>Risk &amp; compliance mapping</h3><p class="muted">Skor/level risiko, nilai eksposur finansial, dan standar kepatuhan belum menjadi field terstruktur pada formulir. Deskripsi risiko/deviasi, justifikasi, rencana mitigasi, dan kondisi CIS tersedia di detail.</p><div id="raCoverage" class="ra-coverage"></div></article></div>


          </div>
          <div id="riskAcceptanceListPanel" role="tabpanel" aria-labelledby="riskAcceptanceListTab" hidden>
            <article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">RISK ACCEPTANCE REGISTRY</p><h3>Daftar pengajuan <span id="raResultCount"></span></h3></div><div class="csf-actions toolbar"><button id="raBackDashboard" class="button button-quiet" type="button">Kembali ke dashboard</button><button id="raListReset" class="button button-quiet" type="button">Reset semua filter</button><input id="raSearch" type="search" aria-label="Cari pengajuan risk acceptance" placeholder="Cari ID, risiko, aset, pemohon..."><button id="raClearDrill" class="button button-quiet" type="button">Hapus drill-down</button></div></div><p id="raDrillStatus" class="muted" role="status"></p><div class="excel-wrap"><table class="excel-table ra-table"><thead><tr><th>Request ID &amp; risk</th><th>Asset / system</th><th>Kontrol / rencana mitigasi</th><th>Requestor / department</th><th>Pengesahan</th><th>Jadwal review</th><th>Status</th><th>Aksi</th></tr></thead><tbody id="riskAcceptanceBody"></tbody></table></div><div id="raPagination" class="assessment-pagination"></div><p class="muted">Batas review memakai tanggal remediasi, bukan expiry approval terverifikasi. Extend dan Revoke belum tersedia sebagai aksi khusus; perubahan menggunakan form yang sudah ada.</p></article>
</div>
            <dialog id="raAuditDialog" class="risk-acceptance-modal"><div class="section-heading"><h3 id="raAuditTitle">Audit aktivitas</h3><button id="raAuditClose" class="button button-quiet" type="button">Tutup</button></div><p class="muted">Log aktivitas aplikasi berisi pengguna, waktu, IP, dan input keputusan. Log ini tidak mengklaim bukti tanda tangan digital atau tamper-proof approval.</p><div id="raAuditBody"></div><div id="raAuditPagination" class="assessment-pagination"></div></dialog>
          <dialog id="riskAcceptanceModal" class="risk-acceptance-modal" aria-labelledby="riskAcceptanceModalTitle">
<div class="section-heading"><h3 id="riskAcceptanceModalTitle">Tambah Risk Acceptance</h3><button type="button" class="button button-quiet" id="riskAcceptanceClose">Tutup</button></div>
<form id="riskAcceptanceForm" class="risk-acceptance-form">
            <input id="riskAcceptanceId" type="hidden">
            <div class="risk-document-page"><div class="risk-document-header"><h3>Cybersecurity Risk Acceptance Form</h3><span>Version 1.1</span></div><p class="risk-document-intro">Cybersecurity risk acceptance is a deliberate executive decision by a business owner to acknowledge and accept a cybersecurity risk which, for the reason given, cannot be remediated through available security controls and measures.</p><p class="risk-document-intro">Using this form, the application, service, or system owner describes the risk to be accepted, its potential impact, why it should be accepted, and mitigating factors, if any.</p><div class="section-heading compact"><div><p class="eyebrow">REQUEST DETAILS</p><h3>Application, Service or System Operational Owner</h3></div><span class="muted" id="riskAcceptanceStatus">New form</span></div>
            <div class="csf-form-grid"><label>Name of Requestor<input id="riskRequestorName" required maxlength="160"></label><label>Asset Name<input id="riskAssetName" required maxlength="200"></label><label>Department<input id="riskDepartment" required maxlength="160"></label><label class="checkbox-field"><span>Previous acceptance</span><span><input id="riskPreviouslyAccepted" type="checkbox"> This risk was accepted previously</span></label></div>
            <div class="risk-form-grid"><label>Description of Risk and/or Compliance Deviation<textarea id="riskDescription" required rows="5"></textarea></label><label>Benefit and Justification for Accepting this Risk<textarea id="riskBenefitJustification" required rows="5"></textarea></label><label>Factors that Minimize this Risk / Proposed Mitigation Plan<textarea id="riskMitigationPlan" required rows="5"></textarea></label></div>
            </div>

            <div class="risk-document-page"><div class="risk-form-section"><div class="section-heading compact"><div><p class="eyebrow">BUSINESS OWNER ACCEPTANCE</p><h3>Maximum one year</h3></div></div><div class="risk-choice-grid"><label><span>Decision</span><select id="riskBusinessOwnerDecision" required><option value="temporary">Yes, for a temporary period</option><option value="one_year">Yes, for up to one year</option><option value="denied">No, request denied</option></select></label><label><span>Risk will be remediated by</span><input id="riskRemediationDate" type="date"></label></div><div class="csf-form-grid"><label>Requestor name (print)<input id="riskRequestorPrintName"></label><label>Email / Telephone<input id="riskRequestorEmailPhone"></label><label>Signature<input id="riskRequestorSignature"></label><label>Date<input id="riskRequestorDate" type="date"></label></div></div>

            <div class="risk-form-section"><div class="section-heading compact"><div><p class="eyebrow">CIO ACKNOWLEDGEMENT</p><h3>CIO or equivalent</h3></div></div><label class="risk-wide-field">Comments (if any)<textarea id="riskCioComments" rows="4"></textarea></label><div class="csf-form-grid"><label>Name<input id="riskCioName"></label><label>Signature<input id="riskCioSignature"></label><label>Date<input id="riskCioDate" type="date"></label></div></div>
            </div>

            <div class="risk-document-page"><div class="risk-form-section"><div class="section-heading compact"><div><p class="eyebrow">CIS REVIEW</p><h3>Cybersecurity Team decision</h3></div></div><div class="risk-choice-grid"><label><span>Decision</span><select id="riskCisDecision" required><option value="approved">Approved</option><option value="denied">Denied</option><option value="conditional">Approved with conditions / comments</option></select></label><label>Reason (if denied)<textarea id="riskCisReason" rows="3"></textarea></label><label>Conditions / comments<textarea id="riskCisConditions" rows="3"></textarea></label></div><div class="csf-form-grid"><label>Name<input id="riskCisName"></label><label>Signature<input id="riskCisSignature"></label><label>Date<input id="riskCisDate" type="date"></label></div></div>
            </div>
            <div class="csf-form-actions"><button class="button button-accent" type="submit" id="riskAcceptanceSubmit">Save risk acceptance form</button><button class="button button-quiet" type="button" id="riskAcceptanceCancel">Tutup</button><span class="save-state" id="riskAcceptanceFormStatus">Ready</span></div>
          </form>
          </dialog>
<dialog id="riskAcceptanceDeleteModal" class="risk-acceptance-modal risk-acceptance-delete-modal" aria-labelledby="riskAcceptanceDeleteTitle">
<h3 id="riskAcceptanceDeleteTitle">Hapus Risk Acceptance</h3><p id="riskAcceptanceDeleteMessage"></p><p class="save-state" role="status" id="riskAcceptanceDeleteStatus"></p>
<div class="csf-form-actions"><button type="button" class="button button-danger" id="riskAcceptanceDeleteConfirm">Hapus</button><button type="button" class="button button-quiet" id="riskAcceptanceDeleteCancel">Batal</button></div>
</dialog>
        </section>
</template>
<style>
.risk-acceptance-modal{width:min(1100px,calc(100vw - 32px));max-height:90vh;margin:auto;padding:24px;border:1px solid var(--line);border-radius:12px;background:var(--paper,#fff);color:var(--ink);overflow:auto;box-shadow:0 24px 80px #0f172a33}
.risk-acceptance-modal::backdrop{background:rgba(15,23,42,.55)}
.risk-acceptance-modal .risk-acceptance-form{margin-bottom:0}
.risk-acceptance-delete-modal{max-width:480px}
.risk-acceptance-delete-modal p{margin-top:16px}
@media(max-width:650px){.risk-acceptance-modal{padding:12px}}
</style>
