<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="riskManagementView" class="view">
          <div class="page-heading"><div><p class="eyebrow">CYBERSECURITY GOVERNANCE</p><h2>Risk Management</h2><p class="lede">Kelola risk register, indikator CIA, dampak, frekuensi, dan tindak lanjut risiko dalam satu ruang kerja.</p></div><div class="csf-actions"><button class="button button-accent" id="riskManagementNewButton" type="button">New risk</button><button class="button button-danger" id="riskRegisterResetButton" type="button">Reset Risk Register</button><span class="file-count" id="riskManagementCount">0 risks</span></div></div>
          <div class="risk-dashboard-grid"><article class="stat-panel"><span class="stat-label">Total risks</span><strong id="riskTotalValue">0</strong><span class="stat-detail">registered risks</span></article><article class="stat-panel"><span class="stat-label">High priority</span><strong id="riskHighValue">0</strong><span class="stat-detail">high or very high</span></article><article class="stat-panel"><span class="stat-label">Residual high</span><strong id="riskResidualValue">0</strong><span class="stat-detail">after treatment</span></article><article class="stat-panel"><span class="stat-label">Overdue</span><strong id="riskOverdueValue">0</strong><span class="stat-detail">deadline before today</span></article></div><div class="risk-summary-grid"><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">RISK RATING SUMMARY</p><h3>Current exposure</h3></div></div><div id="riskRatingSummary" class="risk-summary-list"></div></article><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">TREATMENT SUMMARY</p><h3>Response plan</h3></div></div><div id="riskTreatmentSummary" class="risk-summary-list"></div></article><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">PORTFOLIO VALUE</p><h3>Asset value average</h3></div></div><strong class="risk-summary-average" id="riskAssetValueAverage">0.0</strong><span class="stat-detail">average CIA asset value</span></article></div>
          <div class="risk-management-tabs"><button class="button button-accent" type="button" data-risk-tab="register">Risk Register</button><button class="button button-quiet" type="button" data-risk-tab="indicators">Indikator</button></div>
          <div id="riskRegisterPanel">
            <dialog id="riskManagementModal" class="certification-modal risk-management-modal"><form id="riskRegisterForm" class="risk-register-form"><input id="riskRegisterOriginalId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow">RISK REGISTER ENTRY</p><h3 id="riskRegisterFormTitle">New risk</h3></div><span class="save-state" id="riskRegisterStatus">Ready</span></div>
              <div class="risk-register-grid"><label>Risk ID<input id="rmRiskId" required placeholder="CSR - 004"></label><label>Risk category<input id="rmRiskCategory" required></label><label>Effected asset<input id="rmEffectedAsset" required></label><label>Nama perangkat<select id="rmDeviceName" required><option value="">Select device</option></select></label><label>Risk owner<input id="rmRiskOwner"></label><label>Asset confidentiality<input id="rmAssetConfidentiality" type="number" min="1" max="5"></label><label>Asset integrity<input id="rmAssetIntegrity" type="number" min="1" max="5"></label><label>Asset availability<input id="rmAssetAvailability" type="number" min="1" max="5"></label><label>Asset value<input id="rmAssetValue" type="number" min="1" max="25"></label><label>Likelihood (1-5)<input id="rmLikelihood" type="number" min="1" max="5" required></label><label>Impact (1-5)<input id="rmImpact" type="number" min="1" max="5" required></label><label>Risk rating<input id="rmRiskRating" placeholder="Auto from likelihood x impact"></label><label>Treatment action<select id="rmTreatmentAction"><option value="">Unassigned</option><option>Acceptance</option><option>Mitigation</option><option>Transfer</option><option>Avoidance</option><option>Closed</option></select></label><label>Deadline<input id="rmDeadline" type="date"></label><label>Owner of action<input id="rmOwnerOfAction"></label><label>Residual likelihood<input id="rmResidualLikelihood" type="number" min="1" max="5"></label><label>Residual impact<input id="rmResidualImpact" type="number" min="1" max="5"></label><label>Residual rating<input id="rmResidualRating" placeholder="Auto from residual score"></label><label>REF<input id="rmRef"></label><label>Acceptance form number<input id="rmAcceptanceFormNo"></label></div>
              <div class="risk-register-text-grid"><label>Identification risk<textarea id="rmIdentificationRisk" required rows="3"></textarea></label><label>Risk control<textarea id="rmRiskControl" rows="3"></textarea></label><label>Risk cause<textarea id="rmRiskCause" rows="3"></textarea></label><label>Risk analysis<textarea id="rmRiskAnalysis" rows="3"></textarea></label><label>Risk treatment description<textarea id="rmRiskTreatmentDescription" rows="3"></textarea></label><label>Residual risk description<textarea id="rmResidualRiskDescription" rows="3"></textarea></label><label>Note<textarea id="rmNote" rows="2"></textarea></label><label>Comment<textarea id="rmComment" rows="2"></textarea></label></div>
              <div class="csf-form-actions"><button class="button button-accent" type="submit" id="riskRegisterSubmit">Save risk</button><button class="button button-quiet" type="button" id="riskRegisterCancel">Close</button></div>
            </form></dialog>
            <div class="section-heading"><div><p class="eyebrow">REGISTERED RISKS</p><h3>Risk register</h3></div><label class="search-box"><span>/</span><input id="riskRegisterSearch" type="search" placeholder="Search risks..." autocomplete="off"></label></div><div class="toolbar risk-register-filters"><select id="riskRegisterCategoryFilter" aria-label="Filter risk category"><option value="all">All categories</option></select><select id="riskRegisterRatingFilter" aria-label="Filter risk rating"><option value="all">All ratings</option></select><select id="riskRegisterTreatmentFilter" aria-label="Filter treatment action"><option value="all">All treatments</option></select><button class="button button-quiet" id="riskRegisterClearFilters" type="button">Clear filters</button><button class="button button-quiet" id="riskRegisterExportButton" type="button">Export data</button><button class="button button-quiet" id="riskRegisterTemplateButton" type="button">Download import example</button><label class="button button-quiet" for="riskRegisterImportInput">Import data<input id="riskRegisterImportInput" type="file" accept="application/json,.json" hidden></label></div><div class="excel-wrap"><table class="excel-table risk-register-table"><thead id="riskRegisterHead"></thead><tbody id="riskRegisterBody"></tbody></table></div>
          </div>
          <div id="riskCertificationsPanel" hidden>
            <div class="risk-management-tabs personnel-certification-tabs"><button class="button button-accent" type="button" data-personnel-tab="organization" aria-controls="personnelOrganizationPanel">1. Daftar pegawai</button><button class="button button-quiet" type="button" data-personnel-tab="map" aria-controls="personnelCertificationMapPanel">2. Sertifikasi pegawai</button><button class="button button-quiet" type="button" data-personnel-tab="reference" aria-controls="personnelReferenceRoadmapPanel">3. Reference Roadmap</button></div>
            <p class="muted" id="personnelWorkflowStatus" role="status" aria-live="polite">Daftarkan pegawai terlebih dahulu. Satu pegawai dapat memiliki banyak sertifikasi.</p>
            <div id="personnelOrganizationPanel">
              <div class="page-heading"><div><p class="eyebrow">ORGANIZATION STRUCTURE</p><h2>Organisasi Struktur</h2><p class="lede">Daftarkan pegawai dan jabatan, lalu tambahkan sertifikasinya. Atasan langsung boleh kosong untuk posisi paling atas.</p></div><div class="csf-actions"><button class="button button-accent" id="organizationPersonnelNewButton" type="button">Tambah pegawai</button><span class="file-count" id="organizationPersonnelCount">0 personnel</span></div></div>
              <div class="risk-dashboard-grid"><article class="stat-panel"><span class="stat-label">Personel</span><strong id="organizationPersonCount">0</strong><span class="stat-detail">registered personnel</span></article><article class="stat-panel"><span class="stat-label">Sertifikasi aktif</span><strong id="organizationActiveCount">0</strong><span class="stat-detail">active certifications</span></article><article class="stat-panel"><span class="stat-label">Role / domain</span><strong id="organizationRoleCount">0</strong><span class="stat-detail">organization groups</span></article><article class="stat-panel"><span class="stat-label">Perlu perhatian</span><strong id="organizationAttentionCount">0</strong><span class="stat-detail">planned or expired</span></article></div>
              <div id="organizationStructure" class="organization-structure"></div>
              <dialog id="organizationPersonnelModal" class="certification-modal"><form id="organizationPersonnelForm" class="risk-register-form"><input id="organizationPersonnelId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow" id="organizationPersonnelFormMode">PEGAWAI BARU</p><h3 id="organizationPersonnelFormTitle">Tambah pegawai</h3></div><span class="save-state" id="organizationPersonnelStatus">Ready</span></div><div class="risk-register-grid"><label>Nama pegawai<input id="organizationPersonnelName" required maxlength="160"></label><label>Employee ID<input id="organizationPersonnelEmployeeId" maxlength="80"></label><label>Role / jabatan<input id="organizationPersonnelRole" maxlength="160" placeholder="CISO, SOC Manager, Analyst..."></label><label>Atasan langsung (opsional)<input id="organizationPersonnelSupervisor" list="organizationPersonnelNames" maxlength="160" placeholder="Kosongkan untuk posisi paling atas" aria-describedby="organizationSupervisorHint"><small class="muted" id="organizationSupervisorHint">Tidak perlu diisi jika pegawai tidak memiliki atasan langsung.</small></label></div><div class="csf-form-actions"><button class="button button-accent" type="submit">Simpan pegawai</button><button class="button button-quiet" id="organizationPersonnelCancel" type="button">Tutup</button></div></form></dialog>
              <div class="section-heading"><div><p class="eyebrow">PERSONNEL REGISTER</p><h3>Daftar pegawai</h3></div></div><div class="excel-wrap"><table class="excel-table personnel-register-table"><thead><tr><th>Nama</th><th>Employee ID</th><th>Role / jabatan</th><th>Atasan langsung</th><th>Sertifikasi</th><th>Aksi</th></tr></thead><tbody id="organizationPersonnelBody"></tbody></table></div>

            </div>
            <div id="personnelCertificationMapPanel" hidden>
            <div class="section-heading"><div><p class="eyebrow">PERSONNEL CERTIFICATION ROADMAP</p><h3>Security certification map</h3><p class="muted">Seret kartu untuk mengatur posisi. Tarik sudut kanan bawah untuk mengubah ukuran.</p></div><div class="csf-actions"><button class="button button-accent" id="certificationNewButton" type="button" disabled>Tambah sertifikasi</button><span class="file-count" id="certificationCount">0 certifications</span></div></div>
            <p class="muted" id="certificationPersonnelHint">Daftarkan pegawai pada langkah 1 untuk mulai menambahkan sertifikasi.</p>
              <div class="certification-board-wrap"><div class="certification-board" id="certificationBoard"><div class="certification-board-empty" id="certificationBoardEmpty">Belum ada sertifikasi. Tambahkan data untuk membangun roadmap.</div></div></div>
            <dialog id="certificationModal" class="certification-modal"><form id="certificationForm" class="risk-register-form"><input id="certificationId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow">CERTIFICATION RECORD</p><h3 id="certificationFormTitle">New certification</h3></div><span class="save-state" id="certificationStatus">Ready</span></div><div class="risk-register-grid"><label>Pegawai terdaftar<select id="certificationPersonnelId" required><option value="">Pilih pegawai terdaftar</option></select></label><label>Employee ID<input id="certificationEmployeeId" readonly placeholder="Terisi dari data pegawai"></label><label>Role / jabatan<input id="certificationPersonnelRole" readonly placeholder="Terisi dari data pegawai"></label><label>Atasan langsung<input id="certificationSupervisorName" readonly placeholder="Tidak ada / posisi teratas"></label><label>Certification name<input id="certificationName" list="roadmapCatalogNames" required maxlength="200" placeholder="Search Roadmap catalog or enter a new certification"></label><label>Issuer<input id="certificationIssuer" maxlength="160"></label><label>Reference URL<input id="certificationReferenceUrl" type="url" maxlength="500" placeholder="https://..."></label><label>Status<select id="certificationCertificationStatus"><option>Planned</option><option>In progress</option><option>Active</option><option>Expired</option></select></label><label>Issue date<input id="certificationIssueDate" type="date"></label><label>Expiry date<input id="certificationExpiryDate" type="date"></label></div><datalist id="roadmapCatalogNames"></datalist><datalist id="organizationPersonnelNames"></datalist><label>Notes<textarea id="certificationNotes" rows="3"></textarea></label><div class="csf-form-actions"><button class="button button-accent" type="submit">Save certification</button><button class="button button-danger" id="certificationDelete" type="button" hidden>Delete certification</button><button class="button button-quiet" id="certificationCancel" type="button">Close</button></div></form></dialog>
            <div class="section-heading"><div><p class="eyebrow">CERTIFICATION REGISTER</p><h3>Personnel records</h3><p class="muted">Semua sertifikasi dikelompokkan per pegawai. Tambahkan sertifikasi lain dengan memilih pegawai yang sama.</p></div></div><div class="excel-wrap"><table class="excel-table certification-table"><thead><tr><th>Personnel</th><th>Employee ID</th><th>Role / domain</th><th>Certification</th><th>Issuer</th><th>Status</th><th>Expiry</th><th>Actions</th></tr></thead><tbody id="certificationBody"></tbody></table></div>
            </div>
            <div id="personnelReferenceRoadmapPanel" hidden>
            <div class="section-heading certification-reference-heading"><div><p class="eyebrow">REFERENCE ROADMAP</p><h3>Security Certification Roadmap 9</h3><p class="muted">Klik card untuk melihat detail atau mengelola katalog.</p></div><button class="button button-accent" id="roadmapCatalogNewButton" type="button" hidden>New catalog item</button></div><div class="certification-reference certification-reference-exact" id="certificationReferenceBoard"><div class="certification-reference-loading">Loading Security Certification Roadmap 9...</div></div>
            <dialog id="roadmapCatalogModal" class="certification-modal"><form id="roadmapCatalogForm" class="risk-register-form"><input id="roadmapCatalogId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow">ROADMAP CATALOG</p><h3 id="roadmapCatalogFormTitle">Certification details</h3></div><span class="save-state" id="roadmapCatalogStatus">Ready</span></div><div class="risk-register-grid"><label>Domain<input id="roadmapCatalogDomain" required maxlength="200"></label><label>Certification name<input id="roadmapCatalogName" required maxlength="200"></label><label>Issuer<input id="roadmapCatalogIssuer" maxlength="160"></label><label>Reference URL<input id="roadmapCatalogUrl" type="url" maxlength="500" placeholder="https://..."></label><label>Level<select id="roadmapCatalogLevel"><option>Entry Level</option><option>Intermediate</option><option>Advanced / Expert</option></select></label></div><a class="button roadmap-reference-button" id="roadmapCatalogReferenceLink" href="#" target="_blank" rel="noopener noreferrer" hidden>Open reference</a><label>Notes<textarea id="roadmapCatalogNotes" rows="4"></textarea></label><div class="csf-form-actions"><button class="button button-accent" id="roadmapCatalogSave" type="submit">Save catalog item</button><button class="button button-danger" id="roadmapCatalogDelete" type="button" hidden>Delete</button><button class="button button-quiet" id="roadmapCatalogCancel" type="button">Close</button></div></form></dialog>
            </div>
          </div>
          <div id="riskIndicatorsPanel" hidden><div class="section-heading"><div><p class="eyebrow">RISK INDICATORS</p><h3>Indicator library</h3></div><button class="button button-accent" id="riskIndicatorNewButton" type="button">New indicator</button></div><form id="riskIndicatorForm" class="risk-register-form" hidden><input id="riskIndicatorId" type="hidden"><div class="risk-register-grid"><label>Type<input id="riskIndicatorType" required placeholder="CIA / Impact / Frequency / Matrix"></label><label>Score<input id="riskIndicatorScore" type="number"></label><label>Label<input id="riskIndicatorLabel" required></label><label>Sort order<input id="riskIndicatorSort" type="number" value="0"></label></div><label>Description<textarea id="riskIndicatorDescription" rows="3"></textarea></label><div class="csf-form-actions"><button class="button button-accent" type="submit">Save indicator</button><button class="button button-quiet" id="riskIndicatorCancel" type="button">Cancel</button></div></form><div class="indicator-sheet-grid"><article class="indicator-sheet"><div class="indicator-sheet-title"><span>01</span><div><p class="eyebrow">INDIKATOR CIA</p><h3>Confidentiality · Integrity · Availability</h3></div></div><div class="excel-wrap"><table class="excel-table indicator-table"><thead><tr><th>Nilai</th><th>Confidentiality</th><th>Integrity</th><th>Availability</th><th>Actions</th></tr></thead><tbody id="riskIndicatorsCiaBody"></tbody></table></div></article><article class="indicator-sheet"><div class="indicator-sheet-title"><span>02</span><div><p class="eyebrow">INDIKATOR DAMPAK</p><h3>Dampak terhadap organisasi</h3></div></div><div class="excel-wrap"><table class="excel-table indicator-table"><thead><tr><th>Nilai</th><th>Deskripsi</th><th>Layanan</th><th>Keuangan</th><th>Reputasi</th><th>Hukum</th><th>Actions</th></tr></thead><tbody id="riskIndicatorsImpactBody"></tbody></table></div></article><article class="indicator-sheet"><div class="indicator-sheet-title"><span>03</span><div><p class="eyebrow">INDIKATOR FREKUENSI</p><h3>Riwayat dan potensi kejadian</h3></div></div><div class="excel-wrap"><table class="excel-table indicator-table"><thead><tr><th>Nilai</th><th>Riwayat kejadian</th><th>Actions</th></tr></thead><tbody id="riskIndicatorsFrequencyBody"></tbody></table></div></article><article class="indicator-sheet indicator-sheet-wide"><div class="indicator-sheet-title"><span>04</span><div><p class="eyebrow">MATRIKS RISK LEVEL</p><h3>Dampak x Frekuensi</h3></div></div><div class="excel-wrap"><table class="excel-table indicator-table risk-matrix-table"><thead><tr><th>Rentang skor</th><th>1 · Very Low</th><th>2 · Low</th><th>3 · Medium</th><th>4 · High</th><th>5 · Very High</th><th>Actions</th></tr></thead><tbody id="riskIndicatorsMatrixBody"></tbody></table></div></article></div></div>
        </section>
</template>
