<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="tprmQuestionnaireView" class="view">
          <div class="page-heading"><div><p class="eyebrow">TPRM SUBPAGE 03</p><h2>Vendor Due Diligence Questionnaire</h2><p class="lede">Standardized assessment for Tier 1 and Tier 2 vendors prior to onboarding and annually thereafter.</p></div><div class="csf-actions"><button class="button button-accent" id="questionnaireNewButton" type="button">New questionnaire</button><span class="file-count" id="questionnaireCount">0 records</span></div></div>
          <div class="section-heading"><div><p class="eyebrow">QUESTIONNAIRE RECORDS</p><h3>Vendor assessments</h3><p class="muted">Used by TPRM Committee, IT Security, and Procurement.</p></div></div><div class="excel-wrap"><table class="excel-table tprm-register-table"><thead><tr><th>Vendor</th><th>Risk tier</th><th>PII Exposure</th><th>Security Maturity</th><th>Financial</th><th>Reputation</th><th>Total Score</th><th>Assessment status</th><th>Review date</th><th>Assessment result</th><th>Actions</th></tr></thead><tbody id="questionnaireBody"></tbody></table></div>
          <dialog id="questionnaireModal" class="certification-modal"><form id="questionnaireForm" class="risk-register-form"><input id="questionnaireId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow">QUESTIONNAIRE RECORD</p><h3 id="questionnaireFormTitle">New questionnaire</h3></div><span class="save-state" id="questionnaireStatus">Ready</span></div><div class="risk-register-grid"><label>Vendor company name<input id="questionnaireVendorName" required maxlength="200"></label><label>Assessment status<select id="questionnaireStatusValue"><option>Draft</option><option>In progress</option><option>Complete</option><option>Expired</option><option>Final</option></select></label><label>Review date<input id="questionnaireReviewDate" type="date"></label><label>Assessment result<select id="questionnaireResult"><option>Pending</option><option>Approved</option><option>Approved with Conditions</option><option>Rejected</option></select></label><label>Reviewer<input id="questionnaireReviewer" maxlength="160"></label></div><fieldset class="questionnaire-section questionnaire-final-section"><legend>Risk scoring</legend><div class="risk-register-grid"><label>PII Exposure (1-5)<input id="questionnaireFormPiiExposure" type="number" min="1" max="5" required></label><label>Security Maturity (1-5)<input id="questionnaireFormSecurityMaturity" type="number" min="1" max="5" required></label><label>Financial Stability (1-5)<input id="questionnaireFormFinancial" type="number" min="1" max="5" required></label><label>Reputation &amp; References (1-5)<input id="questionnaireFormReputation" type="number" min="1" max="5" required></label><label>Total Score / 500<input id="questionnaireFormRiskScore" type="number" readonly></label><label>Risk Tier<input id="questionnaireFormRiskTier" readonly placeholder="Auto-calculated from score"></label></div><table class="tprm-tier-table"><tbody><tr><td>40%</td><td><strong>PII Exposure</strong><small>Score x 40, inverted: 5 means no exposure</small></td></tr><tr><td>30%</td><td><strong>Security Maturity</strong><small>Score x 30</small></td></tr><tr><td>10%</td><td><strong>Financial Stability</strong><small>Score x 10</small></td></tr><tr><td>20%</td><td><strong>Reputation &amp; References</strong><small>Score x 20</small></td></tr><tr><td>500</td><td><strong>Maximum possible</strong><small>Tier 1 &lt;= 200, Tier 2 201-350, Tier 3 351-500</small></td></tr></tbody></table></fieldset><label>Response / assessment notes<textarea id="questionnaireNotes" rows="6"></textarea></label><div class="csf-form-actions"><button class="button button-accent" type="submit">Save questionnaire</button><button class="button button-danger" id="questionnaireDelete" type="button" hidden>Delete questionnaire</button><button class="button button-quiet" id="questionnaireCancel" type="button">Close</button></div></form></dialog>
          <dialog id="questionnaireAssessmentModal" class="certification-modal questionnaire-assessment-modal"><form id="questionnaireAssessmentForm" class="risk-register-form"><input id="questionnaireAssessmentId" type="hidden"><div class="section-heading compact"><div><p class="eyebrow">VENDOR DUE DILIGENCE QUESTIONNAIRE</p><h3 id="questionnaireAssessmentTitle">Vendor questionnaire</h3></div><span class="save-state" id="questionnaireAssessmentStatus">Ready</span></div><div id="questionnaireSections"></div><div class="csf-form-actions"><button class="button button-accent" type="submit">Save questionnaire</button><button class="button button-quiet" id="questionnaireAssessmentCancel" type="button">Close</button></div></form></dialog>
          <dialog id="templateSelectionModal" class="certification-modal"><div class="section-heading compact"><div><p class="eyebrow">SELECT TEMPLATE</p><h3>Choose questionnaire template</h3></div></div><div class="risk-register-grid" id="templateSelectionList"></div><div class="csf-form-actions"><button class="button button-quiet" id="templateSelectionCancel" type="button">Cancel</button></div></dialog>
        </section>
</template>
