<!-- Static DOM retained for existing feature runtime. Keep IDs and classes stable. -->
<template>
<section v-pre id="tprmTieringView" class="view">
          <div class="page-heading"><div><p class="eyebrow">TPRM SUBPAGE 02</p><h2>Vendor Risk Tiering Matrix</h2><p class="lede">Classify all vendors by inherent risk to determine due diligence depth, monitoring frequency, and contract requirements.</p></div><span class="file-count">TPRM</span></div>
          <p class="muted">Used by TPRM Committee for vendor onboarding decisions and annual re-tiering.</p>
          <div class="section-heading"><div><p class="eyebrow">1. TIER DEFINITIONS</p><h3>Vendor risk tiers</h3></div></div><div class="excel-wrap"><table class="excel-table tprm-framework-table"><thead><tr><th>Tier</th><th>Risk level</th><th>Definition</th><th>Typical profile</th></tr></thead><tbody><tr><td>Tier 1</td><td>High</td><td>Processes sensitive PII, has administrative access to critical systems, or integrates with OT/IoT. A breach could cause material harm.</td><td>Custom ERP/MES developers, AWS/Azure, payroll processors, OT integrators</td></tr><tr><td>Tier 2</td><td>Medium</td><td>Processes limited PII or has restricted system access. Breach impact is moderate.</td><td>SaaS CRM, logistics, IT support, analytics platforms</td></tr><tr><td>Tier 3</td><td>Low</td><td>No PII access or only anonymized/aggregated data. Breach impact is minimal.</td><td>Office supplies, training providers, non-PII consultants</td></tr></tbody></table></div>
          <div class="section-heading"><div><p class="eyebrow">2. RISK SCORING MODEL (0-100)</p><h3>Scoring dimensions</h3></div></div><div class="excel-wrap"><table class="excel-table tprm-framework-table"><thead><tr><th>Dimension</th><th>Weight</th><th>Score 1: Poor</th><th>Score 3: Adequate</th><th>Score 5: Excellent</th></tr></thead><tbody><tr><td>PII Exposure</td><td>40%</td><td>Sensitive PII at scale with admin access</td><td>Limited PII with restricted access</td><td>No PII or anonymized only</td></tr><tr><td>Security Maturity</td><td>30%</td><td>No certifications or security program</td><td>SOC 2 Type II or ISO 27001</td><td>Multiple certifications and continuous improvement</td></tr><tr><td>Financial Stability</td><td>10%</td><td>Startup, no insurance, unclear financials</td><td>Established, insurance below $5M</td><td>Enterprise-grade, insurance above $5M</td></tr><tr><td>Reputation & References</td><td>20%</td><td>Breaches, no references, legal actions</td><td>Clean history and industry references</td><td>Excellent reputation and thought leadership</td></tr></tbody></table></div><p class="tprm-formula"><strong>Final Score = Sum of (Dimension Score x Weight)</strong></p>
          <div class="section-heading"><div><p class="eyebrow">3. TIER ASSIGNMENT RULES</p><h3>Approvals and overrides</h3></div></div><div class="tprm-grid"><article class="insight-panel"><table class="tprm-tier-table"><tbody><tr><td>0-40</td><td><strong>Tier 1 (High)</strong><small>CISO + Privacy Officer + Legal</small></td></tr><tr><td>41-70</td><td><strong>Tier 2 (Medium)</strong><small>CISO or delegate + Business Owner</small></td></tr><tr><td>71-100</td><td><strong>Tier 3 (Low)</strong><small>Business Owner</small></td></tr></tbody></table></article><article class="insight-panel"><div class="section-heading compact"><div><p class="eyebrow">OVERRIDE RULES</p><h3>Re-tier triggers</h3></div></div><ul class="tprm-list"><li><strong>OT/IoT access</strong><span>+15 penalty</span></li><li><strong>Offshore weak jurisdiction</strong><span>+10 penalty</span></li><li><strong>Sole source critical function</strong><span>Flag concentration risk</span></li><li><strong>PII breach in 24 months</strong><span>Automatic Tier 1</span></li></ul></article></div>
          <div class="section-heading"><div><p class="eyebrow">4-6. CONTROL REQUIREMENTS</p><h3>Due diligence, monitoring, and contracts</h3></div></div><div class="excel-wrap"><table class="excel-table tprm-framework-table"><thead><tr><th>Requirement</th><th>Tier 1</th><th>Tier 2</th><th>Tier 3</th></tr></thead><tbody><tr><td>Full due diligence questionnaire</td><td>Required</td><td>Required</td><td>Not required</td></tr><tr><td>Technical assessment</td><td>Required</td><td>If PII involved</td><td>Not required</td></tr><tr><td>Reference checks</td><td>3 or more</td><td>2 or more</td><td>Not required</td></tr><tr><td>On-site / remote audit</td><td>Annual on-site</td><td>Annual remote</td><td>Triennial or trigger-based</td></tr><tr><td>Security questionnaire refresh</td><td>Quarterly</td><td>Biannual</td><td>Annual</td></tr><tr><td>DPA and audit rights</td><td>Mandatory</td><td>If PII / mandatory audit</td><td>If PII</td></tr><tr><td>Breach notification</td><td>Within 48 hours</td><td>Within 72 hours</td><td>If PII</td></tr><tr><td>Cyber insurance</td><td>$5M minimum</td><td>$2M minimum</td><td>Not required</td></tr></tbody></table></div>
          <div class="section-heading"><div><p class="eyebrow">7-10. OPERATING REFERENCE</p><h3>Re-tiering, manufacturing, register, and calculation</h3></div></div><div class="tprm-grid"><article class="insight-panel"><ul class="tprm-list"><li><strong>Re-tiering</strong><span>Annual review, data scope change, PII incident, merger, regulation, or KPI deterioration</span></li><li><strong>Manufacturing</strong><span>OT/IoT code, factory remote access, or biometrics normally adds +15 and likely Tier 1</span></li><li><strong>Register</strong><span>Vendor ID, name, service, four dimension scores, total, tier, last and next assessment</span></li></ul></article><article class="insight-panel"><table class="tprm-tier-table"><tbody><tr><td>40%</td><td><strong>PII Exposure</strong><small>Score x 40, inverted: 5 means no exposure</small></td></tr><tr><td>30%</td><td><strong>Security Maturity</strong><small>Score x 30</small></td></tr><tr><td>10%</td><td><strong>Financial Stability</strong><small>Score x 10</small></td></tr><tr><td>20%</td><td><strong>Reputation</strong><small>Score x 20</small></td></tr><tr><td>500</td><td><strong>Maximum possible</strong><small>Tier 1 <= 200, Tier 2 201-350, Tier 3 351-500</small></td></tr></tbody></table></article></div>
        </section>
</template>
