function setRiskAcceptanceEditable(editable) { $('riskAcceptanceForm').querySelectorAll('input, textarea, select').forEach(element => { if (element.id !== 'riskAcceptanceId') element.disabled = !editable; }); $('riskAcceptanceSubmit').disabled = !editable; $('riskAcceptanceCancel').disabled = !editable; $('riskAcceptanceSubmit').hidden = !editable; $('riskAcceptanceCancel').hidden = !editable; }
function resetRiskAcceptanceForm() { $('riskAcceptanceForm').reset(); $('riskAcceptanceId').value = ''; setRiskAcceptanceEditable(true); $('riskAcceptanceSubmit').textContent = 'Save risk acceptance form'; $('riskAcceptanceStatus').textContent = 'New form'; $('riskAcceptanceFormStatus').textContent = 'Ready'; }
function riskDate(value) { return value ? String(value).slice(0, 10) : ''; }
function riskFormData() { return { requestorName: $('riskRequestorName').value, assetName: $('riskAssetName').value, department: $('riskDepartment').value, previouslyAccepted: $('riskPreviouslyAccepted').checked, riskDescription: $('riskDescription').value, benefitJustification: $('riskBenefitJustification').value, mitigationPlan: $('riskMitigationPlan').value, businessOwnerDecision: $('riskBusinessOwnerDecision').value, remediationDate: $('riskRemediationDate').value, requestorPrintName: $('riskRequestorPrintName').value, requestorEmailPhone: $('riskRequestorEmailPhone').value, requestorSignature: $('riskRequestorSignature').value, requestorDate: $('riskRequestorDate').value, cioComments: $('riskCioComments').value, cioName: $('riskCioName').value, cioSignature: $('riskCioSignature').value, cioDate: $('riskCioDate').value, cisDecision: $('riskCisDecision').value, cisReason: $('riskCisReason').value, cisConditions: $('riskCisConditions').value, cisName: $('riskCisName').value, cisSignature: $('riskCisSignature').value, cisDate: $('riskCisDate').value }; }
function fillRiskAcceptanceForm(form) { setRiskAcceptanceEditable(true); $('riskAcceptanceId').value = form.id; $('riskRequestorName').value = form.requestorName; $('riskAssetName').value = form.assetName; $('riskDepartment').value = form.department; $('riskPreviouslyAccepted').checked = form.previouslyAccepted; $('riskDescription').value = form.riskDescription; $('riskBenefitJustification').value = form.benefitJustification; $('riskMitigationPlan').value = form.mitigationPlan; $('riskBusinessOwnerDecision').value = form.businessOwnerDecision; $('riskRemediationDate').value = riskDate(form.remediationDate); $('riskRequestorPrintName').value = form.requestorPrintName; $('riskRequestorEmailPhone').value = form.requestorEmailPhone; $('riskRequestorSignature').value = form.requestorSignature; $('riskRequestorDate').value = riskDate(form.requestorDate); $('riskCioComments').value = form.cioComments; $('riskCioName').value = form.cioName; $('riskCioSignature').value = form.cioSignature; $('riskCioDate').value = riskDate(form.cioDate); $('riskCisDecision').value = form.cisDecision; $('riskCisReason').value = form.cisReason; $('riskCisConditions').value = form.cisConditions; $('riskCisName').value = form.cisName; $('riskCisSignature').value = form.cisSignature; $('riskCisDate').value = riskDate(form.cisDate); $('riskAcceptanceSubmit').textContent = 'Update risk acceptance form'; $('riskAcceptanceStatus').textContent = `Editing form #${form.id}`; window.scrollTo({ top: 0, behavior: 'smooth' }); }
function viewRiskAcceptanceForm(form) { fillRiskAcceptanceForm(form); setRiskAcceptanceEditable(false); $('riskAcceptanceStatus').textContent = `Viewing form #${form.id}`; }
function renderRiskAcceptanceForms() { const body = $('riskAcceptanceBody'); if (!body) return; $('riskAcceptanceCount').textContent = `${riskAcceptanceForms.length} form${riskAcceptanceForms.length === 1 ? '' : 's'}`; riskAcceptancePage = renderListPagination('riskAcceptancePagination', riskAcceptancePage, riskAcceptanceForms.length, 'forms'); const visible = riskAcceptanceForms.slice((riskAcceptancePage - 1) * 20, riskAcceptancePage * 20); body.innerHTML = visible.map(form => `<tr><td>${escapeHtml(form.requestorName)}</td><td>${escapeHtml(form.assetName)}</td><td>${escapeHtml(form.department)}</td><td>${escapeHtml(form.businessOwnerDecision)}</td><td>${escapeHtml(form.cisDecision)}</td><td>${riskDate(form.updatedAt)}</td><td><button class="attachment-action-button" type="button" data-risk-view="${form.id}">View</button><button class="attachment-action-button" type="button" data-risk-edit="${form.id}">Edit</button><button class="attachment-action-button" type="button" data-risk-pdf="${form.id}">PDF</button><button class="attachment-action-button danger" type="button" data-risk-delete="${form.id}">Delete</button></td></tr>`).join('') || '<tr><td colspan="7">No risk acceptance forms found.</td></tr>'; }
async function loadRiskAcceptanceForms() { const response = await fetch('/api/risk-acceptance', { cache: 'no-store' }); if (!response.ok) throw new Error('Risk acceptance data unavailable'); riskAcceptanceForms = await response.json(); renderRiskAcceptanceForms(); }
async function saveRiskAcceptanceForm(event) { event.preventDefault(); const id = $('riskAcceptanceId').value; const response = await fetch(id ? `/api/risk-acceptance/${encodeURIComponent(id)}` : '/api/risk-acceptance', { method: id ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(riskFormData()) }); if (!response.ok) { const error = await response.json().catch(() => ({})); $('riskAcceptanceFormStatus').textContent = error.error || 'Save failed'; return; } await loadRiskAcceptanceForms(); resetRiskAcceptanceForm(); $('riskAcceptanceFormStatus').textContent = id ? 'Form updated' : 'Form saved'; }
async function deleteRiskAcceptanceForm(id) { if (!confirm(`Delete risk acceptance form #${id}?`)) return; const response = await fetch(`/api/risk-acceptance/${encodeURIComponent(id)}`, { method: 'DELETE' }); if (!response.ok) { $('riskAcceptanceFormStatus').textContent = 'Delete failed'; return; } await loadRiskAcceptanceForms(); }
function showRiskAcceptanceView() { document.querySelectorAll('.view').forEach(view => view.classList.remove('active-view')); $('riskAcceptanceView').classList.add('active-view'); document.querySelectorAll('.nav-item').forEach(item => item.classList.toggle('active', item.dataset.view === 'risk-acceptance')); renderRiskAcceptanceForms(); saveUiState('risk-acceptance'); }
let policyRegisterRows = [];
const policyDropdownDefaults = {
  categories: ['Cybersecurity', 'IT Governance', 'Privacy', 'Risk Management', 'HR & Compliance'],
  owners: ['CISO', 'IT Manager', 'Data Protection Officer', 'Security Manager', 'Legal', 'Procurement'],
  reviewCycles: ['Annual', 'Biannual', 'Quarterly', 'Ad hoc'],
  approvalStatuses: ['Approved', 'Draft', 'Review due', 'Expired'],
};

const policyDropdownState = {
  categories: [...(policyDropdownDefaults.categories || [])],
  owners: [...(policyDropdownDefaults.owners || [])],
  reviewCycles: [...(policyDropdownDefaults.reviewCycles || [])],
  approvalStatuses: [...(policyDropdownDefaults.approvalStatuses || [])],
};

